Repository agda/agda-stdlib, pull requests merged in 2018-04, with the labels that each got.

#262 [ re #260 ] => associates to the right
  CHANGELOG.md
  src/Relation/Unary.agda
Labels: bug

#246 Added Relation.Unary.Properties
  CHANGELOG.md
  src/Data/List/Base.agda
  src/Data/List/Properties.agda
  src/Relation/Unary.agda
  src/Relation/Unary/Properties.agda
Labels: enhancement, library-design

#261 [ re #258 ] Utility functions on N-ary products
  CHANGELOG.md
  src/Data/Product/N-ary.agda
  src/Data/Product/N-ary/Properties.agda
Labels: enhancement

#277 Add indexed functions in `Relation.Binary.HeterogeneousEquality`
  CHANGELOG.md
  src/Relation/Binary/HeterogeneousEquality.agda
Labels: enhancement

#280 Add injectivity proofs for `_++_` in `Data.Vec.Properties`
  CHANGELOG.md
  src/Data/Vec/Properties.agda
Labels: enhancement

#281 Add proof of associativity of `_++_` in `Data.Vec.Properties`
  CHANGELOG.md
  src/Data/Vec/Properties.agda
Labels: enhancement

#285 Add insert and remove to Data.Vec
  CHANGELOG.md
  src/Data/Vec.agda
  src/Data/Vec/Properties.agda
Labels: enhancement

#272 [ refactor ] Data.Table
  src/Data/Table/Base.agda
Labels: enhancement

#298 [ new ] fromList : List A → Maybe (List⁺ A)
  CHANGELOG.md
  src/Data/List/NonEmpty.agda
Labels: enhancement

#299 [ new ] functions in Data.String
  CHANGELOG.md
  src/Data/String/Base.agda
Labels: enhancement

#302 [ refactor ] structural definition of reverseView
  CHANGELOG.md
  src/Data/List/Reverse.agda
Labels: enhancement

#252 Adding `Data.Fin.Permutation`
  CHANGELOG.md
  src/Data/Fin/Permutation.agda
  src/Data/Fin/Permutation/Components.agda
  src/Data/Fin/Properties.agda
  src/Data/Graph/Acyclic.agda
Labels: enhancement

#296 Tidying `Data.Fin.Properties`
  CHANGELOG.md
  src/Data/Bin/Properties.agda
  src/Data/Fin/Permutation/Components.agda
  src/Data/Fin/Properties.agda
  src/Data/Nat/Divisibility.agda
Labels: enhancement, question
