Repository agda/agda-stdlib, pull requests merged in 2018-08, with the labels that each got.

#390 [ fix #389 ] refactoring in Function.Related.TypeIsomorphisms
  CHANGELOG.md
  src/Data/Container/Any.agda
  src/Data/List/Membership/Propositional/Properties.agda
  src/Data/List/Relation/BagAndSetEquality.agda
  src/Data/Product/Relation/Pointwise/NonDependent.agda
  src/Data/Sum/Relation/Pointwise.agda
  src/Function/Related.agda
  src/Function/Related/TypeIsomorphisms.agda
Labels: refactoring

#398 [ fix #328 ] level polymorphism in Data.Star.*
  CHANGELOG.md
  src/Data/Star/Decoration.agda
  src/Data/Star/Environment.agda
  src/Data/Star/Pointer.agda
Labels: breaking, enhancement

#399 [ fix #396 ] Merging all Category.X.Identity into Function.Identity.Categorical
  CHANGELOG.md
  src/Algebra/Properties/BooleanAlgebra/Expression.agda
  src/Category/Comonad/Identity.agda
  src/Category/Functor/Identity.agda
  src/Category/Monad/Continuation.agda
  src/Category/Monad/Identity.agda
  src/Category/Monad/State.agda
  src/Data/List/NonEmpty/Categorical.agda
  src/Data/Maybe.agda
  src/Data/Maybe/Categorical.agda
  src/Data/Product/Categorical.agda
  src/Data/Sum/Categorical.agda
  src/Data/Vec/Categorical.agda
  src/Function/Identity/Categorical.agda
Labels: breaking, library-design

#404 [ re #365 ] Last stretch towards Categorical Overhaul
  CHANGELOG.md
  src/Category/Monad.agda
  src/Category/Monad/Indexed.agda
  src/Codata/Colist.agda
  src/Codata/Colist/Categorical.agda
  src/Codata/Covec.agda
  src/Codata/Covec/Categorical.agda
  src/Codata/Stream.agda
  src/Codata/Stream/Categorical.agda
  src/Data/List/Categorical.agda
  src/Data/List/NonEmpty/Categorical.agda
  src/Data/Maybe/Categorical.agda
  src/Data/Product/Categorical.agda
  src/Data/Sum/Categorical.agda
Labels: enhancement

#410 [ new ] synonym for Level.zero
  CHANGELOG.md
  src/Data/List/Countdown.agda
  src/Data/Nat/Base.agda
  src/Data/Nat/InfinitelyOften.agda
  src/Function/Related/TypeIsomorphisms.agda
  src/Level.agda
  src/Level/Literals.agda
Labels: enhancement, question

#415 Codata: toMusical & guarded append
  CHANGELOG.md
  src/Codata/Colist.agda
  src/Codata/Conat.agda
  src/Codata/Covec.agda
  src/Codata/Stream.agda
Labels: enhancement

#405 [ fix #365 ] final step: comonad for Product
  CHANGELOG.md
  src/Data/Product/Categorical.agda
  src/Data/Product/Categorical/Examples.agda
  src/Data/Product/Categorical/Left.agda
  src/Data/Product/Categorical/Left/Base.agda
  src/Data/Product/Categorical/Right.agda
  src/Data/Product/Categorical/Right/Base.agda
  src/Data/Sum/Categorical.agda
  src/Data/Sum/Categorical/Examples.agda
  src/Data/Sum/Categorical/Left.agda
  src/Data/Sum/Categorical/Right.agda
Labels: enhancement, library-design, question

#413 Deprivatising `Function.Related`
  CHANGELOG.md
  src/Data/Container/Any.agda
  src/Data/List/Any/Properties.agda
  src/Data/List/Relation/BagAndSetEquality.agda
  src/Data/Product/Relation/Pointwise/Dependent.agda
  src/Data/Product/Relation/Pointwise/NonDependent.agda
  src/Data/Sum/Relation/Pointwise.agda
  src/Function/Related.agda
  src/Function/Related/TypeIsomorphisms.agda
Labels: deprecation, enhancement, library-design

#418 Cofin, vec lookup, literals
  CHANGELOG.md
  src/Codata/Cofin.agda
  src/Codata/Cofin/Literals.agda
  src/Codata/Conat.agda
  src/Codata/Conat/Properties.agda
  src/Codata/Covec.agda
Labels: enhancement

#379 Data.W and Codata.(Musical.)M using Container
  CHANGELOG.md
  README/Container/FreeMonad.agda
  src/Codata/M.agda
  src/Codata/Musical/M.agda
  src/Data/Container.agda
  src/Data/Container/Core.agda
  src/Data/Container/FreeMonad.agda
  src/Data/W.agda
Labels: enhancement

#424 [ new ] more basic functions for Data.These
  CHANGELOG.md
  src/Codata/Delay.agda
  src/Data/These.agda
  src/Data/These/Categorical/Left.agda
  src/Data/These/Categorical/Left/Base.agda
  src/Data/These/Categorical/Right.agda
  src/Data/These/Categorical/Right/Base.agda
Labels: enhancement

#412 [ new ] Closure of a Pred wrt a (pre/strict partial)order
  CHANGELOG.md
  src/Relation/Unary/Closure/Base.agda
  src/Relation/Unary/Closure/Preorder.agda
  src/Relation/Unary/Closure/StrictPartialOrder.agda
Labels: enhancement

#414 [ new ] Factoring out unsafe parts of the library
  .travis.yml
  CHANGELOG.md
  README.md
  README/Function/Reasoning.agda
  README/Record.agda
  index.sh
  src/Data/Char.agda
  src/Data/Char/Base.agda
  src/Data/Char/Unsafe.agda
  src/Data/Digit.agda
  src/Data/Float.agda
  src/Data/Float/Unsafe.agda
  src/Data/Nat/Base.agda
  src/Data/Nat/DivMod.agda
  src/Data/Nat/DivMod/Unsafe.agda
  src/Data/Nat/Unsafe.agda
  src/Data/String.agda
  src/Data/String/Base.agda
  src/Data/String/Unsafe.agda
  src/Data/Word.agda
  src/Data/Word/Unsafe.agda
  src/EverythingSafe.agda
  src/Reflection.agda
  src/Relation/Binary/HeterogeneousEquality/Quotients.agda
  src/Relation/Binary/HeterogeneousEquality/Quotients/Examples.agda
  travis/index.agda
  travis/index.sh
  travis/safe.agda
Labels: enhancement, library-design, refactoring
