Repository agda/agda-stdlib, pull requests merged in 2018-06, with the labels that each got.

#327 fix #295
  src/Data/Graph/Acyclic.agda
  src/Data/List/Any/Properties.agda
  src/Data/List/Countdown.agda
  src/Data/List/Relation/Sublist/Propositional/Properties.agda
  src/Data/List/Reverse.agda
Labels: bug

#270 Codata using sized types and copatterns
  CHANGELOG.md
  src/Codata/Colist.agda
  src/Codata/Colist/Bisimilarity.agda
  src/Codata/Colist/Properties.agda
  src/Codata/Conat.agda
  src/Codata/Conat/Bisimilarity.agda
  src/Codata/Conat/Properties.agda
  src/Codata/Covec.agda
  src/Codata/Covec/Bisimilarity.agda
  src/Codata/Covec/Properties.agda
  src/Codata/Delay.agda
  src/Codata/Delay/Bisimilarity.agda
  src/Codata/Delay/Properties.agda
  src/Codata/Stream.agda
  src/Codata/Stream/Bisimilarity.agda
  src/Codata/Stream/Properties.agda
  src/Codata/Thunk.agda
Labels: enhancement, library-design

#332 [ Fixed #330 ] made readFileUTF8 close the handle before returning
  GenerateEverything.hs
Labels: bug

#336 Fixup Updated CHANGELOG, README etc for release
  README.md
Labels: bug

#325 add different definitions of permutation
  CHANGELOG.md
  src/Data/List/Any/Properties.agda
  src/Data/List/Membership/Propositional/Properties.agda
  src/Data/List/Membership/Setoid/Properties.agda
  src/Data/List/Relation/Permutation/Inductive.agda
  src/Data/List/Relation/Permutation/Inductive/Properties.agda
Labels: enhancement

#338 [ new ] typeOf (A ∋ a) = A
  CHANGELOG.md
  src/Function.agda
Labels: enhancement

#329 [ re #293 ] Adding Order-Preserving Embeddings
  CHANGELOG.md
  src/Data/List/All/Properties.agda
  src/Data/List/Membership/Propositional/Properties.agda
  src/Data/List/Relation/BagAndSetEquality.agda
  src/Data/List/Relation/Sublist/Extensional/Propositional.agda
  src/Data/List/Relation/Sublist/Extensional/Propositional/Properties.agda
  src/Data/List/Relation/Sublist/Extensional/Setoid.agda
  src/Data/List/Relation/Sublist/Extensional/Setoid/Properties.agda
  src/Data/List/Relation/Sublist/Inductive.agda
  src/Function/Injection.agda
Labels: enhancement, library-design

#342 [ fix #339 ] ,_ only stands for _,_'s right section
  CHANGELOG.md
  src/Category/Monad/Partiality.agda
  src/Data/AVL/IndexedMap.agda
  src/Data/Container/Indexed.agda
  src/Data/List/NonEmpty.agda
  src/Data/Product.agda
Labels: bug

#343 Make From-just & From-injₙ's types consistent
  CHANGELOG.md
  README/Case.agda
  src/Algebra/CommutativeMonoidSolver.agda
  src/Algebra/IdempotentCommutativeMonoidSolver.agda
  src/Algebra/Monoid-solver.agda
  src/Data/Maybe/Base.agda
  src/Data/Sum.agda
Labels: library-design

#347 [ fix ] inlining the map in iterate
  src/Codata/Stream.agda
Labels: bug

#349 [ new ] fromMusical coercions
  CHANGELOG.md
  src/Codata/Colist.agda
  src/Codata/Conat.agda
  src/Codata/Covec.agda
  src/Codata/Stream.agda
Labels: enhancement
