Repository agda/agda-stdlib, pull requests merged in 2018-03, with the labels that each got.

#233 Improved product relations
  CHANGELOG.md
  src/Data/Container/Any.agda
  src/Data/List/Any/Membership/Propositional/Properties.agda
  src/Data/List/Any/Properties.agda
  src/Data/Product/Relation/Lex/NonStrict.agda
  src/Data/Product/Relation/Lex/Strict.agda
  src/Data/Product/Relation/Pointwise.agda
  src/Data/Product/Relation/Pointwise/Dependent.agda
  src/Data/Product/Relation/Pointwise/NonDependent.agda
  src/Data/Product/Relation/SigmaPointwise.agda
  src/Function/Related/TypeIsomorphisms.agda
  src/Relation/Binary/Product/NonStrictLex.agda
  src/Relation/Binary/Product/Pointwise.agda
  src/Relation/Binary/Product/StrictLex.agda
  src/Relation/Binary/Sigma/Pointwise.agda
  src/Relation/Nullary/Universe.agda
Labels: enhancement, library-design

#236 Improving sum relations
  CHANGELOG.md
  src/Data/Colist/Infinite-merge.agda
  src/Data/List/Any/BagAndSetEquality.agda
  src/Data/List/Any/Properties.agda
  src/Data/Sum/Relation/Core.agda
  src/Data/Sum/Relation/General.agda
  src/Data/Sum/Relation/LeftOrder.agda
  src/Data/Sum/Relation/Pointwise.agda
  src/Function/Related/TypeIsomorphisms.agda
  src/Relation/Binary/Sum.agda
  src/Relation/Nullary/Universe.agda
Labels: enhancement, library-design

#240 Parameterising `Algebra.Structures` by equality
  CHANGELOG.md
  src/Algebra.agda
  src/Algebra/CommutativeMonoidSolver.agda
  src/Algebra/CommutativeMonoidSolver/Example.agda
  src/Algebra/FunctionProperties.agda
  src/Algebra/FunctionProperties/Consequences.agda
  src/Algebra/IdempotentCommutativeMonoidSolver.agda
  src/Algebra/IdempotentCommutativeMonoidSolver/Example.agda
  src/Algebra/Monoid-solver.agda
  src/Algebra/Morphism.agda
  src/Algebra/Operations.agda
  src/Algebra/Properties/AbelianGroup.agda
  src/Algebra/Properties/BooleanAlgebra.agda
  src/Algebra/Properties/Group.agda
  src/Algebra/Properties/Ring.agda
  src/Algebra/RingSolver/Lemmas.agda
  src/Algebra/Structures.agda
  src/Data/Bool/Properties.agda
  src/Data/Fin.agda
  src/Data/Integer/Properties.agda
  src/Data/Nat/Properties.agda
Labels: enhancement, library-design

#245 Functional reasoning (version 2)
  CHANGELOG.md
  README.agda
  README/Function/Reasoning.agda
  src/Function.agda
  src/Function/Reasoning.agda
Labels: enhancement, library-design

#250 Opening PR to see whether the travis build succeeds
  .travis.yml
Labels: test, travis

#242 Added new `Respects` types and tidied up `Relation.Binary.NonStrictToStrict`
  CHANGELOG.md
  src/Data/List/Base.agda
  src/Data/List/Relation/Lex/NonStrict.agda
  src/Data/Product/Relation/Lex/NonStrict.agda
  src/Relation/Binary/Core.agda
  src/Relation/Binary/NonStrictToStrict.agda
  src/Relation/Binary/Properties/DecTotalOrder.agda
  src/Relation/Binary/Properties/Poset.agda
Labels: enhancement

#243 Moving `Maximum` and `Minimum` to `Relation.Binary.Core`
  CHANGELOG.md
  src/Relation/Binary/Core.agda
  src/Relation/Binary/Lattice.agda
Labels: enhancement, library-design
