Repository agda/agda-stdlib, pull requests merged in 2018-11, with the labels that each got.

#504 [ new ] some properties of Any/membership
  CHANGELOG.md
  src/Data/List/Membership/Propositional/Properties.agda
  src/Data/Vec/Any/Properties.agda
  src/Data/Vec/Membership/Propositional/Properties.agda
Labels: enhancement

#484 Missing update/fromFin functions in Membership
  CHANGELOG.md
  src/Data/Fin/Base.agda
  src/Data/Fin/Properties.agda
  src/Data/List/Base.agda
  src/Data/List/Membership/Propositional/Properties.agda
  src/Data/List/Membership/Setoid.agda
  src/Data/List/Membership/Setoid/Properties.agda
  src/Data/List/Properties.agda
Labels: enhancement

#470 [ new ] add a few more lattice theoretic theorems
  CHANGELOG.md
  src/Relation/Binary/Lattice.agda
  src/Relation/Binary/Properties/BoundedLattice.agda
  src/Relation/Binary/Properties/BoundedMeetSemilattice.agda
  src/Relation/Binary/Properties/DistributiveLattice.agda
  src/Relation/Binary/Properties/HeytingAlgebra.agda
  src/Relation/Binary/Properties/JoinSemilattice.agda
  src/Relation/Binary/Properties/Lattice.agda
  src/Relation/Binary/Properties/MeetSemilattice.agda
Labels: enhancement

#477 [ new ] Bisimilarity and properties for M-types
  CHANGELOG.md
  README/Container/FreeMonad.agda
  src/Codata/M/Bisimilarity.agda
  src/Codata/M/Properties.agda
  src/Codata/Stream/Bisimilarity.agda
  src/Data/Container.agda
  src/Data/Container/Any.agda
  src/Data/Container/Combinator.agda
Labels: enhancement

#450 [ new ] Without Loss Of Generality
  CHANGELOG.md
  src/Algebra/FunctionProperties/Consequences.agda
  src/Algebra/FunctionProperties/Consequences/Propositional.agda
  src/Relation/Binary/Consequences.agda
Labels: enhancement

#516 [ new ] functions in Codata.Stream
  CHANGELOG.md
  src/Codata/Stream.agda
  src/Codata/Stream/Properties.agda
Labels: enhancement

#528 Added thunk-syntax to mimic syntax for products etc
  src/Codata/Thunk.agda
Labels: enhancement

#511 Relax decidability module parameter of Algebra.Solver.Ring
  CHANGELOG.md
  src/Algebra/Solver/IdempotentCommutativeMonoid.agda
  src/Algebra/Solver/Ring.agda
  src/Algebra/Solver/Ring/NaturalCoefficients.agda
  src/Algebra/Solver/Ring/NaturalCoefficients/Default.agda
  src/Algebra/Solver/Ring/Simple.agda
  src/Data/Bool.agda
  src/Data/Bool/Base.agda
  src/Data/Bool/Properties.agda
  src/Data/Fin/Subset/Properties.agda
  src/Function/Related/TypeIsomorphisms/Solver.agda
  src/Relation/Binary/Consequences.agda
  src/Relation/Binary/Core.agda
Labels: breaking, enhancement, refactoring

#456 [ new ] added `IsMagma`, `RawMagma` and `Magma` to `Algebra`
  CHANGELOG.md
  src/Algebra.agda
  src/Algebra/Structures.agda
Labels: enhancement

#520 [ fix #503, fix #514 ] Changing some explicit/implicit arguments
  CHANGELOG.md
  src/Data/List/Membership/Propositional/Properties.agda
  src/Data/List/Relation/Permutation/Inductive/Properties.agda
  src/Data/List/Relation/Subset/Propositional/Properties.agda
Labels: breaking, bug

#524 [ refactor ] moved `sel⇒idem` to `Algebra.FunctionProperties.Consequences.Propositional`
  CHANGELOG.md
  src/Algebra/FunctionProperties/Consequences.agda
  src/Algebra/FunctionProperties/Consequences/Propositional.agda
  src/Data/Integer/Properties.agda
  src/Data/Nat/Properties.agda
Labels: breaking

#525 [ fix #512 ] generalised Maybe.Relation.Pointwise
  CHANGELOG.md
  src/Data/Maybe/Relation/Pointwise.agda
Labels: enhancement

#487 [ new ] chunksOf for stream & colist
  CHANGELOG.md
  src/Codata/Colist.agda
  src/Codata/Cowriter.agda
  src/Codata/Stream.agda
Labels: enhancement, library-design, question

#534 .travis.yml: "intallplan.txt" -> "installplan.txt"
  .travis.yml
Labels: bug

#543 Update Data.List.Membership.DecPropositional.
  src/Data/List/Membership/DecPropositional.agda
Labels: bug, enhancement, status:ready

#522 [ re #517 ] First steps towards formalizing Prefix
  CHANGELOG.md
  src/Data/Fin/Subset/Properties.agda
  src/Data/List/Base.agda
  src/Data/List/Membership/Propositional/Properties.agda
  src/Data/List/Relation/Prefix/Heterogeneous.agda
  src/Data/List/Relation/Prefix/Heterogeneous/Properties.agda
  src/Relation/Binary/Core.agda
Labels: enhancement, status:ready

#530 [ refactor ] Stream's iterate
  CHANGELOG.md
  src/Codata/Stream.agda
  src/Codata/Stream/Properties.agda
Labels: refactoring, status:ready

#535 [ refactor ] straightening out the Algebra hierarchy
  CHANGELOG.md
  src/Algebra.agda
  src/Algebra/Properties/BooleanAlgebra.agda
  src/Algebra/Properties/BooleanAlgebra/Expression.agda
  src/Algebra/Properties/DistributiveLattice.agda
  src/Algebra/Properties/Lattice.agda
  src/Algebra/Structures.agda
  src/Data/Bool/Properties.agda
  src/Data/Fin/Subset/Properties.agda
  src/Data/Integer/Properties.agda
  src/Data/List/Properties.agda
  src/Data/List/Relation/BagAndSetEquality.agda
  src/Data/List/Relation/Permutation/Inductive/Properties.agda
  src/Data/Maybe/Properties.agda
  src/Data/Nat/Properties.agda
  src/Data/Sign/Properties.agda
  src/Function/Related/TypeIsomorphisms.agda
  src/Relation/Binary/Properties/Lattice.agda
Labels: breaking, library-design, refactoring, status:ready

#538 added transitivity for ≤′
  CHANGELOG.md
  src/Data/Nat/Properties.agda
Labels: enhancement

#544 Add properties of algebraic semilattices
  CHANGELOG.md
  src/Algebra.agda
  src/Algebra/Properties/BooleanAlgebra.agda
  src/Algebra/Properties/BooleanAlgebra/Expression.agda
  src/Algebra/Properties/Lattice.agda
  src/Algebra/Properties/Semilattice.agda
  src/Algebra/Structures.agda
  src/Data/Bool/Properties.agda
  src/Data/Fin/Subset/Properties.agda
  src/Data/Nat/Properties.agda
  src/Relation/Binary/Properties/JoinSemilattice.agda
  src/Relation/Binary/Properties/Lattice.agda
  src/Relation/Binary/Properties/MeetSemilattice.agda
Labels: enhancement

#537 [ new ] added left and right natural orders
  CHANGELOG.md
  src/Relation/Binary/Construct/NaturalOrder/Left.agda
  src/Relation/Binary/Construct/NaturalOrder/Right.agda
Labels: enhancement, refactoring, status:ready
