Repository agda/agda-stdlib, pull requests merged in 2018-09, with the labels that each got.

#427 [ new ] conversion from bag equality to Permutation
  src/Data/List/Relation/Permutation/Inductive/Properties.agda
Labels: enhancement

#435 [ fix #433 ] added extra properties about strict relations
  CHANGELOG.md
  src/Relation/Binary.agda
  src/Relation/Binary/NonStrictToStrict.agda
  src/Relation/Binary/PropositionalEquality/TrustMe.agda
  src/Relation/Binary/StrictToNonStrict.agda
Labels: bug, enhancement

#426 [ fix #425 ] Added more raw algebras
  CHANGELOG.md
  src/Algebra.agda
Labels: enhancement

#422 [ re #334 ] Moving Coinduction to Codata.Musical.Notation
  CHANGELOG.md
  README.agda
  src/Category/Monad/Partiality.agda
  src/Category/Monad/Partiality/All.agda
  src/Codata/Cofin.agda
  src/Codata/Colist.agda
  src/Codata/Conat.agda
  src/Codata/Covec.agda
  src/Codata/M.agda
  src/Codata/Musical/Cofin.agda
  src/Codata/Musical/Colist.agda
  src/Codata/Musical/Colist/Infinite-merge.agda
  src/Codata/Musical/Conat.agda
  src/Codata/Musical/Covec.agda
  src/Codata/Musical/M.agda
  src/Codata/Musical/M/Indexed.agda
  src/Codata/Musical/Notation.agda
  src/Codata/Musical/Stream.agda
  src/Codata/Stream.agda
  src/Coinduction.agda
  src/IO.agda
Labels: breaking, refactoring

#423 [ new ] OPEs properties wrt list functions
  src/Data/List/Relation/Sublist/Inductive.agda
  src/Data/List/Relation/Sublist/Inductive/Properties.agda
  src/Data/List/Relation/Sublist/Inductive/Solver.agda
Labels: enhancement

#411 [ new ] Record hierarchy for `Relation.Binary.Indexed.Homogeneous`
  CHANGELOG.md
  src/Relation/Binary/Indexed/Homogeneous.agda
  src/Relation/Binary/Indexed/Homogeneous/Core.agda
  src/Relation/Unary/Indexed.agda
Labels: enhancement, library-design, question

#463 [ new ] flipped version of <$>
  CHANGELOG.md
  src/Category/Functor.agda
Labels: enhancement

#420 [ fix #409 ] Syntax for implicit universal
  CHANGELOG.md
  src/Relation/Unary.agda
Labels: enhancement

#443 [ new ] implemented more order theories
  CHANGELOG.md
  src/Relation/Binary/Lattice.agda
  src/Relation/Binary/Properties/DistributiveLattice.agda
  src/Relation/Binary/Properties/HeytingAlgebra.agda
Labels: deprecation, enhancement

#449 [ refactor ] deprecated im≡jm+n⇒[i∸j]m≡n and i∸k∸j+j∸k≡i+j∸k in Data.Nat.Properties
  CHANGELOG.md
  src/Data/Nat/Coprimality.agda
  src/Data/Nat/GCD.agda
  src/Data/Nat/GCD/Lemmas.agda
  src/Data/Nat/InfinitelyOften.agda
  src/Data/Nat/Primality.agda
  src/Data/Nat/Properties.agda
Labels: deprecation, refactoring
