Repository agda/agda-stdlib, pull requests merged in 2018-07, with the labels that each got.

#357 [ new ] map1 and map2 for Sum
  CHANGELOG.md
  src/Data/Sum/Base.agda
Labels: enhancement

#350 [ new ] useful modular arithmetic
  CHANGELOG.md
  src/Data/Fin/Properties.agda
  src/Data/Nat/DivMod.agda
  src/Data/Nat/DivMod/Core.agda
  src/Data/Nat/Divisibility.agda
Labels: enhancement, library-design, question

#358 [ fix #355 ] Pair to use in the FFI
  CHANGELOG.md
  src/Foreign/Haskell.agda
Labels: enhancement

#345 [ fix #335 ] Lift now takes an explicit Level
  CHANGELOG.md
  README/Record.agda
  src/Category/Monad/State.agda
  src/Data/AVL/Key.agda
  src/Data/Container/Combinator.agda
  src/Data/Container/Indexed/Combinator.agda
  src/Data/Maybe/Base.agda
  src/Data/Product/N-ary.agda
  src/Data/Sum.agda
  src/Function/Related/TypeIsomorphisms.agda
  src/IO.agda
  src/Induction/Nat.agda
  src/Level.agda
  src/Record.agda
  src/Relation/Binary/Simple.agda
  src/Relation/Nullary/Decidable.agda
  src/Relation/Nullary/Universe.agda
Labels: library-design

#366 [ new ] fromList⁺ : List⁺ Char → String
  CHANGELOG.md
  src/Data/String/Base.agda
Labels: enhancement

#374 [ fix #373 ] *-distrib-∸ & ^-assoc
  CHANGELOG.md
  src/Data/Nat/Properties.agda
Labels: enhancement

#376 [ fix #351 ] change the precedence level of $
  CHANGELOG.md
  src/Function.agda
Labels: bug, library-design

#368 [ fix #364 ] Propositional function spaces
  CHANGELOG.md
  src/Codata/Musical/Colist.agda
  src/Codata/Musical/Colist/Infinite-merge.agda
  src/Data/Container/Any.agda
  src/Data/Container/Combinator.agda
  src/Data/Container/Indexed/Combinator.agda
  src/Data/List/All/Properties.agda
  src/Data/List/Any/Properties.agda
  src/Data/List/Membership/Propositional/Properties.agda
  src/Data/List/Membership/Propositional/Properties/Core.agda
  src/Data/List/Relation/BagAndSetEquality.agda
  src/Data/List/Relation/Permutation/Inductive/Properties.agda
  src/Data/Product/N-ary/Properties.agda
  src/Data/Vec/All/Properties.agda
  src/Data/Vec/Properties.agda
  src/Function/Bijection.agda
  src/Function/Equality.agda
  src/Function/Equivalence.agda
  src/Function/Injection.agda
  src/Function/Inverse.agda
  src/Function/LeftInverse.agda
  src/Function/Related/TypeIsomorphisms.agda
  src/Function/Surjection.agda
Labels: enhancement

#372 [ new ] nat-computed levels
  CHANGELOG.md
  src/Level.agda
Labels: enhancement

#375 Deprecating `Data.Fin.Dec`
  CHANGELOG.md
  src/Data/Fin/Dec.agda
  src/Data/Fin/Properties.agda
  src/Data/Fin/Subset.agda
  src/Data/Fin/Subset/Properties.agda
  src/Data/Nat/Primality.agda
  src/Relation/Unary/Properties.agda
Labels: deprecation, library-design

#361 [ fix #221 ] Functor, Applicative, Monad instances for Sum
  CHANGELOG.md
  src/Data/Sum/Categorical.agda
Labels: enhancement

#384 [ new ] missing sequence(A/M), map(A/M), for(A/M)
  CHANGELOG.md
  src/Data/Vec/Categorical.agda
Labels: enhancement

#385 [ new ] Data.Product.N-ary.Categorical
  CHANGELOG.md
  src/Data/Product/N-ary/Categorical.agda
Labels: enhancement

#382 [ re #365 ] Categorical: Delay and Stream
  CHANGELOG.md
  src/Codata/Delay.agda
  src/Codata/Delay/Categorical.agda
  src/Codata/Stream/Categorical.agda
  src/Data/These.agda
Labels: enhancement

#388 Added some more `Vec` properties
  CHANGELOG.md
  src/Data/Vec/All/Properties.agda
  src/Data/Vec/Membership/Propositional/Properties.agda
  src/Data/Vec/Properties.agda
  src/Data/Vec/Relation/Pointwise/Inductive.agda
Labels: enhancement

#386 [ new ] comonad + identity & NonEmpty instances
  CHANGELOG.md
  src/Category/Comonad.agda
  src/Category/Comonad/Identity.agda
  src/Category/Monad/Identity.agda
  src/Data/List/NonEmpty.agda
  src/Data/List/NonEmpty/Categorical.agda
Labels: enhancement

#387 [ new ] Proof of the pigeonhole principle
  CHANGELOG.md
  src/Data/Fin/Properties.agda
Labels: enhancement

#394 [ fix #393 ] move nat-computed levels to their own module
  CHANGELOG.md
  src/Level.agda
  src/Level/Literals.agda
Labels: library-design

#403 [ fix #401 ] Remove Data.Char.Core
  CHANGELOG.md
  src/Data/Char/Base.agda
  src/Data/Char/Core.agda
  src/Data/String/Base.agda
Labels: breaking, library-design, refactoring
