Repository agda/agda-stdlib, pull requests merged in 2019-09, with the labels that each got.

#805 Kleene lists
  CHANGELOG.md
  src/Data/List/Kleene.agda
  src/Data/List/Kleene/AsList.agda
  src/Data/List/Kleene/Base.agda
Labels: enhancement, library-design, status:ready

#872 [ new ] Add constructors for new propositional function packages
  src/Function/Packages.agda
Labels: enhancement

#873 Proofs about identity and composition for the new function hierarchy
  CHANGELOG.md
  src/Function/Construct/Composition.agda
  src/Function/Construct/Identity.agda
  src/Function/Packages.agda
  src/Function/Structures.agda
Labels: enhancement

#871 [ fix #859 ] Add a link to the index to the front-page
  README.md
Labels: documentation

#869 [ fix #868 ] Add Data.AVL.Map
  CHANGELOG.md
  src/Data/AVL/Map.agda
Labels: enhancement, status:ready

#864 [ fix #826 ] Coercible type class
  .travis.yml
  GenerateEverything.hs
  README/Foreign/Haskell.agda
  src/Data/Maybe/Base.agda
  src/Foreign/Haskell/Coerce.agda
  src/Foreign/Haskell/Maybe.agda
  src/Foreign/Haskell/Pair.agda
Labels: FFI, bug, enhancement, status:ready

#875 Improved inheritance in binary relation properties files
  CHANGELOG.md
  src/Algebra/Properties/Semilattice.agda
  src/Relation/Binary/Consequences.agda
  src/Relation/Binary/Construct/NonStrictToStrict.agda
  src/Relation/Binary/Properties/DecTotalOrder.agda
  src/Relation/Binary/Properties/Poset.agda
  src/Relation/Binary/Properties/Preorder.agda
  src/Relation/Binary/Properties/StrictTotalOrder.agda
  src/Relation/Binary/Properties/TotalOrder.agda
Labels: enhancement, library-design, status:ready

#840 Order for `Data.Bin`
  CHANGELOG.md
  src/Data/Bin.agda
  src/Data/Bin/Base.agda
  src/Data/Bin/Induction.agda
  src/Data/Bin/Properties.agda
  src/Data/Nat/Properties.agda
Labels: enhancement, status:ready

#856 Sublist union
  CHANGELOG.md
  src/Data/List/Relation/Binary/Sublist/Heterogeneous.agda
  src/Data/List/Relation/Binary/Sublist/Heterogeneous/Core.agda
  src/Data/List/Relation/Binary/Sublist/Heterogeneous/Properties.agda
  src/Data/List/Relation/Binary/Sublist/Propositional.agda
  src/Data/List/Relation/Binary/Sublist/Propositional/Disjoint.agda
  src/Data/List/Relation/Binary/Sublist/Propositional/Example/UniqueBoundVariables.agda
  src/Data/List/Relation/Binary/Sublist/Propositional/Properties.agda
  src/Data/List/Relation/Binary/Sublist/Setoid.agda
  src/Data/List/Relation/Binary/Sublist/Setoid/Properties.agda
  src/Data/List/Relation/Unary/All.agda
  src/Data/List/Relation/Unary/All/Properties.agda
Labels: enhancement, status:not-ready-yet

#889 Remove invalid brackets in function arguments
  src/Data/Bin/Properties.agda
Labels: bug

#881 Changed symbol for left-inverse package and added symbol for right-inverse
  CHANGELOG.md
  src/Function/Construct/Composition.agda
  src/Function/Construct/Identity.agda
  src/Function/Packages.agda
Labels: enhancement, naming, status:ready

#895 [ List.All ] points-to relation and props of updateAt modelled after Vec
  CHANGELOG.md
  src/Data/List/Relation/Unary/All.agda
  src/Data/List/Relation/Unary/All/Properties.agda
  src/Data/Vec/Properties.agda
Labels: enhancement

#883 Reorganisation of the new binary modules
  CHANGELOG.md
  src/Data/Bin.agda
  src/Data/Bin/Properties.agda
  src/Data/Nat/Binary.agda
  src/Data/Nat/Binary/Base.agda
  src/Data/Nat/Binary/Induction.agda
  src/Data/Nat/Binary/Properties.agda
Labels: deprecation, library-design, refactoring, status:ready

#905 remove `Level` import from `Data.Empty`
  src/Data/Empty.agda
Labels: refactoring, status:ready

#899 [ Data.List ] function reverse-append _ʳ++_, simplify proofs about reverse
  CHANGELOG.md
  src/Data/List/Base.agda
  src/Data/List/Properties.agda
  src/Data/List/Relation/Binary/Equality/Setoid.agda
  src/Data/List/Relation/Binary/Pointwise.agda
  src/Data/List/Relation/Binary/Sublist/Heterogeneous/Properties.agda
  src/Data/List/Relation/Binary/Sublist/Setoid/Properties.agda
  src/Data/List/Relation/Ternary/Interleaving/Properties.agda
Labels: enhancement, status:ready

#886 Standardised the binary relation hierarchy
  CHANGELOG.md
  src/Algebra/Solver/Ring.agda
  src/Axiom/UniquenessOfIdentityProofs.agda
  src/Category/Monad/Partiality.agda
  src/Data/Rational/Properties.agda
  src/Relation/Binary.agda
  src/Relation/Binary/Consequences.agda
  src/Relation/Binary/Core.agda
  src/Relation/Binary/Definitions.agda
  src/Relation/Binary/Indexed/Heterogeneous/Core.agda
  src/Relation/Binary/Packages.agda
  src/Relation/Binary/Properties/Setoid.agda
  src/Relation/Binary/PropositionalEquality.agda
  src/Relation/Binary/PropositionalEquality/Core.agda
  src/Relation/Binary/Structures.agda
  src/Relation/Unary/Properties.agda
Labels: library-design, refactoring, status:ready

#878 [ new ] fresh lists
  CHANGELOG.md
  README/Data.agda
  README/Data/List/Fresh.agda
  README/Data/Trie/NonDependent.agda
  src/Data/Char/Properties.agda
  src/Data/List/Fresh.agda
  src/Data/List/Fresh/Membership/Setoid.agda
  src/Data/List/Fresh/Membership/Setoid/Properties.agda
  src/Data/List/Fresh/Properties.agda
  src/Data/List/Fresh/Relation/Unary/All.agda
  src/Data/List/Fresh/Relation/Unary/All/Properties.agda
  src/Data/List/Fresh/Relation/Unary/Any.agda
  src/Data/List/Fresh/Relation/Unary/Any/Properties.agda
  src/Data/List/NonEmpty.agda
  src/Data/List/Properties.agda
  src/Data/Record.agda
  src/Data/String/Properties.agda
  src/Data/Sum/Base.agda
  src/Relation/Nary.agda
  src/Relation/Nullary/Decidable/Core.agda
  src/Relation/Unary.agda
Labels: documentation, enhancement, status:ready

#882 Functional vectors
  CHANGELOG.md
  src/Data/Fin/Base.agda
  src/Data/Fin/Properties.agda
  src/Data/Vec.agda
  src/Data/Vec/Functional.agda
  src/Data/Vec/Functional/Relation/Binary/Pointwise.agda
  src/Data/Vec/Functional/Relation/Binary/Pointwise/Properties.agda
  src/Data/Vec/Functional/Relation/Unary/All.agda
  src/Data/Vec/Functional/Relation/Unary/All/Properties.agda
  src/Data/Vec/Functional/Relation/Unary/Any.agda
Labels: discussion, enhancement, library-design, status:not-ready-yet

#890 Show functions for reflection things
  CHANGELOG.md
  src/Data/String/Base.agda
  src/Reflection/Argument/Relevance.agda
  src/Reflection/Argument/Visibility.agda
  src/Reflection/Definition.agda
  src/Reflection/Literal.agda
  src/Reflection/Pattern.agda
  src/Reflection/Term.agda
Labels: enhancement, status:ready

#880 Added some more properties to Data.Nat.Properties
  CHANGELOG.md
  src/Data/Nat/Properties.agda
Labels: enhancement, status:ready

#910 Added `isDecEquivalence` to `Relation.Binary.PropositionalEquality`
  CHANGELOG.md
  src/Relation/Binary/PropositionalEquality.agda
Labels: enhancement, status:ready

#911 Reorganise `Relation.Binary.Indexed` into the new hierarchy structure
  src/Relation/Binary/Core.agda
  src/Relation/Binary/Definitions.agda
  src/Relation/Binary/Indexed/Heterogeneous.agda
  src/Relation/Binary/Indexed/Heterogeneous/Core.agda
  src/Relation/Binary/Indexed/Heterogeneous/Definitions.agda
  src/Relation/Binary/Indexed/Heterogeneous/Packages.agda
  src/Relation/Binary/Indexed/Heterogeneous/Structures.agda
  src/Relation/Binary/Indexed/Homogeneous.agda
  src/Relation/Binary/Indexed/Homogeneous/Core.agda
  src/Relation/Binary/Indexed/Homogeneous/Definitions.agda
  src/Relation/Binary/Indexed/Homogeneous/Packages.agda
  src/Relation/Binary/Indexed/Homogeneous/Structures.agda
  src/Relation/Binary/Packages.agda
  src/Relation/Binary/Structures.agda
Labels: library-design, refactoring, status:ready
