Repository agda/agda-stdlib, pull requests merged in 2019-11, with the labels that each got.

#959 Added equality relation to `RawRing`
  CHANGELOG.md
  src/Algebra/Bundles.agda
  src/Algebra/Solver/Ring.agda
  src/Algebra/Solver/Ring/AlmostCommutativeRing.agda
  src/Algebra/Solver/Ring/Lemmas.agda
  src/Algebra/Solver/Ring/NaturalCoefficients.agda
Labels: breaking, bug, status:ready

#966 Moved patterns in `Data.Fin.Base` to `Data.Fin.Patterns`
  CHANGELOG.md
  src/Data/Fin/Base.agda
  src/Data/Fin/Patterns.agda
Labels: breaking, bug, status:ready

#965 Remove unnecessary uses of irrelevance
  CHANGELOG.md
  src/Data/Fin/Base.agda
  src/Data/Fin/Permutation/Components.agda
  src/Data/Fin/Properties.agda
  src/Data/Nat/DivMod.agda
Labels: breaking, library-design, status:ready

#961 Deprecate `Data.BoundedVec`
  CHANGELOG.md
  src/Data/BoundedVec.agda
  src/Data/BoundedVec/Inefficient.agda
Labels: deprecation, status:ready

#960 Give `Codata.Stream.tail` a more general type
  CHANGELOG.md
  src/Codata/Stream.agda
Labels: enhancement, status:ready

#972 Generalized type of `All-swap`
  CHANGELOG.md
  src/Data/List/Relation/Unary/All/Properties.agda
Labels: enhancement, status:ready

#963 Make levels explicit in `Data.Unit.Polymorphism.Properties`
  src/Data/Unit/Polymorphic/Properties.agda
Labels: enhancement, refactoring, status:ready

#962 Deprecate `Data.Table`
  CHANGELOG.md
  src/Data/Table.agda
  src/Data/Table/Base.agda
  src/Data/Table/Properties.agda
  src/Data/Table/Relation/Binary/Equality.agda
  src/Data/Table/Relation/Equality.agda
  src/Data/Vec/Functional.agda
  src/Data/Vec/Functional/Relation/Binary/Pointwise/Properties.agda
  src/Data/Vec/Functional/Relation/Unary/All.agda
  src/Data/Vec/Functional/Relation/Unary/All/Properties.agda
  src/Data/Vec/Functional/Relation/Unary/Any.agda
Labels: deprecation, enhancement, status:ready

#937 Algebraic properties of _+_ for normalised rationals
  CHANGELOG.md
  src/Algebra/Properties/CommutativeSemigroup.agda
  src/Data/Integer/DivMod.agda
  src/Data/Integer/GCD.agda
  src/Data/Nat/Coprimality.agda
  src/Data/Nat/DivMod.agda
  src/Data/Nat/DivMod/Core.agda
  src/Data/Nat/Divisibility.agda
  src/Data/Nat/GCD.agda
  src/Data/Nat/Properties.agda
  src/Data/Rational/Base.agda
  src/Data/Rational/Properties.agda
  src/Data/Rational/Unnormalised/Properties.agda
Labels: breaking, deprecation, enhancement, refactoring

#947 Rename `fromℕ≤` to `fromℕ<` in `Data.Fin`
  CHANGELOG.md
  src/Codata/Cofin.agda
  src/Data/Fin.agda
  src/Data/Fin/Base.agda
  src/Data/Fin/Properties.agda
  src/Data/Nat/Coprimality.agda
  src/Data/Nat/DivMod.agda
  src/Data/Nat/DivMod/WithK.agda
  src/Data/Vec/Properties.agda
Labels: deprecation, naming, refactoring, status:ready

#974 Reverted decidability procedures in `Data.Nat.Binary.Properties` to improve performance
  src/Data/Nat/Binary/Properties.agda
Labels: performance

#968 Redo Dec-related lemmas in the `Relation.Nullary` hierarchy
  CHANGELOG.md
  README/Dec.agda
  src/Relation/Nullary/Decidable/Core.agda
  src/Relation/Nullary/Implication.agda
  src/Relation/Nullary/Negation.agda
  src/Relation/Nullary/Product.agda
  src/Relation/Nullary/Reflects.agda
  src/Relation/Nullary/Sum.agda
Labels: refactoring, status:ready

#977 Removed module parameters from `Function`
  src/Function.agda
  src/Function/Construct/Composition.agda
  src/Function/Construct/Identity.agda
Labels: bug, library-design

#975 Improve pointers to README files and rename README.Dec
  README.agda
  README/Decidability.agda
  src/Data/AVL.agda
  src/Data/Integer.agda
  src/Data/Integer/Base.agda
  src/Data/List.agda
  src/Data/List/Base.agda
  src/Data/List/Fresh.agda
  src/Data/Nat.agda
  src/Data/Nat/Base.agda
  src/Data/Trie.agda
  src/Relation/Nullary.agda
  src/Relation/Unary.agda
Labels: documentation
