Repository agda/agda-stdlib, pull requests merged in 2019-06, with the labels that each got.

#789 the result of decision procedure is fixed once witnessed is provided
  CHANGELOG.md
  src/Axiom/UniquenessOfIdentityProofs.agda
  src/Data/List/Relation/Binary/Pointwise.agda
  src/Data/List/Relation/Unary/All.agda
  src/Data/Maybe/Relation/Unary/All.agda
  src/Data/Maybe/Relation/Unary/Any.agda
  src/Data/Nat/Properties.agda
  src/Data/Vec/Relation/Unary/All.agda
  src/Relation/Binary/Construct/Add/Extrema/Strict.agda
  src/Relation/Binary/Construct/Add/Infimum/NonStrict.agda
  src/Relation/Binary/Construct/Add/Infimum/Strict.agda
  src/Relation/Binary/Construct/Add/Point/Equality.agda
  src/Relation/Binary/Construct/Add/Supremum/NonStrict.agda
  src/Relation/Binary/Construct/Add/Supremum/Strict.agda
  src/Relation/Binary/HeterogeneousEquality.agda
  src/Relation/Binary/PropositionalEquality.agda
  src/Relation/Nullary.agda
  src/Relation/Nullary/Decidable/Core.agda
  src/Relation/Unary.agda
Labels: enhancement, status:ready

#792 Proofs about `_/_`
  CHANGELOG.md
  src/Data/Digit.agda
  src/Data/Nat/DivMod.agda
  src/Data/Nat/DivMod/Core.agda
  src/Data/Nat/Divisibility.agda
  src/Data/Nat/Divisibility/Core.agda
  src/Data/Nat/GCD.agda
  src/Data/Nat/LCM.agda
  src/Data/Nat/Properties.agda
Labels: breaking, bug, enhancement, status:ready

#664 [ fix #642 ] Fixed precedence levels of `Ring` operations
  CHANGELOG.md
  src/Algebra/Structures.agda
Labels: breaking, bug, status:ready

#788 Fix #591, adding argmax/min, max/min for lists
  CHANGELOG.md
  src/Algebra/Construct/LiftedChoice.agda
  src/Algebra/Construct/NaturalChoice/Max.agda
  src/Algebra/Construct/NaturalChoice/Min.agda
  src/Data/List/Extrema.agda
  src/Data/List/Extrema/Core.agda
  src/Data/List/Extrema/Nat.agda
Labels: enhancement, status:ready

#813 [ fix #758 ] Documenting OPTIONS conventions
  HACKING.md
Labels: admin, status:ready

#794 Extensionality for implicit function spaces
  CHANGELOG.md
  src/Axiom/Extensionality/Propositional.agda
  src/Function.agda
Labels: enhancement, status:ready

#784 create Relation.Binary.Construct.Closure.Reflexive.Properties
  CHANGELOG.md
  src/Relation/Binary/Construct/Closure/Reflexive/Properties.agda
  src/Relation/Binary/Construct/Closure/Reflexive/Properties/WithK.agda
Labels: enhancement, status:ready

#798 [ fix #767 ] Format strings and Printf
  CHANGELOG.md
  README.agda
  README/Text.agda
  src/Data/String/Base.agda
  src/Text/Format.agda
  src/Text/Printf.agda
Labels: enhancement, status:ready

#811 n-ary decidable equality transformer
  CHANGELOG.md
  src/Data/Product/Nary/NonDependent.agda
  src/Function/Nary/NonDependent.agda
  src/Function/Nary/NonDependent/Base.agda
  src/Relation/Binary/PropositionalEquality.agda
  src/Relation/Nary.agda
Labels: enhancement, refactoring, status:ready

#802 Added some constants to `Data.Fin.Base`
  CHANGELOG.md
  src/Data/Fin/Base.agda
Labels: enhancement, status:ready

#806 Add convenience lemma weaken-↑ to substitutions library
  CHANGELOG.md
  src/Data/Fin/Substitution/Lemmas.agda
Labels: enhancement, status:ready

#810 Name `Traversable` modules in `Data.X.Categorical`
  CHANGELOG.md
  src/Data/List/Categorical.agda
  src/Data/List/NonEmpty/Categorical.agda
  src/Data/Maybe/Categorical.agda
  src/Data/Product/Categorical/Left.agda
  src/Data/Product/Categorical/Right.agda
  src/Data/Sum/Categorical/Left.agda
  src/Data/Sum/Categorical/Right.agda
  src/Data/These/Categorical/Left.agda
  src/Data/These/Categorical/Right.agda
  src/Data/Vec/Categorical.agda
Labels: breaking, library-design, status:ready

#807 Fixes #445 and standardises names in the `Algebra.Properties` folder
  CHANGELOG.md
  src/Algebra/Properties/AbelianGroup.agda
  src/Algebra/Properties/BooleanAlgebra.agda
  src/Algebra/Properties/BooleanAlgebra/Expression.agda
  src/Algebra/Properties/CommutativeMonoid.agda
  src/Algebra/Properties/DistributiveLattice.agda
  src/Algebra/Properties/Group.agda
  src/Algebra/Properties/Lattice.agda
  src/Algebra/Properties/Ring.agda
  src/Algebra/Properties/Semilattice.agda
  src/Algebra/Structures.agda
  src/Data/Bool/Properties.agda
  src/Data/Fin/Subset/Properties.agda
  src/Data/Nat/Properties.agda
Labels: breaking, enhancement, refactoring, status:ready

#717 fromℕ≤ and inject≤ changes (Fin data type).
  CHANGELOG.md
  src/Data/Fin/Base.agda
  src/Data/Fin/Properties.agda
Labels: enhancement, status:ready

#790 [ new ] Data.Vec.Bounded for bounded vectors
  CHANGELOG.md
  src/Data/Nat/Properties.agda
  src/Data/Vec.agda
  src/Data/Vec/Base.agda
  src/Data/Vec/Bounded.agda
  src/Data/Vec/Bounded/Base.agda
Labels: enhancement, status:ready

#817 [ fix #814 ] fix inconsistent fixity of reasoning combinators
  CHANGELOG.md
  src/Relation/Binary/Reasoning/Base/Double.agda
  src/Relation/Binary/Reasoning/Base/Triple.agda
Labels: bug, status:ready

#823 [ cleanup ] Relation.Binary.PropositionalEquality
  src/Relation/Binary/PropositionalEquality.agda
Labels: bug

#822 Add `ε⁻¹≈ε` and cancellative properties to `Algebra.Properties.Group`
  CHANGELOG.md
  src/Algebra/Properties/Group.agda
  src/Algebra/Properties/Ring.agda
Labels: enhancement

#719 [ fix #718 ] Fix unsolved metas in propositional uniqueness
  src/Data/List/Relation/Binary/Sublist/Heterogeneous/Core.agda
  src/Data/List/Relation/Unary/AllPairs.agda
  src/Data/List/Relation/Unary/AllPairs/Core.agda
  src/Data/List/Relation/Unary/Unique/Setoid.agda
Labels: bug, library-design, status:ready

#820 Transfer across some proofs to `Permutation.Setoid` and deprecate `Permutation.Inductive`
  CHANGELOG.md
  src/Data/List/Relation/BagAndSetEquality.agda
  src/Data/List/Relation/Binary/Equality/DecPropositional.agda
  src/Data/List/Relation/Binary/Equality/DecSetoid.agda
  src/Data/List/Relation/Binary/Equality/Propositional.agda
  src/Data/List/Relation/Binary/Equality/Setoid.agda
  src/Data/List/Relation/Binary/Permutation/Homogeneous.agda
  src/Data/List/Relation/Binary/Permutation/Inductive.agda
  src/Data/List/Relation/Binary/Permutation/Inductive/Properties.agda
  src/Data/List/Relation/Binary/Permutation/Propositional.agda
  src/Data/List/Relation/Binary/Permutation/Propositional/Properties.agda
  src/Data/List/Relation/Binary/Permutation/Setoid.agda
  src/Data/List/Relation/Binary/Permutation/Setoid/Properties.agda
  src/Data/List/Relation/Binary/Pointwise.agda
Labels: deprecation, enhancement, refactoring, status:ready

#818 Refactor lcm
  CHANGELOG.md
  src/Data/Integer/DivMod.agda
  src/Data/Nat/Coprimality.agda
  src/Data/Nat/DivMod.agda
  src/Data/Nat/DivMod/WithK.agda
  src/Data/Nat/Divisibility.agda
  src/Data/Nat/GCD.agda
  src/Data/Nat/LCM.agda
Labels: breaking, deprecation, enhancement, refactoring, status:ready

#700 add `Maybe` type for Haskell interop
  CHANGELOG.md
  GenerateEverything.hs
  src/Foreign/Haskell.agda
  src/Foreign/Haskell/Maybe.agda
  src/Foreign/Haskell/Pair.agda
Labels: FFI, discussion, enhancement, library-design, status:ready

#824 [ new ] congAt : a = b -> f vs a ws = f vs b ws
  src/Function/Nary/NonDependent.agda
Labels: enhancement

#821 Fix #773 - make `*-suc` naming convention consistent
  CHANGELOG.md
  src/Data/Integer/DivMod.agda
  src/Data/Integer/Properties.agda
  src/Data/Nat/Properties.agda
Labels: deprecation, status:ready
