Repository agda/agda-stdlib, pull requests merged in 2019-12, with the labels that each got.

#984 Proper subset relations
  CHANGELOG.md
  src/Data/Bool/Properties.agda
  src/Data/Fin/Subset.agda
  src/Data/Fin/Subset/Induction.agda
  src/Data/Fin/Subset/Properties.agda
Labels: enhancement, status:ready

#982 Rewrite definitions that use Dec to be less strict
  CHANGELOG.md
  src/Algebra/Properties/CommutativeMonoid.agda
  src/Axiom/UniquenessOfIdentityProofs.agda
  src/Category/Monad/Partiality.agda
  src/Codata/Musical/Colist.agda
  src/Data/Bool/Properties.agda
  src/Data/Digit.agda
  src/Data/Fin/Permutation/Components.agda
  src/Data/Fin/Properties.agda
  src/Data/Graph/Acyclic.agda
  src/Data/List/Base.agda
  src/Data/List/Countdown.agda
  src/Data/List/Fresh.agda
  src/Data/List/Fresh/Relation/Unary/Any/Properties.agda
  src/Data/List/Membership/Propositional/Properties.agda
  src/Data/List/Membership/Setoid/Properties.agda
  src/Data/List/Properties.agda
  src/Data/List/Relation/Binary/Pointwise.agda
  src/Data/List/Relation/Binary/Prefix/Heterogeneous/Properties.agda
  src/Data/List/Relation/Binary/Sublist/Heterogeneous/Properties.agda
  src/Data/List/Relation/Binary/Subset/Setoid/Properties.agda
  src/Data/List/Relation/Binary/Suffix/Heterogeneous/Properties.agda
  src/Data/List/Relation/Ternary/Interleaving/Setoid/Properties.agda
  src/Data/List/Relation/Unary/All/Properties.agda
  src/Data/List/Relation/Unary/AllPairs/Properties.agda
  src/Data/List/Relation/Unary/Linked.agda
  src/Data/Maybe/Base.agda
  src/Data/Product/Properties/WithK.agda
  src/Data/Record.agda
  src/Data/Sum/Base.agda
  src/Data/Table.agda
  src/Data/Table/Properties.agda
  src/Data/Vec.agda
  src/Data/Vec/Base.agda
  src/Data/Vec/Properties.agda
  src/Function/Related/TypeIsomorphisms.agda
  src/Relation/Nary.agda
  src/Relation/Nullary/Decidable/Core.agda
  src/Relation/Unary.agda
Labels: performance, status:ready

#973 Added properties to `Algebra.Properties.Group`
  CHANGELOG.md
  src/Algebra/Properties/AbelianGroup.agda
  src/Algebra/Properties/Group.agda
  src/Algebra/Properties/Ring.agda
Labels: enhancement, refactoring, status:ready

#999 Cleanup binary
  src/Data/Nat/Binary/Properties.agda
Labels: refactoring, status:ready

#1013 Have authored enough bits to add myself to the author lists.
  LICENCE
  README.agda
Labels: admin

#996 Add basic properties of _*_ for normalised rationals
  CHANGELOG.md
  src/Data/Rational/Properties.agda
  src/Data/Rational/Unnormalised/Properties.agda
Labels: enhancement, status:ready

#991 Added fixpoint proof for well-founded induction
  CHANGELOG.md
  src/Induction/WellFounded.agda
Labels: enhancement, status:ready

#971 Make RawFunctor more Level polymorphic
  CHANGELOG.md
  src/Category/Applicative.agda
  src/Category/Applicative/Indexed.agda
  src/Category/Functor.agda
Labels: enhancement, status:ready

#1017 Relate < and ≤ (part of #1016)
  CHANGELOG.md
  CHANGELOG/v1.1.md
  src/Data/Integer/Properties.agda
Labels: enhancement, status:ready

#1007 Fix naming inconsistency in Data.List.Relation.Unary.Any.Properties
  CHANGELOG.md
  src/Data/List/Relation/Unary/All/Properties.agda
Labels: naming, status:ready

#1010 enumerated items import statements
  README/Data/Nat.agda
Labels: documentation, enhancement, status:ready

#1006 [ fix ] change definition of `Permutation.refl`
  CHANGELOG.md
  src/Data/List/Relation/Binary/Equality/Setoid.agda
  src/Data/List/Relation/Binary/Permutation/Homogeneous.agda
  src/Data/List/Relation/Binary/Permutation/Setoid.agda
  src/Data/List/Relation/Binary/Permutation/Setoid/Properties.agda
  src/Data/List/Relation/Binary/Pointwise.agda
  src/Relation/Binary/Properties/Setoid.agda
Labels: breaking, enhancement, refactoring, status:ready

#1032 added using directives to README.Data.List
  README/Data/List.agda
Labels: documentation, enhancement

#1023 [minor] checked punctuation, grammar, descriptive links
  README.md
Labels: documentation, status:ready

#1021 [ re #488 ] more properties for Colist
  CHANGELOG.md
  src/Codata/Colist.agda
  src/Codata/Colist/Bisimilarity.agda
  src/Codata/Colist/Properties.agda
  src/Codata/Conat.agda
  src/Codata/Conat/Bisimilarity.agda
  src/Codata/Conat/Properties.agda
  src/Codata/Cowriter/Bisimilarity.agda
  src/Codata/Stream/Bisimilarity.agda
  src/Codata/Stream/Properties.agda
  src/Data/List/NonEmpty.agda
  src/Data/Maybe/Properties.agda
Labels: enhancement, status:ready
