Repository agda/agda-stdlib, pull requests merged in 2019-02, with the labels that each got.

#586 [ fix #185 ] New style reasoning
  CHANGELOG.md
  src/Codata/Musical/Colist.agda
  src/Data/Integer/Properties.agda
  src/Data/Nat/Coprimality.agda
  src/Data/Nat/Properties.agda
  src/Relation/Binary/Reasoning/Base/Double.agda
  src/Relation/Binary/Reasoning/Base/Single.agda
  src/Relation/Binary/Reasoning/Base/Triple.agda
  src/Relation/Binary/Reasoning/MultiSetoid.agda
  src/Relation/Binary/Reasoning/PartialOrder.agda
  src/Relation/Binary/Reasoning/Preorder.agda
  src/Relation/Binary/Reasoning/Setoid.agda
  src/Relation/Binary/Reasoning/StrictPartialOrder.agda
Labels: enhancement, library-design, status:ready

#606 Fixed the missing argument of ⊆-Reasoning in the module Data.List.Rel…
  src/Data/List/Relation/Binary/Subset/Propositional/Properties.agda
Labels: bug

#596 Added some List tabulate-lookup properties.
  CHANGELOG.md
  src/Data/List/Base.agda
  src/Data/List/Properties.agda
Labels: enhancement, status:ready

#578 [ new ] add proofs of decidable propositional equality for various container datatypes
  CHANGELOG.md
  src/Data/List/Properties.agda
  src/Data/List/Relation/Binary/Pointwise.agda
  src/Data/Maybe/Properties.agda
  src/Data/Product/Properties.agda
  src/Data/Product/Properties/WithK.agda
  src/Data/Sum/Properties.agda
  src/Data/These/Properties.agda
  src/Data/Vec/Properties.agda
Labels: enhancement, status:ready

#605 [ fix #344 ] Symmetric reasoning combinators
  CHANGELOG.md
  src/Algebra/Properties/AbelianGroup.agda
  src/Algebra/Properties/BooleanAlgebra.agda
  src/Data/List/Relation/Binary/BagAndSetEquality.agda
  src/Data/List/Relation/Binary/Permutation/Inductive.agda
  src/Data/List/Relation/Binary/Permutation/Inductive/Properties.agda
  src/Data/List/Relation/Binary/Sublist/Propositional/Properties.agda
  src/Data/List/Relation/Binary/Subset/Propositional/Properties.agda
  src/Data/List/Relation/Binary/Subset/Setoid/Properties.agda
  src/Relation/Binary/Reasoning/Base/Double.agda
  src/Relation/Binary/Reasoning/Base/Single.agda
  src/Relation/Binary/Reasoning/Base/Triple.agda
  src/Relation/Binary/Reasoning/MultiSetoid.agda
  src/Relation/Binary/Reasoning/Setoid.agda
Labels: enhancement, status:ready

#600 [ fix #472 ] Updated binary relations for Data.Sum
  CHANGELOG.md
  src/Data/Sum/Relation/Binary/Core.agda
  src/Data/Sum/Relation/Binary/LeftOrder.agda
  src/Data/Sum/Relation/Binary/Pointwise.agda
  src/Data/Sum/Relation/Core.agda
  src/Relation/Binary/Sum.agda
  src/Relation/Nullary/Universe.agda
Labels: breaking, enhancement, library-design, status:not-ready-yet

#532 [ fix #457 ] Endomorphisms on a Setoid
  CHANGELOG.md
  src/Function/Endomorphism/Propositional.agda
  src/Function/Endomorphism/Setoid.agda
Labels: enhancement, status:ready

#583 [ fix #554 ] efficient comparisons on natural numbers
  CHANGELOG.md
  src/Algebra/Properties/CommutativeMonoid.agda
  src/Data/Bool/Properties.agda
  src/Data/Fin/Permutation/Components.agda
  src/Data/Nat/Base.agda
  src/Data/Nat/Properties.agda
  src/Relation/Binary/Core.agda
  src/Relation/Binary/PropositionalEquality.agda
Labels: enhancement, status:ready

#594 Add List decidable propositional equality
  CHANGELOG.md
  src/Data/List/Relation/Binary/Equality/DecPropositional.agda
Labels: enhancement, status:ready

#621 Moving proofs about `Injection`, `Surjection` etc. out of `Pointwise`
  CHANGELOG.md
  src/Codata/Musical/Colist/Infinite-merge.agda
  src/Data/Container/Any.agda
  src/Data/List/Membership/Propositional/Properties.agda
  src/Data/List/Relation/Binary/BagAndSetEquality.agda
  src/Data/List/Relation/Unary/Any/Properties.agda
  src/Data/Product/Function/Dependent/Propositional.agda
  src/Data/Product/Function/Dependent/Propositional/WithK.agda
  src/Data/Product/Function/Dependent/Setoid.agda
  src/Data/Product/Function/Dependent/Setoid/WithK.agda
  src/Data/Product/Function/NonDependent/Propositional.agda
  src/Data/Product/Function/NonDependent/Setoid.agda
  src/Data/Product/Relation/Binary/Pointwise/Dependent.agda
  src/Data/Product/Relation/Binary/Pointwise/Dependent/WithK.agda
  src/Data/Product/Relation/Binary/Pointwise/NonDependent.agda
  src/Data/Sum/Function/Propositional.agda
  src/Data/Sum/Function/Setoid.agda
  src/Data/Sum/Relation/Binary/Pointwise.agda
  src/Data/Vec/Relation/Unary/Any/Properties.agda
  src/Function/Related/TypeIsomorphisms.agda
Labels: breaking, library-design, refactoring, status:ready

#598 [ refactor ] more general version of _--_ et al.
  CHANGELOG.md
  src/Data/List/Membership/Setoid.agda
  src/Data/List/Relation/Unary/All/Properties.agda
  src/Data/List/Relation/Unary/Any.agda
Labels: breaking, refactoring, status:ready

#634 [ re #633 ] Split EverythingSafe in 2
  .gitignore
  GenerateEverything.hs
  src/Data/List/Relation/Binary/Suffix/Heterogeneous.agda
  src/Data/List/Relation/Binary/Suffix/Heterogeneous/Properties.agda
  src/Relation/Binary/Construct/Add/Extrema/Equality.agda
  src/Relation/Binary/Construct/Add/Extrema/NonStrict.agda
  src/Relation/Binary/Construct/Add/Extrema/Strict.agda
  src/Relation/Binary/Construct/Add/Infimum/Equality.agda
  src/Relation/Binary/Construct/Add/Infimum/NonStrict.agda
  src/Relation/Binary/Construct/Add/Infimum/Strict.agda
  src/Relation/Binary/Construct/Add/Point/Equality.agda
  src/Relation/Binary/Construct/Add/Supremum/Equality.agda
  src/Relation/Binary/Construct/Add/Supremum/NonStrict.agda
  src/Relation/Binary/Construct/Add/Supremum/Strict.agda
  src/Relation/Nullary/Construct/Add/Extrema.agda
  src/Relation/Nullary/Construct/Add/Infimum.agda
  src/Relation/Nullary/Construct/Add/Point.agda
  src/Relation/Nullary/Construct/Add/Supremum.agda
Labels: enhancement, status:ready, travis

#632 [ travis ] building on experimental too
  .travis.yml
  GenerateEverything.hs
  travis/safe.agda
Labels: agda-2.6.0, travis
