Repository agda/agda-stdlib, pull requests merged in 2019-07, with the labels that each got.

#783 Data.Bin II
  CHANGELOG.md
  src/Algebra/Properties/CommutativeSemigroup.agda
  src/Algebra/Properties/Semigroup.agda
  src/Data/Bin.agda
  src/Data/Bin/Base.agda
  src/Data/Bin/Properties.agda
  src/Data/Nat/Properties.agda
  src/Relation/Binary/Properties/Setoid.agda
Labels: breaking, enhancement, status:not-ready-yet

#829 add a function `levelOf`
  CHANGELOG.md
  src/Level.agda
Labels: enhancement

#795 Translations of algebraic properties via morphisms and left-inverses
  CHANGELOG.md
  src/Algebra.agda
  src/Algebra/Morphism.agda
  src/Algebra/Morphism/RawMagma.agda
  src/Algebra/Morphism/RawMonoid.agda
Labels: enhancement, status:ready

#838 Simplified proofs in `Data.Bin.Properties` using algebraic homomorphism proofs
  CHANGELOG.md
  src/Algebra.agda
  src/Algebra/Morphism/RawMagma.agda
  src/Algebra/Morphism/RawMonoid.agda
  src/Data/Bin/Properties.agda
  src/Data/Nat/Properties.agda
  src/Relation/Binary/PropositionalEquality.agda
  src/Relation/Binary/Reasoning/Base/Double.agda
  src/Relation/Binary/Reasoning/Base/Single.agda
  src/Relation/Binary/Reasoning/Base/Triple.agda
Labels: enhancement, refactoring, status:ready

#841 [ Sublist/Setoid ] use open instead of alias for ⊆-refl etc.
  src/Data/List/Relation/Binary/Sublist/Heterogeneous/Properties.agda
  src/Data/List/Relation/Binary/Sublist/Setoid.agda
Labels: refactoring, status:not-ready-yet

#848 [ Sublist.Propositional ] category laws, plus functor laws for All and Any
  src/Data/List/Relation/Binary/Sublist/Propositional/Properties.agda
Labels: enhancement

#843 Unnormalised rationals
  CHANGELOG.md
  src/Data/Integer/Base.agda
  src/Data/Rational/Unnormalised.agda
  src/Data/Rational/Unnormalised/Properties.agda
Labels: enhancement, library-design, status:ready
