Repository agda/agda-stdlib, pull requests merged in 2019-08, with the labels that each got.

#849 [ Sublist.Setoid ] RawPushout for merging two extensions of a list
  src/Data/List/Relation/Binary/Sublist/Propositional/Properties.agda
  src/Data/List/Relation/Binary/Sublist/Setoid.agda
Labels: enhancement

#854 [ Sublist.Setoid.Properties ] removed spurious module parameters
  src/Data/List/Relation/Binary/Sublist/Setoid/Properties.agda
Labels: bug

#852 Add Partial Equivalences, Partial Setoids, and Partial Reasoning
  CHANGELOG.md
  src/Relation/Binary.agda
  src/Relation/Binary/Core.agda
  src/Relation/Binary/Reasoning/Base/Partial.agda
  src/Relation/Binary/Reasoning/Base/Single.agda
  src/Relation/Binary/Reasoning/PartialSetoid.agda
  src/Relation/Binary/Reasoning/Setoid.agda
Labels: enhancement, library-design, status:ready
