Repository agda/agda-stdlib, pull requests merged in 2019-10, with the labels that each got.

#916 [ fix #903 ] Adding Foreign.Haskell.Either
  CHANGELOG.md
  GenerateEverything.hs
  src/Foreign/Haskell.agda
  src/Foreign/Haskell/Coerce.agda
  src/Foreign/Haskell/Either.agda
Labels: FFI, enhancement, status:ready

#913 [ new ] map for fresh lists
  src/Data/List/Fresh.agda
Labels: enhancement, status:ready

#919 [ #917 ] Do not deprecate ⌊_⌋, the traditional name of isYes.
  src/Relation/Nullary/Decidable/Core.agda
Labels: naming

#924 [ new ] bundles for orders on chars / strings
  CHANGELOG.md
  src/Data/Char/Properties.agda
  src/Data/String/Properties.agda
Labels: enhancement, status:ready

#926 Data.Empty.Polymorphic
  CHANGELOG.md
  src/Data/Empty/Polymorphic.agda
Labels: enhancement, status:ready

#941 [ fix ] lack of space between two patterns
  src/Reflection/Pattern.agda
Labels: bug, status:ready

#927 Add homomorphisms over binary relations
  CHANGELOG.md
  src/Data/Nat/Binary/Properties.agda
  src/Data/Nat/Properties.agda
  src/Relation/Binary/Morphism.agda
  src/Relation/Binary/Morphism/RawOrder.agda
  src/Relation/Binary/Morphism/RawRelation.agda
Labels: enhancement, refactoring, status:ready

#925 Add a Level-polymorphic version of Data.Unit
  CHANGELOG.md
  src/Data/Unit/Polymorphic.agda
  src/Data/Unit/Polymorphic/Base.agda
  src/Data/Unit/Polymorphic/Properties.agda
Labels: enhancement, status:ready

#950 Simplify ∸-+-assoc
  src/Data/Nat/Properties.agda
Labels: refactoring, status:ready

#945 Fix missing exports in `Relation.Binary.Structures`
  CHANGELOG.md
  src/Relation/Binary/Structures.agda
Labels: bug, status:ready

#936 Refactored Algebra hierarchy to the new standard format
  CHANGELOG.md
  src/Algebra.agda
  src/Algebra/Construct/LiftedChoice.agda
  src/Algebra/Construct/NaturalChoice/Max.agda
  src/Algebra/Construct/NaturalChoice/Min.agda
  src/Algebra/Core.agda
  src/Algebra/Definitions.agda
  src/Algebra/FunctionProperties.agda
  src/Algebra/FunctionProperties/Consequences.agda
  src/Algebra/FunctionProperties/Consequences/Core.agda
  src/Algebra/FunctionProperties/Consequences/Propositional.agda
  src/Algebra/FunctionProperties/Core.agda
  src/Algebra/Morphism.agda
  src/Algebra/Morphism/RawMagma.agda
  src/Algebra/Morphism/RawMonoid.agda
  src/Algebra/Packages.agda
  src/Algebra/Properties/BooleanAlgebra.agda
  src/Algebra/Properties/CommutativeMonoid.agda
  src/Algebra/Properties/CommutativeSemigroup.agda
  src/Algebra/Properties/DistributiveLattice.agda
  src/Algebra/Properties/Group.agda
  src/Algebra/Properties/Lattice.agda
  src/Algebra/Solver/Ring.agda
  src/Algebra/Structures.agda
  src/Data/Bool/Properties.agda
  src/Data/Fin/Permutation/Components.agda
  src/Data/Fin/Properties.agda
  src/Data/Fin/Subset.agda
  src/Data/Fin/Subset/Properties.agda
  src/Data/Integer/Properties.agda
  src/Data/List/Extrema/Core.agda
  src/Data/List/Kleene/Base.agda
  src/Data/List/Membership/Propositional/Properties.agda
  src/Data/List/Membership/Setoid/Properties.agda
  src/Data/List/Properties.agda
  src/Data/List/Relation/Binary/BagAndSetEquality.agda
  src/Data/List/Relation/Binary/Permutation/Propositional/Properties.agda
  src/Data/List/Relation/Binary/Permutation/Setoid/Properties.agda
  src/Data/Maybe/Properties.agda
  src/Data/Nat/Binary/Base.agda
  src/Data/Nat/Binary/Properties.agda
  src/Data/Nat/Properties.agda
  src/Data/Rational/Properties.agda
  src/Data/Rational/Unnormalised/Properties.agda
  src/Data/Sign/Properties.agda
  src/Data/Vec/Properties.agda
  src/Function/Endomorphism/Propositional.agda
  src/Function/Related/TypeIsomorphisms.agda
  src/Relation/Binary/Construct/NaturalOrder/Left.agda
  src/Relation/Binary/Construct/NaturalOrder/Right.agda
  src/Relation/Binary/Lattice.agda
  src/Relation/Binary/Properties/BoundedJoinSemilattice.agda
  src/Relation/Binary/Properties/BoundedLattice.agda
  src/Relation/Binary/Properties/BoundedMeetSemilattice.agda
  src/Relation/Binary/Properties/DistributiveLattice.agda
  src/Relation/Binary/Properties/HeytingAlgebra.agda
  src/Relation/Binary/Properties/JoinSemilattice.agda
  src/Relation/Binary/Properties/Lattice.agda
  src/Relation/Binary/Properties/MeetSemilattice.agda
Labels: library-design, refactoring, status:ready

#935 [ refactor ] change decision procedures to use more combinators
  CHANGELOG.md
  src/Codata/Conat/Properties.agda
  src/Data/Bin/Properties.agda
  src/Data/Fin/Properties.agda
  src/Data/Fin/Subset/Properties.agda
  src/Data/List/Fresh/Relation/Unary/Any.agda
  src/Data/List/Properties.agda
  src/Data/List/Relation/Binary/Lex/Core.agda
  src/Data/List/Relation/Binary/Pointwise.agda
  src/Data/List/Relation/Binary/Sublist/Heterogeneous/Properties.agda
  src/Data/List/Relation/Unary/All.agda
  src/Data/List/Relation/Unary/AllPairs.agda
  src/Data/List/Relation/Unary/Any.agda
  src/Data/Maybe/Properties.agda
  src/Data/Nat/GCD.agda
  src/Data/Nat/Properties.agda
  src/Data/Product/Properties/WithK.agda
  src/Data/Rational/Properties.agda
  src/Data/Sum/Properties.agda
  src/Data/These/Properties.agda
  src/Data/Vec/Properties.agda
  src/Data/Vec/Relation/Binary/Pointwise/Inductive.agda
  src/Data/Vec/Relation/Unary/All.agda
  src/Data/Vec/Relation/Unary/Any.agda
  src/Data/Word/Unsafe.agda
  src/Relation/Binary/Consequences.agda
  src/Relation/Binary/Construct/Closure/Reflexive/Properties.agda
  src/Relation/Binary/Construct/Intersection.agda
  src/Relation/Binary/Construct/NonStrictToStrict.agda
  src/Relation/Binary/Construct/StrictToNonStrict.agda
  src/Relation/Binary/Construct/Union.agda
  src/Relation/Nullary/Decidable.agda
  src/Relation/Nullary/Decidable/Core.agda
Labels: refactoring, status:ready

#949 Use polymorphic Unit/Empty to remove two uses of Lift
  src/Relation/Binary/Construct/Always.agda
  src/Relation/Binary/Construct/Never.agda
Labels: refactoring, status:ready

#953 Rename "package" to "bundle"
  CHANGELOG.md
  src/Algebra.agda
  src/Algebra/Bundles.agda
  src/Algebra/Construct/NaturalChoice/Min.agda
  src/Algebra/Morphism/RawMagma.agda
  src/Algebra/Morphism/RawMonoid.agda
  src/Algebra/Properties/BooleanAlgebra.agda
  src/Algebra/Properties/CommutativeMonoid.agda
  src/Algebra/Properties/DistributiveLattice.agda
  src/Algebra/Properties/Group.agda
  src/Algebra/Properties/Lattice.agda
  src/Algebra/Solver/Ring.agda
  src/Data/Bool/Properties.agda
  src/Data/Fin/Subset/Properties.agda
  src/Data/Integer/Properties.agda
  src/Data/List/Properties.agda
  src/Data/List/Relation/Binary/Permutation/Propositional/Properties.agda
  src/Data/List/Relation/Binary/Permutation/Setoid/Properties.agda
  src/Data/Maybe/Properties.agda
  src/Data/Nat/Binary/Properties.agda
  src/Data/Nat/Properties.agda
  src/Data/Product/Relation/Binary/Lex/NonStrict.agda
  src/Data/Product/Relation/Binary/Lex/Strict.agda
  src/Data/Product/Relation/Binary/Pointwise/NonDependent.agda
  src/Data/Rational/Properties.agda
  src/Data/Rational/Unnormalised/Properties.agda
  src/Data/Sign/Properties.agda
  src/Data/Sum/Relation/Binary/LeftOrder.agda
  src/Data/Sum/Relation/Binary/Pointwise.agda
  src/Data/Unit/Properties.agda
  src/Data/Vec/Relation/Binary/Pointwise/Inductive.agda
  src/Function.agda
  src/Function/Bundles.agda
  src/Function/Construct/Composition.agda
  src/Function/Construct/Identity.agda
  src/Function/Definitions/Core1.agda
  src/Function/Definitions/Core2.agda
  src/Relation/Binary.agda
  src/Relation/Binary/Bundles.agda
  src/Relation/Binary/Construct/NaturalOrder/Left.agda
  src/Relation/Binary/Construct/NaturalOrder/Right.agda
  src/Relation/Binary/Indexed/Heterogeneous.agda
  src/Relation/Binary/Indexed/Heterogeneous/Bundles.agda
  src/Relation/Binary/Indexed/Heterogeneous/Construct/At.agda
  src/Relation/Binary/Indexed/Heterogeneous/Construct/Trivial.agda
  src/Relation/Binary/Indexed/Homogeneous.agda
  src/Relation/Binary/Indexed/Homogeneous/Bundles.agda
  src/Relation/Binary/Indexed/Homogeneous/Core.agda
  src/Relation/Binary/PropositionalEquality.agda
Labels: naming, refactoring, status:ready

#956 Deprecate LEQ in Data.Unit, and remove it from Data.Unit.Polymorphic.
  CHANGELOG.md
  src/Data/Unit.agda
  src/Data/Unit/Base.agda
  src/Data/Unit/Polymorphic.agda
  src/Data/Unit/Polymorphic/Base.agda
  src/Data/Unit/Polymorphic/Properties.agda
  src/Data/Unit/Properties.agda
Labels: deprecation, refactoring, status:ready

#954 Add `CommutativeSemigroup`
  CHANGELOG.md
  src/Algebra/Bundles.agda
  src/Algebra/Properties/CommutativeSemigroup.agda
  src/Algebra/Structures.agda
  src/Data/Integer/Properties.agda
  src/Data/Nat/Binary/Properties.agda
  src/Data/Nat/Properties.agda
  src/Data/Rational/Unnormalised/Properties.agda
Labels: enhancement, status:ready

#955 Added more filter lemmas
  CHANGELOG.md
  src/Data/List/Properties.agda
Labels: enhancement, status:ready

#932 Add `Reflects` and define `Dec` in terms of it
  CHANGELOG.md
  src/Data/Bool/Base.agda
  src/Relation/Nullary.agda
  src/Relation/Nullary/Reflects.agda
Labels: enhancement, performance, refactoring, status:ready

#958 Tidy up and expand morphism hierarchies
  CHANGELOG.md
  src/Algebra/Morphism.agda
  src/Algebra/Morphism/Definitions.agda
  src/Algebra/Morphism/MagmaMonomorphism.agda
  src/Algebra/Morphism/MonoidMonomorphism.agda
  src/Algebra/Morphism/RawMagma.agda
  src/Algebra/Morphism/RawMonoid.agda
  src/Algebra/Morphism/Structures.agda
  src/Algebra/Solver/Ring/AlmostCommutativeRing.agda
  src/Data/Nat/Binary/Properties.agda
  src/Data/Nat/Properties.agda
  src/Relation/Binary/Morphism.agda
  src/Relation/Binary/Morphism/Definitions.agda
  src/Relation/Binary/Morphism/OrderMonomorphism.agda
  src/Relation/Binary/Morphism/RelMonomorphism.agda
  src/Relation/Binary/Morphism/Structures.agda
Labels: enhancement, library-design, refactoring, status:ready

#909 Add `Linked` predicate over lists
  CHANGELOG.md
  src/Data/List/Relation/Unary/Linked.agda
  src/Data/List/Relation/Unary/Linked/Properties.agda
Labels: enhancement, naming, status:ready
