Repository agda/agda-stdlib, pull requests merged in 2019-04, with the labels that each got.

#681 [ bug ] Fixed two bugs in `Rational`
  CHANGELOG.md
  src/Data/Rational.agda
  src/Data/Rational/Base.agda
  src/Data/Rational/Properties.agda
Labels: bug, status:ready

#684 [ fix #683 ] re-export specialised versions of the constructors
  CHANGELOG.md
  src/Data/List/Relation/Binary/Sublist/DecPropositional.agda
  src/Data/List/Relation/Binary/Sublist/DecPropositional/Properties.agda
  src/Data/List/Relation/Binary/Sublist/DecSetoid.agda
  src/Data/List/Relation/Binary/Sublist/DecSetoid/Properties.agda
  src/Data/List/Relation/Binary/Sublist/DecSetoid/Solver.agda
  src/Data/List/Relation/Binary/Sublist/Heterogeneous.agda
  src/Data/List/Relation/Binary/Sublist/Heterogeneous/Core.agda
  src/Data/List/Relation/Binary/Sublist/Heterogeneous/Properties.agda
  src/Data/List/Relation/Binary/Sublist/Heterogeneous/Solver.agda
  src/Data/List/Relation/Binary/Sublist/Homogeneous/Properties.agda
  src/Data/List/Relation/Binary/Sublist/Propositional.agda
  src/Data/List/Relation/Binary/Sublist/Propositional/Properties.agda
  src/Data/List/Relation/Binary/Sublist/Setoid.agda
  src/Data/List/Relation/Binary/Sublist/Setoid/Properties.agda
Labels: bug, regression, status:ready

#614 [ doc ] expanding README.Case
  README/Case.agda
Labels: documentation, status:ready

#680 [ re #595] Added documentation for `List`
  README.agda
  README/List.agda
Labels: documentation, enhancement

#672 [ fix #467 #147 ] Added the Disjoint, AllPairs and Unique relations for List
  CHANGELOG.md
  src/Data/List/Relation/Binary/Disjoint/Propositional.agda
  src/Data/List/Relation/Binary/Disjoint/Setoid.agda
  src/Data/List/Relation/Binary/Disjoint/Setoid/Properties.agda
  src/Data/List/Relation/Unary/All/Properties.agda
  src/Data/List/Relation/Unary/AllPairs.agda
  src/Data/List/Relation/Unary/AllPairs/Properties.agda
  src/Data/List/Relation/Unary/Unique/Propositional.agda
  src/Data/List/Relation/Unary/Unique/Propositional/Properties.agda
  src/Data/List/Relation/Unary/Unique/Setoid.agda
  src/Data/List/Relation/Unary/Unique/Setoid/Properties.agda
Labels: enhancement, status:ready

#703 [ travis ] fix build
  .travis.yml
Labels: travis

#687 [ re #678 ] Add faster implementation of `show` for naturals
  CHANGELOG.md
  src/Data/Digit.agda
  src/Data/Nat/DivMod.agda
  src/Data/Nat/Properties.agda
  src/Data/Nat/Show.agda
  src/Relation/Binary/PropositionalEquality/Core.agda
Labels: enhancement, status:ready

#701 [ refactor ] Experimenting with variables in `Data.List`
  src/Data/List/Base.agda
  src/Data/List/Properties.agda
Labels: agda-2.6.0, library-design, refactoring

#691 Implement Reader monad (transformer)
  CHANGELOG.md
  src/Category/Monad/Reader.agda
Labels: enhancement, status:ready

#716 [ new ] concat⁺ for the sublist relation
  CHANGELOG.md
  src/Data/List/Relation/Binary/Sublist/Heterogeneous/Properties.agda
Labels: enhancement, status:ready

#708 [ refactor ] Removed trivial cases
  src/Algebra/Properties/CommutativeMonoid.agda
  src/Algebra/Solver/Ring.agda
  src/Category/Monad/Partiality.agda
  src/Codata/Musical/Cofin.agda
  src/Codata/Musical/Colist.agda
  src/Codata/Musical/Colist/Infinite-merge.agda
  src/Codata/Musical/Conat.agda
  src/Data/Bin.agda
  src/Data/Bool/Properties.agda
  src/Data/Fin/Base.agda
  src/Data/Fin/Permutation/Components.agda
  src/Data/Fin/Properties.agda
  src/Data/Fin/Subset/Properties.agda
  src/Data/Graph/Acyclic.agda
  src/Data/Integer/Properties.agda
  src/Data/List/Membership/Propositional/Properties.agda
  src/Data/List/Membership/Setoid/Properties.agda
  src/Data/List/Properties.agda
  src/Data/List/Relation/Binary/BagAndSetEquality.agda
  src/Data/List/Relation/Binary/Disjoint/Setoid/Properties.agda
  src/Data/List/Relation/Binary/Lex/Core.agda
  src/Data/List/Relation/Binary/Lex/Strict.agda
  src/Data/List/Relation/Binary/Pointwise.agda
  src/Data/List/Relation/Binary/Prefix/Heterogeneous/Properties.agda
  src/Data/List/Relation/Binary/Sublist/Heterogeneous.agda
  src/Data/List/Relation/Binary/Sublist/Heterogeneous/Properties.agda
  src/Data/List/Relation/Binary/Sublist/Propositional/Properties.agda
  src/Data/List/Relation/Binary/Subset/Propositional/Properties.agda
  src/Data/List/Relation/Binary/Subset/Setoid/Properties.agda
  src/Data/List/Relation/Ternary/Interleaving/Properties.agda
  src/Data/List/Relation/Unary/All.agda
  src/Data/List/Relation/Unary/All/Properties.agda
  src/Data/List/Relation/Unary/Any/Properties.agda
  src/Data/List/Relation/Unary/First/Properties.agda
  src/Data/Maybe.agda
  src/Data/Nat/Coprimality.agda
  src/Data/Nat/Divisibility.agda
  src/Data/Nat/Properties.agda
  src/Data/Sign/Properties.agda
  src/Data/Star/Pointer.agda
  src/Data/Sum/Function/Setoid.agda
  src/Data/Sum/Relation/Binary/LeftOrder.agda
  src/Data/Table/Properties.agda
  src/Data/Vec.agda
  src/Data/Vec/Membership/Propositional/Properties.agda
  src/Data/Vec/Properties.agda
  src/Data/Vec/Relation/Unary/All.agda
  src/Data/Vec/Relation/Unary/Any/Properties.agda
  src/Induction/Nat.agda
  src/Record.agda
  src/Relation/Binary/Construct/Add/Infimum/Strict.agda
  src/Relation/Binary/Construct/Add/Supremum/Strict.agda
  src/Relation/Nullary/Decidable.agda
Labels: agda-2.6.0, refactoring, status:ready

#647 [ Fix #646 ] Generalize Heterogeneous Equality.
  src/Relation/Binary/HeterogeneousEquality.agda
  src/Relation/Binary/HeterogeneousEquality/Core.agda
Labels: library-design, status:ready

#699 deprecate `Foreign.Haskell.Unit`
  src/Foreign/Haskell.agda
Labels: deprecation, status:ready

#720 [ #715 ] Fixed the bug in `Reasoning.MultiSetoid` reasoning by reimplementing it.
  src/Relation/Binary/Reasoning/MultiSetoid.agda
Labels: bug, regression

#711 [ refactor ] Make comparisons over Nat more efficient
  CHANGELOG.md
  src/Data/Nat/Properties.agda
Labels: refactoring, status:ready

#447 [ new ] Data.Trie(.NonEmpty)
  CHANGELOG.md
  README.agda
  README/Trie/NonDependent.agda
  src/Data/AVL/Height.agda
  src/Data/AVL/Indexed.agda
  src/Data/AVL/NonEmpty.agda
  src/Data/AVL/NonEmpty/Propositional.agda
  src/Data/List/Base.agda
  src/Data/Maybe.agda
  src/Data/Maybe/Base.agda
  src/Data/These.agda
  src/Data/These/Base.agda
  src/Data/Trie.agda
  src/Data/Trie/NonEmpty.agda
Labels: enhancement, status:ready

#638 [ re #488 ] properties of Stream's map, repeat, and cycle
  CHANGELOG.md
  src/Codata/Stream/Bisimilarity.agda
  src/Codata/Stream/Properties.agda
  src/Data/List/NonEmpty.agda
  src/Data/List/Relation/Binary/Equality/Propositional.agda
Labels: enhancement, status:ready

#710 [ fix #627 #698 ] Fix and Improve Reflection
  CHANGELOG.md
  src/Reflection.agda
Labels: bug, deprecation, discussion, enhancement, status:ready

#704 [ fix #408 ] WARNING_ON_IMPORT to deprecate modules
  GenerateEverything.hs
  src/Algebra/Properties/Semilattice.agda
  src/Data/Fin/Dec.agda
  src/Data/List/All.agda
  src/Data/List/All/Properties.agda
  src/Data/List/Any.agda
  src/Data/List/Any/Properties.agda
  src/Data/List/Relation/BagAndSetEquality.agda
  src/Data/List/Relation/Binary/Subset/Propositional/Properties.agda
  src/Data/List/Relation/Equality/DecPropositional.agda
  src/Data/List/Relation/Equality/DecSetoid.agda
  src/Data/List/Relation/Equality/Propositional.agda
  src/Data/List/Relation/Equality/Setoid.agda
  src/Data/List/Relation/Lex/Core.agda
  src/Data/List/Relation/Lex/NonStrict.agda
  src/Data/List/Relation/Lex/Strict.agda
  src/Data/List/Relation/Permutation/Inductive.agda
  src/Data/List/Relation/Permutation/Inductive/Properties.agda
  src/Data/List/Relation/Pointwise.agda
  src/Data/List/Relation/Sublist/Propositional.agda
  src/Data/List/Relation/Sublist/Propositional/Properties.agda
  src/Data/List/Relation/Subset/Propositional.agda
  src/Data/List/Relation/Subset/Propositional/Properties.agda
  src/Data/List/Relation/Subset/Setoid.agda
  src/Data/List/Relation/Subset/Setoid/Properties.agda
  src/Data/Plus.agda
  src/Data/Product/Relation/Lex/NonStrict.agda
  src/Data/Product/Relation/Lex/Strict.agda
  src/Data/Product/Relation/Pointwise/Dependent.agda
  src/Data/Product/Relation/Pointwise/NonDependent.agda
  src/Data/ReflexiveClosure.agda
  src/Data/Star.agda
  src/Data/Star/Properties.agda
  src/Data/Sum/Relation/LeftOrder.agda
  src/Data/Sum/Relation/Pointwise.agda
  src/Data/Table/Relation/Equality.agda
  src/Data/Vec/All.agda
  src/Data/Vec/All/Properties.agda
  src/Data/Vec/Any.agda
  src/Data/Vec/Relation/Equality/DecPropositional.agda
  src/Data/Vec/Relation/Equality/DecSetoid.agda
  src/Data/Vec/Relation/Equality/Propositional.agda
  src/Data/Vec/Relation/Equality/Setoid.agda
  src/Data/Vec/Relation/Pointwise/Extensional.agda
  src/Data/Vec/Relation/Pointwise/Inductive.agda
  src/Data/Word/Unsafe.agda
  src/Induction/WellFounded.agda
  src/Relation/Binary/EqReasoning.agda
  src/Relation/Binary/EquivalenceClosure.agda
  src/Relation/Binary/PartialOrderReasoning.agda
  src/Relation/Binary/PreorderReasoning.agda
  src/Relation/Binary/SetoidReasoning.agda
  src/Relation/Binary/StrictPartialOrderReasoning.agda
  src/Relation/Binary/SymmetricClosure.agda
Labels: agda-2.6.1, deprecation, status:ready

#648 [ #643 ] Add rewriting theory concepts to standard library
  CHANGELOG.md
  src/Relation/Binary/Construct/Closure/Equivalence/Properties.agda
  src/Relation/Binary/Rewriting.agda
Labels: enhancement, status:ready

#721 [ documentation ] Added documentation for the `Data` folder
  README.agda
  README/Data.agda
  README/Data/AVL.agda
  README/Data/Container/FreeMonad.agda
  README/Data/Container/Indexed.agda
  README/Data/Integer.agda
  README/Data/Interleaving.agda
  README/Data/List.agda
  README/Data/Nat.agda
  README/Data/Trie/NonDependent.agda
Labels: documentation, status:ready

#722 [ refactor ] Standardise how relational structures are treated in `Data` modules
  CHANGELOG.md
  src/Data/Bool.agda
  src/Data/Bool/Properties.agda
  src/Data/Integer/Properties.agda
  src/Data/Rational/Properties.agda
  src/Data/Sign.agda
  src/Data/Sign/Base.agda
  src/Data/Sign/Properties.agda
  src/Data/Unit.agda
  src/Data/Unit/Base.agda
  src/Data/Unit/Properties.agda
Labels: deprecation, library-design, refactoring, status:ready
