Repository agda/agda-stdlib, pull requests merged in 2019-05, with the labels that each got.

#723 [ new ] Added symmetric pattern constructors to `Data.Integer`
  CHANGELOG.md
  src/Data/Integer/Base.agda
  src/Data/Integer/Properties.agda
  src/Data/Rational/Base.agda
Labels: enhancement, status:ready

#702 [ new ] proofs that various orders are connex
  CHANGELOG.md
  src/Data/Nat/Properties.agda
  src/Relation/Binary/Consequences.agda
  src/Relation/Binary/Core.agda
Labels: enhancement, status:ready

#727 [ fix #724 ] rename setoid and order results
  CHANGELOG.md
  README/Data/List.agda
  README/Data/Trie/NonDependent.agda
  src/Data/Char.agda
  src/Data/Char/Base.agda
  src/Data/Char/Properties.agda
  src/Data/String.agda
  src/Data/String/Base.agda
  src/Data/String/Properties.agda
Labels: refactoring, status: low-hanging-fruit, status:ready, task

#731 Word prop: Define the induced relations, prove some of their properties
  CHANGELOG.md
  src/Data/Word.agda
  src/Data/Word/Base.agda
  src/Data/Word/Properties.agda
Labels: agda-2.6.1, enhancement, status:ready

#712 [ refactor ] Added some documentation + Refl + Universal to Relation.Binary.Core
  CHANGELOG.md
  src/Relation/Binary/Construct/Always.agda
  src/Relation/Binary/Construct/Closure/Reflexive.agda
  src/Relation/Binary/Core.agda
  src/Relation/Unary/Properties.agda
Labels: documentation, enhancement, question, refactoring, status:ready

#750 [ hacking ] documenting git pre-commit hooks
  HACKING.md
Labels: admin, documentation

#739 Remove GHC-7.10 support and bump minimum dependencies
  .travis.yml
  lib.cabal
Labels: agda-2.6.1, status:ready

#732 _-resp-⊆
  CHANGELOG.md
  src/Data/List/Relation/Binary/Sublist/Propositional/Properties.agda
Labels: enhancement, status:ready

#738 [ fix #730 ] Renamed (from/to)Nat to (from/to)ℕ
  CHANGELOG.md
  README/Data/List.agda
  src/Data/Char/Base.agda
  src/Data/Char/Properties.agda
  src/Data/Nat/Show.agda
Labels: deprecation, status:ready

#754 [ close #416 ] Adding RTS options
  .travis.yml
  GNUmakefile
Labels: enhancement, status:ready, test, travis

#745 Standardised names in Data.Nat.Properties
  CHANGELOG.md
  README/Inspect.agda
  notes/style-guide.md
  src/Data/Bin/Properties.agda
  src/Data/Fin/Properties.agda
  src/Data/Integer/Divisibility.agda
  src/Data/Integer/Divisibility/Signed.agda
  src/Data/List/Relation/Binary/Suffix/Heterogeneous/Properties.agda
  src/Data/Nat/Coprimality.agda
  src/Data/Nat/Divisibility.agda
  src/Data/Nat/GCD/Lemmas.agda
  src/Data/Nat/Properties.agda
Labels: deprecation, refactoring, status:ready

#753 [ new ] syntax for satisfiable
  CHANGELOG.md
  src/Relation/Unary.agda
Labels: enhancement, status:ready

#749 Nat div refactor
  CHANGELOG.md
  src/Data/Digit.agda
  src/Data/Integer/DivMod.agda
  src/Data/Integer/Divisibility.agda
  src/Data/Nat/DivMod.agda
  src/Data/Nat/DivMod/Core.agda
  src/Data/Nat/DivMod/WithK.agda
  src/Data/Nat/Divisibility.agda
  src/Data/Nat/LCM.agda
Labels: deprecation, enhancement, refactoring, status:ready

#740 [ fix #736 ] Added propositional equality lemmas to `Relation.Binary.Construct.Add...`
  CHANGELOG.md
  src/Relation/Binary/Construct/Add/Extrema/NonStrict.agda
  src/Relation/Binary/Construct/Add/Extrema/Strict.agda
  src/Relation/Binary/Construct/Add/Infimum/NonStrict.agda
  src/Relation/Binary/Construct/Add/Infimum/Strict.agda
  src/Relation/Binary/Construct/Add/Supremum/NonStrict.agda
  src/Relation/Binary/Construct/Add/Supremum/Strict.agda
  src/Relation/Nullary/Construct/Add/Infimum.agda
  src/Relation/Nullary/Construct/Add/Point.agda
Labels: enhancement, status:ready

#734 Added basic relations to `Data.Bool`
  CHANGELOG.md
  README/Function/Reasoning.agda
  src/Data/Bool.agda
  src/Data/Bool/Base.agda
  src/Data/Bool/Properties.agda
  src/Data/List/Relation/Unary/All/Properties.agda
  src/Data/Nat/DivMod/Core.agda
  src/Data/String/Properties.agda
Labels: enhancement, status:ready

#741 Replace Induction.Nat with Data.Nat/Fin.Induction
  CHANGELOG.md
  README/Data.agda
  README/Data/Nat/Induction.agda
  src/Codata/Musical/Colist/Infinite-merge.agda
  src/Data/Digit.agda
  src/Data/Fin/Induction.agda
  src/Data/Graph/Acyclic.agda
  src/Data/Nat/GCD.agda
  src/Data/Nat/Induction.agda
  src/Induction/Lexicographic.agda
  src/Induction/Nat.agda
Labels: deprecation, library-design, status:ready

#737 Added List permutation relation for setoid equalities
  CHANGELOG.md
  src/Data/List/Relation/Binary/Permutation/Homogeneous.agda
  src/Data/List/Relation/Binary/Permutation/Setoid.agda
Labels: enhancement, status:ready

#709 [ new ] Added some extra properties of folds
  CHANGELOG.md
  src/Data/List/Properties.agda
Labels: enhancement, question, status:ready

#662 [ new ] combinators for List's All
  CHANGELOG.md
  src/Data/List/Relation/Unary/All.agda
Labels: enhancement, status:ready

#762 Recomputable
  CHANGELOG.md
  src/Relation/Binary/Consequences.agda
  src/Relation/Binary/Core.agda
  src/Relation/Unary.agda
  src/Relation/Unary/Consequences.agda
Labels: discussion, enhancement, status:ready

#761 Permutation.shifts : xs ++ ys ++ zs ↭ ys ++ xs ++ zs
  CHANGELOG.md
  src/Data/List/Relation/Binary/Permutation/Inductive/Properties.agda
Labels: enhancement, status:ready

#760 Define some more utilities of unary list relations
  CHANGELOG.md
  src/Data/List/Relation/Unary/All.agda
  src/Data/List/Relation/Unary/Any/Properties.agda
Labels: enhancement, status:ready

#763 ,-injectiveʳ and ≡-dec for non-dependent product
  CHANGELOG.md
  src/Data/Product/Properties.agda
  src/Data/Product/Properties/WithK.agda
  src/Data/Product/Relation/Binary/Pointwise/NonDependent.agda
Labels: deprecation, enhancement, status:ready

#768 Moved Record/Universe to Data folder
  CHANGELOG.md
  README.agda
  README/Data.agda
  README/Data/Record.agda
  src/Data/Record.agda
  src/Data/Universe.agda
  src/Data/Universe/Indexed.agda
  src/Record.agda
  src/Universe.agda
Labels: deprecation, library-design, status:ready

#780 Export Setω in Level
  CHANGELOG.md
  src/Level.agda
Labels: enhancement

#769 BoundedLattice is an alias for IdempotentCommutativeMonoid
  CHANGELOG.md
  src/Algebra.agda
  src/Algebra/Structures.agda
Labels: enhancement, status:ready

#785 [ new ] use generalised variable
  src/Reflection.agda
Labels: enhancement, status:ready

#771 Deprecated _+'_ in `Data.Fin.Properties`
  CHANGELOG.md
  src/Data/Bin.agda
  src/Data/Fin/Properties.agda
  src/Data/Nat/Properties.agda
  src/Data/Vec/Properties.agda
Labels: deprecation, status:ready

#779 Added strict ordering to Rational
  CHANGELOG.md
  src/Data/Integer.agda
  src/Data/Integer/Base.agda
  src/Data/Integer/Properties.agda
  src/Data/Nat/Properties.agda
  src/Data/Rational.agda
  src/Data/Rational/Base.agda
  src/Data/Rational/Properties.agda
Labels: enhancement, status:ready

#776 Lifted choice
  CHANGELOG.md
  src/Algebra.agda
  src/Algebra/Construct/LiftedChoice.agda
  src/Algebra/Structures.agda
Labels: enhancement, status:ready

#772 Update installation instructions to download the .tar file
  notes/installation-guide.md
Labels: documentation, question, status:not-ready-yet

#770 New, efficient GCD implementation
  CHANGELOG.md
  src/Data/Nat/Coprimality.agda
  src/Data/Nat/GCD.agda
  src/Data/Nat/LCM.agda
  src/Data/Rational/Base.agda
Labels: breaking, performance, question, status:ready

#791 [ style ] multiple reasoning toolkit used in the same file
  notes/style-guide.md
Labels: admin, status:ready

#766 [ fix #729 ] List membership irrelevance
  CHANGELOG.md
  src/Data/List/Membership/Propositional/Properties/WithK.agda
  src/Data/List/Membership/Setoid/Properties.agda
  src/Data/List/Relation/Unary/All.agda
  src/Data/List/Relation/Unary/Unique/Setoid/Properties.agda
  src/Relation/Binary.agda
Labels: enhancement, status:ready

#608 [ fix #577 ] generic n-ary functions and products
  CHANGELOG.md
  README.agda
  README/Nary.agda
  src/Data/Fin.agda
  src/Data/Fin/Base.agda
  src/Data/Nat/Base.agda
  src/Data/Product/N-ary.agda
  src/Data/Product/N-ary/Categorical.agda
  src/Data/Product/N-ary/Properties.agda
  src/Data/Product/Nary/NonDependent.agda
  src/Data/Unit.agda
  src/Data/Vec/Recursive.agda
  src/Data/Vec/Recursive/Categorical.agda
  src/Data/Vec/Recursive/Properties.agda
  src/Function/Nary/NonDependent.agda
  src/Relation/Binary/PropositionalEquality.agda
  src/Relation/Nary.agda
  src/Relation/Nullary/Decidable.agda
  src/Relation/Nullary/Decidable/Core.agda
Labels: documentation, enhancement, status:ready
