Repository agda/agda-stdlib, pull requests merged in 2020-04, with the labels that each got.

#1111 Proved that both [,] and map respect function equality in Data.Sum.Properties
  CHANGELOG.md
  src/Data/Fin/Properties.agda
  src/Data/List/Relation/Binary/BagAndSetEquality.agda
  src/Data/Sum/Properties.agda
Labels: enhancement, status: blocked-by-issue, status:ready

#1129 add symmetric reflexive closures for relations
  CHANGELOG.md
  src/Relation/Binary/Construct/Closure/SymmetricTransitive.agda
Labels: enhancement, status:ready

#1096 Add `Instances` modules for exposing instances to instance search
  .travis.yml
  CHANGELOG.md
  src/Category/Monad/Partiality/Instances.agda
  src/Codata/Covec/Instances.agda
  src/Codata/Stream/Instances.agda
  src/Data/List/Instances.agda
  src/Data/List/NonEmpty/Instances.agda
  src/Data/Maybe/Instances.agda
  src/Data/Vec/Instances.agda
  src/Function/Identity/Instances.agda
Labels: instances, library-design, status:ready

#1125 Tree zippers attempt 2
  CHANGELOG/v1.4.md
  src/Data/Tree/Binary.agda
  src/Data/Tree/Binary/Properties.agda
  src/Data/Tree/Binary/Relation/Unary/All.agda
  src/Data/Tree/Binary/Relation/Unary/All/Properties.agda
  src/Data/Tree/Binary/Zipper.agda
  src/Data/Tree/Binary/Zipper/Properties.agda
  src/Text/Pretty/Core.agda
Labels: breaking, enhancement, status:ready

#1106 Typeclass instances for TC monad
  CHANGELOG.md
  src/Reflection.agda
  src/Reflection/TypeChecking/Monad.agda
  src/Reflection/TypeChecking/Monad/Categorical.agda
  src/Reflection/TypeChecking/Monad/Instances.agda
  src/Reflection/TypeChecking/Monad/Syntax.agda
  src/Reflection/TypeChecking/MonadSyntax.agda
  src/Tactic/RingSolver.agda
Labels: enhancement, instances, library-design, reflection, status:ready

#1145 finish deprecating MonadSyntax
  src/Reflection/TypeChecking/MonadSyntax.agda
  src/Tactic/MonoidSolver.agda
Labels: bug, status:ready

#1151 Added a small identity in `Relation.Binary.PropositionalEquality` about how trans and cong interact
  CHANGELOG.md
  src/Relation/Binary/PropositionalEquality.agda
Labels: enhancement, status: ready

#1147 [ new ] simple inversion lemmas for Pointwise relations on Maybe
  CHANGELOG.md
  src/Data/Maybe/Relation/Binary/Pointwise.agda
Labels: enhancement, status: ready

#1140 [ new ] properties for list permutations
  CHANGELOG.md
  src/Data/List/Relation/Binary/Permutation/Propositional/Properties.agda
Labels: enhancement, status: ready

#1120 Moved well-founded proofs for `on` to `Relation.Binary.Construct.On`
  CHANGELOG.md
  src/Codata/Musical/Colist/Infinite-merge.agda
  src/Data/Fin/Subset/Induction.agda
  src/Data/Nat/Binary/Induction.agda
  src/Induction/WellFounded.agda
  src/Relation/Binary/Construct/On.agda
Labels: deprecation, refactoring, status: ready

#1161 Fixed function names in comments
  src/Data/Fin/Base.agda
Labels: bug, documentation

#1143 Move `Data.AVL` to `Data.Tree.AVL`
  CHANGELOG.md
  README/Data.agda
  README/Data/List/Interleaving.agda
  README/Data/Tree/AVL.agda
  README/Data/Trie/NonDependent.agda
  src/Data/AVL.agda
  src/Data/AVL/Height.agda
  src/Data/AVL/Indexed.agda
  src/Data/AVL/Indexed/WithK.agda
  src/Data/AVL/IndexedMap.agda
  src/Data/AVL/Key.agda
  src/Data/AVL/Map.agda
  src/Data/AVL/NonEmpty.agda
  src/Data/AVL/NonEmpty/Propositional.agda
  src/Data/AVL/Sets.agda
  src/Data/AVL/Value.agda
  src/Data/Tree/AVL.agda
  src/Data/Tree/AVL/Height.agda
  src/Data/Tree/AVL/Indexed.agda
  src/Data/Tree/AVL/Indexed/WithK.agda
  src/Data/Tree/AVL/IndexedMap.agda
  src/Data/Tree/AVL/Key.agda
  src/Data/Tree/AVL/Map.agda
  src/Data/Tree/AVL/NonEmpty.agda
  src/Data/Tree/AVL/NonEmpty/Propositional.agda
  src/Data/Tree/AVL/Sets.agda
  src/Data/Tree/AVL/Value.agda
  src/Data/Trie.agda
  src/Data/Trie/NonEmpty.agda
Labels: deprecation, library-design, refactoring, status: ready

#850 Standardise numeric predicates
  CHANGELOG.md
  src/Data/Integer/Base.agda
  src/Data/Integer/DivMod.agda
  src/Data/Integer/Literals.agda
  src/Data/Nat/Base.agda
  src/Data/Nat/Coprimality.agda
  src/Data/Nat/DivMod.agda
  src/Data/Rational/Base.agda
  src/Data/Rational/Literals.agda
  src/Data/Rational/Properties.agda
  src/Data/Rational/Unnormalised.agda
Labels: enhancement, library-design, question, status: ready

#1163 [ new ] wordsBy & words
  CHANGELOG.md
  src/Data/List/Base.agda
  src/Data/String/Base.agda
Labels: enhancement, status: ready
