Repository agda/agda-stdlib, pull requests merged in 2020-01, with the labels that each got.

#985 Add redundant fields to algebraic structures to make diamonds commute
  CHANGELOG.md
  src/Algebra/Morphism/MonoidMonomorphism.agda
  src/Algebra/Properties/BooleanAlgebra.agda
  src/Algebra/Structures.agda
  src/Algebra/Structures/Biased.agda
  src/Data/Bool/Properties.agda
  src/Data/Fin/Subset/Properties.agda
  src/Data/Integer/Properties.agda
  src/Data/List/Relation/Binary/BagAndSetEquality.agda
  src/Data/List/Relation/Binary/Permutation/Propositional/Properties.agda
  src/Data/List/Relation/Binary/Permutation/Setoid/Properties.agda
  src/Data/Nat/Binary/Properties.agda
  src/Data/Nat/Properties.agda
  src/Data/Rational/Unnormalised/Properties.agda
  src/Function/Related/TypeIsomorphisms.agda
Labels: discussion, library-design, status:ready

#1034 [ fix ] max≈v⁺ was talking about min
  CHANGELOG.md
  src/Data/List/Extrema.agda
Labels: bug, status:ready

#994 Pretty printing tables of strings
  .travis.yml
  CHANGELOG.md
  README.agda
  README/Text/Printf.agda
  README/Text/Tabular.agda
  src/Data/List/Base.agda
  src/Data/Nat/Properties.agda
  src/Data/String.agda
  src/Data/String/Base.agda
  src/Data/Vec/Base.agda
  src/Data/Vec/Bounded/Base.agda
  src/Text/Tabular/Base.agda
  src/Text/Tabular/List.agda
  src/Text/Tabular/Vec.agda
  travis/fix-whitespace.yaml
Labels: documentation, enhancement, status:ready

#1028 Standardised Eq modules in `Relation.Binary` hierarchy
  CHANGELOG.md
  src/Relation/Binary/Bundles.agda
  src/Relation/Binary/Structures.agda
Labels: bug, status:ready

#1011 [ new ] port of @jyp's pretty printing library
  CHANGELOG.md
  GenerateEverything.hs
  README.agda
  README/Text/Pretty.agda
  src/Data/DifferenceList.agda
  src/Data/Erased.agda
  src/Data/Product/Relation/Unary/All.agda
  src/Data/Refinement.agda
  src/Data/Refinement/Relation/Unary/All.agda
  src/Data/String/Unsafe.agda
  src/Data/Tree/Binary.agda
  src/Data/Tree/Binary/Properties.agda
  src/Data/Tree/Binary/Relation/Unary/All.agda
  src/Data/Tree/Binary/Relation/Unary/All/Properties.agda
  src/Text/Pretty.agda
  src/Text/Pretty/Core.agda
Labels: documentation, enhancement, paper-based, status:ready

#1029 Add `resp` proofs to `Relation.Binary.Construct.Union`
  CHANGELOG.md
  src/Relation/Binary/Construct/Union.agda
Labels: enhancement, status:ready

#1031 Add property lift-injective to Data.Fin.Properties.
  CHANGELOG.md
  src/Data/Fin/Properties.agda
Labels: enhancement, status:ready

#1030 Add some more properties to `Data.Fin.Subset.Properties`
  CHANGELOG.md
  src/Data/Fin/Subset/Properties.agda
  src/Data/Nat/Properties.agda
Labels: enhancement, status:ready

#1020 Added additional property of 2 binary operations in Algebra.Definitions
  src/Algebra/Definitions.agda
Labels: discussion, enhancement, naming

#1035 [ new ] pretty printing of rose trees
  CHANGELOG.md
  README.agda
  README/Text/Tree.agda
  src/Data/List/Base.agda
  src/Data/Tree/Rose.agda
  src/Data/Tree/Rose/Properties.agda
  src/Text/Tree/Linear.agda
Labels: documentation, enhancement, status:ready

#1045 Change argument order for binary reasoning combinators
  CHANGELOG.md
  README/Data/Nat.agda
  src/Codata/Musical/Colist.agda
  src/Data/Integer/Divisibility.agda
  src/Data/Integer/Divisibility/Signed.agda
  src/Data/Integer/Properties.agda
  src/Data/List/Relation/Binary/BagAndSetEquality.agda
  src/Data/List/Relation/Binary/Permutation/Propositional.agda
  src/Data/List/Relation/Binary/Permutation/Setoid.agda
  src/Data/List/Relation/Binary/Subset/Propositional/Properties.agda
  src/Data/List/Relation/Binary/Subset/Setoid/Properties.agda
  src/Data/Nat/Binary/Properties.agda
  src/Data/Nat/Divisibility.agda
  src/Data/Nat/Properties.agda
  src/Data/Rational/Properties.agda
  src/Relation/Binary/Construct/Closure/ReflexiveTransitive/Properties.agda
  src/Relation/Binary/PropositionalEquality/Core.agda
  src/Relation/Binary/Reasoning/Base/Double.agda
  src/Relation/Binary/Reasoning/Base/Partial.agda
  src/Relation/Binary/Reasoning/Base/Single.agda
  src/Relation/Binary/Reasoning/Base/Triple.agda
  src/Relation/Binary/Reasoning/MultiSetoid.agda
  src/Relation/Binary/Reasoning/PartialSetoid.agda
  src/Relation/Binary/Reasoning/Setoid.agda
Labels: breaking, enhancement, performance, status:ready

#1053 [ travis ] fix build
  .travis.yml
Labels: travis

#1042 added group definitons for unnormalised rational
  CHANGELOG.md
  src/Data/Rational/Unnormalised/Properties.agda
Labels: enhancement, status:ready

#1037 Fix public exports that used to be in private blocks
  CHANGELOG.md
  src/Data/List/Relation/Binary/BagAndSetEquality.agda
Labels: bug, status:ready

#1036 Generalised some permutation lemmas from propositional to setoid equality
  CHANGELOG.md
  src/Data/List/Relation/Binary/Permutation/Setoid.agda
  src/Data/List/Relation/Binary/Permutation/Setoid/Properties.agda
  src/Data/Nat/Properties.agda
Labels: enhancement, status:ready

#993 Proved a property of Vectors related to lookup and Fin.splitAt
  CHANGELOG.md
  src/Data/Sum/Properties.agda
  src/Data/Vec/Properties.agda
Labels: enhancement, status:ready

#1060 [ fix #1040 ] instructions to use fix-whitespace
  .travis.yml
  CHANGELOG.md
  GNUmakefile
  HACKING.md
  fix-whitespace.yaml
Labels: admin, status:ready

#1050 Move monoid solver to `Tactic.MonoidSolver`
  CHANGELOG.md
  README.agda
  README/Solvers/ReflectiveMonoid.agda
  README/Tactic/MonoidSolver.agda
  src/Algebra/Solver/Monoid.agda
  src/Data/List/Solver.agda
  src/Tactic/MonoidSolver.agda
Labels: cosmetic, library-design, status:ready, tactics

#1057 Rename `Algebra.FunctionProperties.Consequences` to `Algebra.Consequences`
  CHANGELOG.md
  src/Algebra/Consequences/Base.agda
  src/Algebra/Consequences/Propositional.agda
  src/Algebra/Consequences/Setoid.agda
  src/Algebra/Construct/LiftedChoice.agda
  src/Algebra/FunctionProperties/Consequences.agda
  src/Algebra/FunctionProperties/Consequences/Core.agda
  src/Algebra/FunctionProperties/Consequences/Propositional.agda
  src/Algebra/Properties/BooleanAlgebra.agda
  src/Algebra/Structures.agda
  src/Algebra/Structures/Biased.agda
  src/Data/Nat/Binary/Properties.agda
  src/Data/Nat/Properties.agda
  src/Data/Rational/Properties.agda
  src/Data/Rational/Unnormalised/Properties.agda
Labels: library-design, refactoring, status:ready

#1056 Add deprecation warnings to more modules
  CHANGELOG.md
  README/Data/List.agda
  README/Data/Record.agda
  src/Algebra/FunctionProperties.agda
  src/Algebra/FunctionProperties/Core.agda
  src/Algebra/Solver/Ring/AlmostCommutativeRing.agda
  src/Codata/Cowriter.agda
  src/Codata/Musical/Colist.agda
  src/Data/Bin.agda
  src/Data/Bin/Properties.agda
  src/Data/BoundedVec.agda
  src/Data/BoundedVec/Inefficient.agda
  src/Data/List/Extrema.agda
  src/Data/List/Relation/Binary/Permutation/Inductive.agda
  src/Data/List/Relation/Binary/Permutation/Inductive/Properties.agda
  src/Data/List/Relation/Ternary/Interleaving/Propositional.agda
  src/Data/Product/N-ary.agda
  src/Data/Product/N-ary/Categorical.agda
  src/Data/Product/N-ary/Properties.agda
  src/Data/Table.agda
  src/Data/Table/Base.agda
  src/Data/Table/Properties.agda
  src/Data/Table/Relation/Binary/Equality.agda
  src/Data/Table/Relation/Equality.agda
  src/Data/Vec/Relation/Binary/Pointwise/Inductive.agda
  src/Induction/Nat.agda
  src/Record.agda
  src/Relation/Binary/PropositionalEquality.agda
  src/Universe.agda
Labels: deprecation, status:ready

#1062 added definitions for abelian group on unnormalised rationals
  CHANGELOG.md
  src/Data/Rational/Unnormalised/Properties.agda
Labels: enhancement, status:ready

#1066 Add pointers to universe polymorphic variants of empty and unit types
  src/Data/Empty.agda
  src/Data/Unit/Base.agda
Labels: documentation, status:ready
