Repository agda/agda-stdlib, pull requests merged in 2020-09, with the labels that each got.

#1290 Make gcd' comment agree with the implementation
  src/Data/Nat/GCD.agda
Labels: bug, documentation, status: ready

#1285 First step of float revision
  .travis.yml
  CHANGELOG.md
  src/Data/Float.agda
  src/Data/Float/Base.agda
  src/Data/Float/Properties.agda
Labels: breaking, status: ready, upstream

#1294 Generic traversals of reflected terms
  CHANGELOG.md
  src/Reflection/DeBruijn.agda
  src/Reflection/Traversal.agda
Labels: enhancement, reflection, status: ready

#1296 Tiny build utils enhancements
  .travis.yml
  AllNonAsciiChars.hs
  CHANGELOG.md
  GenerateEverything.hs
  agda-stdlib-utils.cabal
Labels: admin, status: being-worked-on
