Repository agda/agda-stdlib, pull requests merged in 2020-08, with the labels that each got.

#1260 Rename all and any to all? and any? for consistency
  CHANGELOG.md
  src/Data/List/Countdown.agda
  src/Data/List/Membership/DecSetoid.agda
  src/Data/List/Relation/Unary/All.agda
  src/Data/List/Relation/Unary/AllPairs.agda
  src/Data/List/Relation/Unary/Any.agda
  src/Data/List/Relation/Unary/Grouped.agda
  src/Data/Vec/Membership/DecSetoid.agda
  src/Data/Vec/Relation/Unary/All.agda
  src/Data/Vec/Relation/Unary/AllPairs.agda
  src/Data/Vec/Relation/Unary/Any.agda
Labels: deprecation, refactoring, status: ready

#1264 Show that `index (∈-lookup i xs)` is in fact `i`
  CHANGELOG.md
  src/Data/Vec/Membership/Propositional/Properties.agda
Labels: enhancement, status: ready

#1263 Add function to reduce All into Vec
  CHANGELOG.md
  src/Data/Vec/Relation/Unary/All.agda
Labels: enhancement, status: ready

#1265 Fix level for FixPoint in Induction.WellFounded
  CHANGELOG.md
  src/Induction/WellFounded.agda
Labels: bug, status: ready

#1258 WIP: Show that `Data.Nat.Show.charsInBase` is injective
  CHANGELOG.md
  src/Data/Digit/Properties.agda
  src/Data/Fin/Properties.agda
  src/Data/List/Properties.agda
  src/Data/Nat/Show.agda
  src/Data/Nat/Show/Properties.agda
Labels: enhancement, status: blocked-by-issue, status: ready

#1273 Add more properties to Data.Tree.Binary.Properties
  CHANGELOG.md
  src/Data/Tree/Binary/Properties.agda
Labels: enhancement, status: ready

#1259 Additional compositions with binary functions
  CHANGELOG.md
  src/Category/Applicative/Indexed.agda
  src/Category/Applicative/Predicate.agda
  src/Data/Product.agda
  src/Data/Sum/Base.agda
  src/Data/These.agda
  src/Function/Base.agda
  src/Function/Definitions.agda
Labels: enhancement, status: ready

#1224 add irefl, icong and icong'
  CHANGELOG.md
  src/Relation/Binary/PropositionalEquality/Core.agda
Labels: enhancement, status: ready

#1109 Add some standard algebraic constructs (unit and pairing)
  CHANGELOG.md
  src/Algebra/Construct/DirectProduct.agda
  src/Algebra/Construct/Zero.agda
  src/Algebra/Module/Construct/DirectProduct.agda
  src/Data/Product.agda
Labels: enhancement, status: ready

#1182 Add lexicographic ordering on vectors
  CHANGELOG.md
  src/Data/Unit/Properties.agda
  src/Data/Vec/Relation/Binary/Lex/Core.agda
  src/Data/Vec/Relation/Binary/Lex/NonStrict.agda
  src/Data/Vec/Relation/Binary/Lex/Strict.agda
  src/Relation/Binary/Construct/NonStrictToStrict.agda
Labels: discussion, enhancement, status: ready

#1286 [ changelog ] document new functions in Data.Product
  CHANGELOG.md
Labels: documentation, status: ready

#1203 WIP: port old TypeIsomorphisms over to the new Function hierarchy.
  CHANGELOG.md
  src/Data/Product.agda
  src/Data/Product/Algebra.agda
  src/Data/Product/Properties.agda
  src/Data/Sum/Algebra.agda
  src/Data/Sum/Base.agda
  src/Function/Bundles.agda
  src/Function/Properties.agda
  src/Relation/Nullary/Decidable.agda
  src/Relation/Nullary/Indexed/Negation.agda
Labels: enhancement, status: ready

#1228 Fixity
  CHANGELOG.md
  README/Design/Fixity.agda
  src/Data/Graph/Acyclic.agda
  src/Data/Integer/Divisibility/Signed.agda
  src/Data/List/Fresh/Membership/Setoid.agda
  src/Data/List/Fresh/Relation/Unary/All.agda
  src/Data/List/Relation/Binary/Prefix/Heterogeneous.agda
  src/Data/List/Relation/Binary/Sublist/DecSetoid.agda
  src/Data/List/Relation/Binary/Sublist/Heterogeneous/Solver.agda
  src/Data/List/Relation/Binary/Sublist/Propositional/Example/UniqueBoundVariables.agda
  src/Data/List/Relation/Binary/Subset/Propositional/Properties.agda
  src/Data/List/Relation/Binary/Suffix/Heterogeneous.agda
  src/Data/List/Relation/Ternary/Interleaving.agda
  src/Data/List/Relation/Unary/First.agda
  src/Data/Nat/Binary/Base.agda
  src/Data/Nat/Binary/Properties.agda
  src/Data/Nat/InfinitelyOften.agda
  src/Function/Nary/NonDependent/Base.agda
  src/Induction/Lexicographic.agda
  src/Relation/Binary/Construct/Closure/ReflexiveTransitive.agda
  src/Relation/Binary/Construct/StrictToNonStrict.agda
  src/Tactic/RingSolver.agda
  src/Tactic/RingSolver/NonReflective.agda
Labels: breaking, bug, status: ready
