Repository agda/agda-stdlib, pull requests merged in 2020-10, with the labels that each got.

#1299 Generic traversals of reflected terms
  CHANGELOG.md
  src/Reflection/DeBruijn.agda
  src/Reflection/Traversal.agda
Labels: enhancement, reflection, status: ready

#1300 (Near)Semiring & Lattice morphisms
  CHANGELOG.md
  src/Algebra/Bundles.agda
  src/Algebra/Morphism/Structures.agda
Labels: enhancement, status: ready

#1307 Add Reflection.TypeChecking.Format.errorPartFmt
  CHANGELOG.md
  src/Reflection/TypeChecking/Format.agda
  src/Reflection/TypeChecking/Monad.agda
Labels: enhancement, status: ready

#1312 Add version to library name
  CHANGELOG.md
  notes/release-guide.txt
  standard-library.agda-lib
Labels: admin, enhancement, status: ready

#1311 Generalize strengthening to take a "by" argument
  src/Reflection/DeBruijn.agda
Labels: enhancement, status: ready

#1314 [ fix #1313 ] List/**/All/Properties.map-id has too many parameters
  CHANGELOG.md
  src/Data/List/Relation/Unary/All/Properties.agda
Labels: breaking, bug, status: ready

#1308 Add CancellativeCommutativeSemiring
  CHANGELOG.md
  src/Algebra/Bundles.agda
  src/Algebra/Definitions.agda
  src/Algebra/Structures.agda
Labels: enhancement, status: ready

#1291 Add module with utilities for making system calls.
  .travis.yml
  CHANGELOG.md
  README/Reflection/External.agda
  src/Reflection/External.agda
Labels: reflection, status: ready

#1317 Add some properties relating to List.concat
  CHANGELOG.md
  src/Data/List/Properties.agda
Labels: enhancement, status: ready

#1316 Data.Vec.Properties: Add take/drop proofs, zipWith-replicate
  CHANGELOG.md
  src/Data/Vec/Properties.agda
Labels: enhancement, status: ready

#1315 Tidying up in `Relation.Binary.Construct.Closure`
  CHANGELOG.md
  src/Data/Vec/Relation/Binary/Pointwise/Extensional.agda
  src/Induction/WellFounded.agda
  src/Relation/Binary/Construct/Closure/Equivalence.agda
  src/Relation/Binary/Construct/Closure/Reflexive.agda
  src/Relation/Binary/Construct/Closure/Reflexive/Properties.agda
  src/Relation/Binary/Construct/Closure/Reflexive/Properties/WithK.agda
  src/Relation/Binary/Construct/Closure/Symmetric.agda
  src/Relation/Binary/Construct/Closure/Transitive.agda
Labels: bug, deprecation, naming, refactoring, status: ready

#1324 Add Reflection.Universe
  CHANGELOG.md
  src/Reflection/Universe.agda
Labels: enhancement, reflection, status: ready

#1323 Level polymorphism for Algebra.Construct.Zero and Algebra.Module.Construct.Zero
  CHANGELOG.md
  src/Algebra/Construct/Zero.agda
  src/Algebra/Module/Construct/Zero.agda
Labels: breaking, enhancement, status: ready

#1326 Changes related to SizeUniv [agda/agda#5000]
  .travis.yml
  src/Codata/Thunk.agda
  src/Size.agda
Labels: status: being-worked-on, upstream

#1336 Add +-*-commutativeSemiring bundle for Integer (#1293)
  CHANGELOG.md
  src/Data/Integer/Properties.agda
Labels: enhancement, status: ready

#1325 Annotated reflected syntax
  CHANGELOG.md
  GenerateEverything.hs
  src/Reflection/Annotated.agda
  src/Reflection/Annotated/Free.agda
Labels: discussion, enhancement, status: ready

#1329 Fix precedence of _≉_ and re-export it via algebraic bundles
  CHANGELOG.md
  src/Algebra/Bundles.agda
  src/Relation/Binary/Bundles.agda
Labels: bug, enhancement, status: ready
