Repository agda/agda-stdlib, pull requests merged in 2020-12, with the labels that each got.

#1364 [ refactor ] IO module
  CHANGELOG.md
  README/Foreign/Haskell.agda
  README/IO.agda
  src/Data/String/Base.agda
  src/IO.agda
Labels: breaking, documentation, refactoring, status: ready

#1372 [ fix ] lines should not drop empty lines
  CHANGELOG.md
  src/Data/List/Base.agda
  src/Data/String/Base.agda
Labels: bug, enhancement, status: ready

#1343 [ new ] le for chars
  CHANGELOG.md
  README/Data/Trie/NonDependent.agda
  src/Data/Char.agda
  src/Data/Char/Base.agda
  src/Data/Char/Instances.agda
  src/Data/Char/Properties.agda
  src/Data/String/Base.agda
  src/Data/String/Properties.agda
  src/Relation/Binary/Construct/Closure/Reflexive.agda
Labels: breaking, discussion, enhancement, library-design, status: ready

#1366 [ new ] postulate length-tail lemma
  CHANGELOG.md
  src/Data/String/Base.agda
  src/Data/String/Unsafe.agda
Labels: enhancement, status: ready

#1369 [ fix #1368 ] ⊤-returning IO functions made level polymorphic
  CHANGELOG.md
  README/Debug/Trace.agda
  src/IO.agda
Labels: breaking, enhancement, status: ready

#1376 Add Algebra.Morphism.LatticeMonomorphism
  CHANGELOG.md
  src/Algebra/Morphism/LatticeMonomorphism.agda
Labels: enhancement, status: ready

#1268 Added properties of the delay monad termination proof
  CHANGELOG.md
  src/Codata/Delay/Properties.agda
Labels: enhancement, status: ready

#1367 [ new ] bindings for Haskell's System.Exit
  CHANGELOG.md
  GenerateEverything.hs
  src/System/Exit.agda
  src/System/Exit/Primitive.agda
Labels: enhancement, status: ready

#1375 Add several Data.Nat.Properties
  CHANGELOG.md
  src/Data/Nat/Properties.agda
Labels: enhancement, status: ready

#1377 Deprecate `Algebra.Operations.Semiring`
  CHANGELOG.md
  src/Algebra/Operations/Semiring.agda
  src/Algebra/Properties/Monoid/Multiplication.agda
  src/Algebra/Properties/Semiring/Exponentiation.agda
  src/Algebra/Properties/Semiring/Multiplication.agda
  src/Algebra/Solver/Ring.agda
  src/Algebra/Solver/Ring/NaturalCoefficients.agda
  src/Algebra/Solver/Ring/NaturalCoefficients/Default.agda
Labels: deprecation, status: ready

#1371 Various AVL goodies
  CHANGELOG.md
  src/Data/Tree/AVL.agda
  src/Data/Tree/AVL/Indexed.agda
  src/Data/Tree/AVL/IndexedMap.agda
  src/Data/Tree/AVL/Map.agda
  src/Data/Tree/AVL/Sets.agda
Labels: enhancement, status: ready

#1378 [ fix #667 ] readMaybe for natural numbers
  CHANGELOG.md
  src/Data/Fin/Show.agda
  src/Data/Integer.agda
  src/Data/Integer/Show.agda
  src/Data/Maybe/Base.agda
  src/Data/Nat/Show.agda
  src/Data/Rational.agda
  src/Data/Rational/Show.agda
  src/Text/Printf.agda
Labels: enhancement, status: ready

#1379 Update variable policy in style guide
  fix-whitespace.yaml
  notes/style-guide.md
  src/Data/List/Relation/Unary/All.agda
  src/Data/List/Relation/Unary/All/Properties.agda
  src/Data/List/Relation/Unary/Any.agda
  src/Data/List/Relation/Unary/Any/Properties.agda
Labels: admin, discussion, refactoring, status: ready

#1381 Add properties of <, ≤, ⊔ and ⊓ operators in Data.Integer
  CHANGELOG.md
  src/Data/Integer/Properties.agda
  src/Data/Rational/Properties.agda
  src/Data/Rational/Unnormalised/Properties.agda
Labels: enhancement, status: ready

#1382 Add various lemmas about list relations
  CHANGELOG.md
  src/Data/List/Base.agda
  src/Data/List/Extrema.agda
  src/Data/List/Membership/DecPropositional.agda
  src/Data/List/Membership/DecSetoid.agda
  src/Data/List/Membership/Propositional/Properties.agda
  src/Data/List/Membership/Setoid/Properties.agda
  src/Data/List/Relation/Binary/Sublist/Setoid.agda
  src/Data/List/Relation/Binary/Subset/Propositional/Properties.agda
  src/Data/List/Relation/Binary/Subset/Setoid/Properties.agda
  src/Data/List/Relation/Unary/Any/Properties.agda
  src/Data/List/Relation/Unary/Unique/DecPropositional.agda
  src/Data/List/Relation/Unary/Unique/DecPropositional/Properties.agda
  src/Data/List/Relation/Unary/Unique/DecSetoid.agda
  src/Data/List/Relation/Unary/Unique/DecSetoid/Properties.agda
  src/Data/List/Relation/Unary/Unique/Setoid.agda
  src/Relation/Binary/PropositionalEquality/Core.agda
Labels: enhancement, status: ready

#1345 Generic GCD. Properties of Irreducible, Coprime, GCD.
  CHANGELOG.md
  src/Algebra/Bundles.agda
  src/Algebra/Divisibility.agda
  src/Algebra/Primality.agda
  src/Algebra/Properties/CommutativeMagma/Divisibility.agda
  src/Algebra/Properties/Magma/Divisibility.agda
  src/Algebra/Properties/Monoid/Divisibility.agda
  src/Algebra/Properties/Semiring/Divisibility.agda
  src/Algebra/Properties/Semiring/GCD.agda
  src/Algebra/Properties/Semiring/Primality.agda
  src/Data/Sum/Base.agda
Labels: enhancement, library-design, status: ready
