Repository agda/agda-stdlib, pull requests merged in 2020-03, with the labels that each got.

#1100 Suppress warnings from `Algebra.Properties.CommutativeMonoid`
  src/Algebra/Operations/CommutativeMonoid.agda
  src/Algebra/Properties/CommutativeMonoid.agda
Labels: deprecation, discussion, library-design, status:ready

#1094 Deprecated `Induction.WellFounded.Lexicographic`
  CHANGELOG.md
  src/Data/Product/Relation/Binary/Lex/NonStrict.agda
  src/Data/Product/Relation/Binary/Lex/Strict.agda
  src/Induction/WellFounded.agda
Labels: deprecation, enhancement, library-design, status:ready

#1095 Use generalized variables in Category subdirectory
  src/Category/Applicative.agda
  src/Category/Applicative/Indexed.agda
  src/Category/Applicative/Predicate.agda
  src/Category/Comonad.agda
  src/Category/Functor.agda
  src/Category/Functor/Predicate.agda
  src/Category/Monad.agda
  src/Category/Monad/Continuation.agda
  src/Category/Monad/Indexed.agda
  src/Category/Monad/Partiality.agda
  src/Category/Monad/Partiality/All.agda
  src/Category/Monad/Predicate.agda
  src/Category/Monad/Reader.agda
  src/Category/Monad/State.agda
Labels: refactoring, status:ready

#1104 Add `it` utility function
  CHANGELOG.md
  src/Function/Base.agda
Labels: enhancement, status:ready

#1101 Get rid of slow 'rewrite'
  src/Data/List/Relation/Unary/Any/Properties.agda
Labels: performance, refactoring

#1112 Rename proofs relating < and <' in Data.Integer.Properties
  CHANGELOG.md
  src/Data/Integer/Properties.agda
Labels: naming, status:ready

#1110 Various additions to the style guide
  notes/style-guide.md
Labels: discussion, documentation

#1117 Smarter trans for propositional permutations
  CHANGELOG.md
  src/Data/List/Relation/Binary/Permutation/Propositional.agda
Labels: performance, status:ready

#1115 Rename Reflection.TCMonadSyntax to Reflection.TypeChecking.MonadSyntax
  CHANGELOG.md
  src/Reflection.agda
  src/Reflection/TypeChecking/MonadSyntax.agda
  src/Tactic/MonoidSolver.agda
  src/Tactic/RingSolver.agda
Labels: refactoring, status:ready
