Repository agda/agda-stdlib, pull requests merged in 2020-06, with the labels that each got.

#1216 Deprecate *-+- algebraic structures/bundles in favour of +-*-
  CHANGELOG.md
  src/Data/Nat/Binary/Properties.agda
  src/Data/Nat/Properties.agda
  src/Data/Nat/Solver.agda
  src/Data/Nat/Tactic/RingSolver.agda
Labels: deprecation, status: ready

#1215 Move `Rational.Unnormalised` to `Rational.Unnormalised.Base`
  src/Data/Rational/Base.agda
  src/Data/Rational/Properties.agda
  src/Data/Rational/Unnormalised.agda
  src/Data/Rational/Unnormalised/Base.agda
  src/Data/Rational/Unnormalised/Properties.agda
Labels: library-design, refactoring, status: ready

#1208 Add Symmetry relations for Inverse (& friends) and IsEquivalence bundles
  CHANGELOG.md
  src/Function/Construct/Composition.agda
  src/Function/Construct/Symmetry.agda
  src/Function/Properties/Equivalence.agda
  src/Function/Properties/Inverse.agda
Labels: enhancement, library-design, status: ready

#1213 added `Morphism` definition to Function.Core
  CHANGELOG.md
  CHANGELOG/v1.4.md
  src/Algebra/Morphism.agda
  src/Algebra/Morphism/Definitions.agda
  src/Algebra/Solver/Ring/AlmostCommutativeRing.agda
  src/Category/Applicative/Indexed.agda
  src/Category/Functor.agda
  src/Data/Vec/Categorical.agda
  src/Function/Core.agda
  src/Relation/Binary/Morphism/Definitions.agda
  src/Tactic/RingSolver/Core/AlmostCommutativeRing.agda
Labels: deprecation, status: ready

#1226 Update decidable equality of reflected syntax
  .travis.yml
  src/Reflection/Pattern.agda
  src/Reflection/Show.agda
  src/Reflection/Term.agda
Labels: breaking, reflection, status: ready, upstream

#1218 Adding properties on unnormalised rationals
  CHANGELOG/v1.4.md
  src/Data/Integer/Base.agda
  src/Data/Integer/Properties.agda
  src/Data/Rational/Unnormalised.agda
  src/Data/Rational/Unnormalised/Base.agda
  src/Data/Rational/Unnormalised/Properties.agda
Labels: bug, enhancement, status: ready

#1088 [ new ] alternative closure operator
  CHANGELOG.md
  src/Relation/Unary/Closure/Base.agda
  src/Relation/Unary/Closure/Preorder.agda
  src/Relation/Unary/Closure/StrictPartialOrder.agda
Labels: breaking, status: ready

#1225 Move `≤-pred` to Data.Nat.Properties.Base
  src/Data/Fin/Base.agda
  src/Data/Nat/Properties.agda
  src/Data/Nat/Properties/Core.agda
Labels: performance, refactoring, status: ready

#1232 Expose `*-zero`, `*-zeroˡ`, `*-zeroʳ` from `Data.Rational.Properties`
  CHANGELOG.md
  src/Data/Rational/Properties.agda
Labels: enhancement, status: ready

#1239 Changelog for #1226
  CHANGELOG.md
Labels: documentation, status: ready

#1220 [ fix #1128 ] Use the BUILTIN Maybe
  .travis.yml
  CHANGELOG.md
  GNUmakefile
  README/Foreign/Haskell.agda
  src/Data/Maybe/Base.agda
  src/Foreign/Haskell.agda
  src/Foreign/Haskell/Coerce.agda
  src/Foreign/Haskell/Maybe.agda
Labels: FFI, enhancement, status: ready, upstream

#1235 Generalize printf
  CHANGELOG.md
  src/Text/Format.agda
  src/Text/Format/Generic.agda
  src/Text/Printf.agda
  src/Text/Printf/Generic.agda
Labels: enhancement, status: ready

#1240 Add composition in Relation.Binary.Construct
  CHANGELOG.md
  src/Relation/Binary/Construct/Composition.agda
Labels: enhancement, status: ready

#1241 Data.Vec.Functional operations and properties
  CHANGELOG.md
  src/Data/Fin/Base.agda
  src/Data/Fin/Properties.agda
  src/Data/Vec/Functional.agda
  src/Data/Vec/Functional/Properties.agda
Labels: enhancement, status: ready

#1236 Printf for reflection type errors
  CHANGELOG.md
  src/Reflection/TypeChecking/Format.agda
  src/Reflection/TypeChecking/Monad.agda
Labels: enhancement, status: ready

#1217 More Fin properties
  CHANGELOG.md
  src/Data/Fin/Properties.agda
  src/Data/Maybe/Properties.agda
  src/Function/Base.agda
Labels: enhancement, status: ready
