Repository agda/agda-stdlib, pull requests merged in 2021-03, with the labels that each got.

#1374 Add min/max/absolute value for ℚ
  CHANGELOG.md
  src/Data/Nat/DivMod.agda
  src/Data/Nat/Divisibility/Core.agda
  src/Data/Nat/GCD.agda
  src/Data/Nat/Properties.agda
  src/Data/Rational/Base.agda
  src/Data/Rational/Properties.agda
  src/Data/Rational/Unnormalised/Properties.agda
  src/Relation/Binary/Morphism/OrderMonomorphism.agda
Labels: enhancement, status: ready

#1048 [ new ] pretty printing of binary trees
  CHANGELOG.md
  README.agda
  README/Data/Tree/Binary.agda
  README/Data/Tree/Rose.agda
  src/Data/Tree/Binary.agda
  src/Data/Tree/Binary/Show.agda
  src/Data/Tree/Rose.agda
  src/Data/Tree/Rose/Show.agda
  src/Text/Tabular/Base.agda
  src/Text/Tabular/List.agda
  src/Text/Tree/Linear.agda
Labels: discussion, documentation, enhancement, library-design, status: ready

#1448 [ new ] more interleaving functions in Codata.Stream
  CHANGELOG.md
  src/Codata/Stream.agda
Labels: enhancement, status: ready

#1444 Add lexicographic product over algebras
  CHANGELOG.md
  src/Algebra/Construct/LexProduct.agda
  src/Algebra/Construct/LexProduct/Base.agda
  src/Algebra/Construct/LexProduct/Inner.agda
  src/Relation/Nullary/Negation.agda
  src/Relation/Nullary/Negation/Core.agda
Labels: enhancement, status: ready

#1449 Fix broken link to the "low-hanging-fruit" tag
  README.md
Labels: admin, status: ready

#1447 readjust reasoning APIs
  CHANGELOG.md
  src/Relation/Binary/Reasoning/Base/Partial.agda
  src/Relation/Binary/Reasoning/Base/Single.agda
  src/Relation/Binary/Reasoning/Setoid.agda
Labels: breaking, enhancement, status: ready

#1451 IO.Finite.putStrLn: actually do putStrLn
  src/IO/Finite.agda
Labels: bug, status: ready

#1453 Adapt to https://github.com/agda/agda/pull/5289
  .travis.yml
  CHANGELOG.md
  src/Reflection/Annotated.agda
  src/Reflection/Show.agda
  src/Reflection/Term.agda
  src/Reflection/Traversal.agda
  travis/index.agda
  travis/index.sh
Labels: reflection, status: ready, upstream
