Repository agda/agda-stdlib, pull requests merged in 2021-07, with the labels that each got.

#1528 Added some basic properties of bijections (new function hierarchy)
  CHANGELOG.md
  src/Function/Construct/Symmetry.agda
  src/Function/Properties/Bijection.agda
  src/Function/Properties/Equivalence.agda
  src/Function/Properties/Inverse.agda
Labels: enhancement, status: ready

#1532 Add Data.Product.Properties.map-cong₂
  CHANGELOG.md
  src/Codata/M/Properties.agda
  src/Data/Product/Properties.agda
Labels: enhancement, status: ready

#1537 Stop `Data.Rational.Base` exporting `+0` and `+[1+_]`
  CHANGELOG.md
  src/Data/Rational/Base.agda
  src/Data/Rational/Properties.agda
Labels: breaking, status: ready

#1540 Remove redundancy in ring morphisms etc
  CHANGELOG.md
  src/Algebra/Morphism/Construct/Composition.agda
  src/Algebra/Morphism/Construct/Identity.agda
  src/Algebra/Morphism/RingMonomorphism.agda
  src/Algebra/Morphism/Structures.agda
  src/Data/Rational/Properties.agda
  src/Data/Rational/Unnormalised/Properties.agda
Labels: breaking, refactoring, status: ready

#1533 Move `Strict` to `Function.Strict` and move `_$!_` there
  CHANGELOG.md
  src/Codata/Cofin.agda
  src/Codata/Conat/Properties.agda
  src/Codata/Covec.agda
  src/Codata/Covec/Properties.agda
  src/Codata/Delay/Properties.agda
  src/Codata/M/Bisimilarity.agda
  src/Codata/M/Properties.agda
  src/Codata/Musical/Cofin.agda
  src/Codata/Musical/M/Indexed.agda
  src/Codata/Stream/Categorical.agda
  src/Codata/Stream/Properties.agda
  src/Function.agda
  src/Function/Base.agda
  src/Function/Core.agda
  src/Function/Strict.agda
  src/Strict.agda
  src/Text/Format/Generic.agda
  src/Text/Printf.agda
Labels: deprecation, refactoring, status: ready

#1548 Simplify definition of Data.Nat.Properties.<⇒≤
  src/Data/Nat/Properties.agda
Labels: refactoring, status: ready

#1541 add `diagonal` and some properties about `Vec`
  CHANGELOG.md
  src/Data/Vec/Base.agda
  src/Data/Vec/Categorical.agda
  src/Data/Vec/Properties.agda
  src/Data/Vec/Relation/Unary/Any/Properties.agda
Labels: enhancement, status: ready

#1551 (Semi)Ring instances for DirectProduct
  CHANGELOG.md
  src/Algebra/Construct/DirectProduct.agda
  src/Algebra/Morphism/Structures.agda
Labels: enhancement, status: ready

#1554 Define isLoop
  CHANGELOG.md
  src/Algebra/Bundles.agda
  src/Algebra/Structures.agda
Labels: enhancement, status: ready

#1556 [ new ] Data.Default
  CHANGELOG.md
  README/Data.agda
  README/Data/Default.agda
  src/Data/Default.agda
Labels: enhancement, status: ready

#1557 polymorphic versions of empty and universal sets
  CHANGELOG.md
  src/Relation/Unary/Polymorphic.agda
Labels: enhancement, status: ready

#1559 Generalised ordering relations in `Fin`
  CHANGELOG.md
  src/Data/Fin/Base.agda
  src/Data/Fin/Properties.agda
Labels: breaking, enhancement, status: ready

#1558 add 2 versions of equality of predicates
  CHANGELOG.md
  src/Relation/Unary.agda
  src/Relation/Unary/Relation/Binary/Equality.agda
Labels: enhancement, status: ready

#1561 Update `Function.Related` for the new function hierarchy
  CHANGELOG.md
  src/Function/Bundles.agda
  src/Function/Consequences.agda
  src/Function/Definitions.agda
  src/Function/Definitions/Core1.agda
  src/Function/Definitions/Core2.agda
  src/Function/Properties/Bijection.agda
  src/Function/Properties/Equivalence.agda
  src/Function/Properties/Inverse.agda
  src/Function/Properties/RightInverse.agda
  src/Function/Properties/Surjection.agda
  src/Function/Related.agda
  src/Function/Related/Propositional.agda
Labels: bug, enhancement, refactoring, status: ready

#1538 RFC: changed `_/_` and `_%_` to use irrelevant instance arguments
  CHANGELOG.md
  src/Data/Integer/Base.agda
  src/Data/Integer/DivMod.agda
  src/Data/Nat/Base.agda
  src/Data/Nat/Coprimality.agda
  src/Data/Nat/DivMod.agda
  src/Data/Nat/DivMod/WithK.agda
  src/Data/Nat/Divisibility.agda
  src/Data/Nat/GCD.agda
  src/Data/Nat/LCM.agda
  src/Data/Nat/PseudoRandom/LCG.agda
  src/Data/Rational/Base.agda
  src/Data/Rational/Properties.agda
  src/Data/Rational/Unnormalised/Base.agda
  src/System/Clock.agda
Labels: breaking, instances, refactoring, status: ready
