Repository agda/agda-stdlib, pull requests merged in 2021-06, with the labels that each got.

#1515 [ cleanup ] use modules rather than long names
  CHANGELOG.md
  src/Codata/Musical/Conversion.agda
Labels: refactoring, status: ready

#1514 [ Improved fix #1510 ] Get rid of `error`, use `throwError` and `die`.
  GenerateEverything.hs
  agda-stdlib-utils.cabal
Labels: bug, continuous-integration, status: ready

#1516 [ actions ] move build & html doc deploy to actions
  .github/workflows/ci-ubuntu.yml
  .github/workflows/haskell-ci.yml
  .travis.yml
  travis/index.agda
  travis/index.sh
  travis/safe.agda
Labels: continuous-integration, documentation, status: ready

#1517 [ actions ] preserves old HTML doc
  .github/workflows/ci-ubuntu.yml
Labels: bug, continuous-integration, documentation, status: ready

#1522 [ ci ] doc for the actions script
  .github/workflows/ci-ubuntu.yml
Labels: continuous-integration, documentation, status: ready

#1502 Add algebra morphism identity and composition constructions
  CHANGELOG.md
  src/Algebra/Bundles.agda
  src/Algebra/Morphism/Construct/Composition.agda
  src/Algebra/Morphism/Construct/Identity.agda
  src/Algebra/Morphism/Structures.agda
Labels: enhancement, status: ready

#1501 Define `IsUnitalMagma` and `IsQuasigroup`
  CHANGELOG.md
  src/Algebra/Bundles.agda
  src/Algebra/Structures.agda
Labels: enhancement, status: ready
