Repository agda/agda-stdlib, pull requests merged in 2021-11, with the labels that each got.

#1616 Make J universe-polymorphic on A
  CHANGELOG.md
  src/Relation/Binary/PropositionalEquality/Properties.agda
Labels: enhancement, status: ready

#1622 Bump cabal file package upper bounds
  .github/workflows/ci-ubuntu.yml
  agda-stdlib-utils.cabal
Labels: admin

#1621 associativity for vectors
  CHANGELOG.md
  src/Data/Vec/Relation/Binary/Equality/Setoid.agda
Labels: enhancement, status: ready

#1613 Fin/function isomorphism
  CHANGELOG.md
  src/Data/Fin/Base.agda
  src/Data/Fin/Properties.agda
Labels: enhancement, status: ready

#1624 Data.List.Fresh.NonEmpty
  CHANGELOG.md
  src/Data/List/Fresh/NonEmpty.agda
Labels: enhancement, status: ready

#1108 Pull lattice-like structures out of Algebra, into Algebra.Lattice
  CHANGELOG.md
  src/Algebra/Bundles.agda
  src/Algebra/Consequences/Setoid.agda
  src/Algebra/Construct/DirectProduct.agda
  src/Algebra/Construct/LiftedChoice.agda
  src/Algebra/Construct/NaturalChoice/Base.agda
  src/Algebra/Construct/NaturalChoice/Max.agda
  src/Algebra/Construct/NaturalChoice/MaxOp.agda
  src/Algebra/Construct/NaturalChoice/Min.agda
  src/Algebra/Construct/NaturalChoice/MinMaxOp.agda
  src/Algebra/Construct/NaturalChoice/MinOp.agda
  src/Algebra/Construct/Subst/Equality.agda
  src/Algebra/Construct/Zero.agda
  src/Algebra/Lattice.agda
  src/Algebra/Lattice/Bundles.agda
  src/Algebra/Lattice/Construct/DirectProduct.agda
  src/Algebra/Lattice/Construct/LiftedChoice.agda
  src/Algebra/Lattice/Construct/NaturalChoice/MaxOp.agda
  src/Algebra/Lattice/Construct/NaturalChoice/MinMaxOp.agda
  src/Algebra/Lattice/Construct/NaturalChoice/MinOp.agda
  src/Algebra/Lattice/Construct/Subst/Equality.agda
  src/Algebra/Lattice/Construct/Zero.agda
  src/Algebra/Lattice/Morphism.agda
  src/Algebra/Lattice/Morphism/Construct/Composition.agda
  src/Algebra/Lattice/Morphism/Construct/Identity.agda
  src/Algebra/Lattice/Morphism/LatticeMonomorphism.agda
  src/Algebra/Lattice/Morphism/Structures.agda
  src/Algebra/Lattice/Properties/BooleanAlgebra.agda
  src/Algebra/Lattice/Properties/BooleanAlgebra/Expression.agda
  src/Algebra/Lattice/Properties/DistributiveLattice.agda
  src/Algebra/Lattice/Properties/Lattice.agda
  src/Algebra/Lattice/Properties/Semilattice.agda
  src/Algebra/Lattice/Structures.agda
  src/Algebra/Lattice/Structures/Biased.agda
  src/Algebra/Morphism/Construct/Composition.agda
  src/Algebra/Morphism/Construct/Identity.agda
  src/Algebra/Morphism/MagmaMonomorphism.agda
  src/Algebra/Morphism/RingMonomorphism.agda
  src/Algebra/Morphism/Structures.agda
  src/Algebra/Properties/BooleanAlgebra.agda
  src/Algebra/Properties/BooleanAlgebra/Expression.agda
  src/Algebra/Properties/DistributiveLattice.agda
  src/Algebra/Properties/Lattice.agda
  src/Algebra/Properties/Semilattice.agda
  src/Algebra/Structures.agda
  src/Data/Bool/Properties.agda
  src/Data/Fin/Subset.agda
  src/Data/Fin/Subset/Induction.agda
  src/Data/Fin/Subset/Properties.agda
  src/Data/Integer/Properties.agda
  src/Data/Nat/Properties.agda
  src/Data/Rational/Properties.agda
  src/Data/Rational/Unnormalised/Properties.agda
  src/Relation/Binary/Construct/NaturalOrder/Left.agda
  src/Relation/Binary/Construct/NaturalOrder/Right.agda
  src/Relation/Binary/Properties/JoinSemilattice.agda
  src/Relation/Binary/Properties/Lattice.agda
Labels: library-design, deprecation, breaking, status: ready

#1631 Move Relation.Binary.Properties.XLattice to Relation.Binary.Lattice.Properties.XLattice
  CHANGELOG.md
  src/Data/Vec/Relation/Binary/Equality/Setoid.agda
  src/Relation/Binary/Lattice/Properties/BoundedJoinSemilattice.agda
  src/Relation/Binary/Lattice/Properties/BoundedLattice.agda
  src/Relation/Binary/Lattice/Properties/BoundedMeetSemilattice.agda
  src/Relation/Binary/Lattice/Properties/DistributiveLattice.agda
  src/Relation/Binary/Lattice/Properties/JoinSemilattice.agda
  src/Relation/Binary/Lattice/Properties/Lattice.agda
  src/Relation/Binary/Lattice/Properties/MeetSemilattice.agda
  src/Relation/Binary/Properties/BoundedJoinSemilattice.agda
  src/Relation/Binary/Properties/BoundedLattice.agda
  src/Relation/Binary/Properties/BoundedMeetSemilattice.agda
  src/Relation/Binary/Properties/DistributiveLattice.agda
  src/Relation/Binary/Properties/HeytingAlgebra.agda
  src/Relation/Binary/Properties/JoinSemilattice.agda
  src/Relation/Binary/Properties/Lattice.agda
  src/Relation/Binary/Properties/MeetSemilattice.agda
Labels: deprecation, refactoring, status: ready

#1633 Create Algebra.Module summary module
  CHANGELOG.md
  src/Algebra/Module.agda
Labels: bug, enhancement, status: ready
