Repository agda/agda-stdlib, pull requests merged in 2021-02, with the labels that each got.

#1412 Add subset difference and removal operators
  CHANGELOG.md
  notes/style-guide.md
  src/Data/Fin/Subset.agda
  src/Data/Fin/Subset/Properties.agda
Labels: enhancement, refactoring, status: ready

#1411 [ re #1334 ] Some proofs in Data.Nat.Properties
  CHANGELOG.md
  src/Data/List/Relation/Unary/All/Properties.agda
  src/Data/Nat/Properties.agda
Labels: enhancement, status: ready

#1413 Add /-cancelˡ to Data.Nat.DivMod (#1165)
  CHANGELOG.md
  src/Data/Nat/DivMod.agda
  src/Data/Nat/DivMod/Core.agda
Labels: enhancement, status: ready

#1410 [ fix #1406 ] Adding some of All's properties
  CHANGELOG.md
  src/Data/List/Base.agda
  src/Data/List/Relation/Unary/All/Properties.agda
Labels: enhancement, status: ready

#1415 [ re agda/agda#5165 ] Add Main & cleanup README
  CHANGELOG.md
  README.agda
  README/IO.agda
  src/IO.agda
  src/IO/Primitive.agda
Labels: documentation, enhancement, status: ready

#1418 [ new ] pseudo random generators
  CHANGELOG.md
  src/Data/Nat/PseudoRandom/LCG.agda
Labels: enhancement, status: ready

#1417 Prove that for m n integer, if m * n is 0 then either m or n is 0
  CHANGELOG.md
  src/Data/Integer/Properties.agda
Labels: enhancement, status: ready

#1419 Added new proofs about `Pointwise` relation for `List`s
  CHANGELOG.md
  src/Data/List/Relation/Binary/Equality/Setoid.agda
  src/Data/List/Relation/Binary/Pointwise.agda
  src/Data/List/Relation/Binary/Subset/Propositional/Properties.agda
  src/Data/List/Relation/Binary/Subset/Setoid/Properties.agda
Labels: enhancement, refactoring, status: ready

#1426 Remove dependy on Data.Nat.Tactic.RingSolver in Data.Nat.DivMod
  src/Data/Nat/DivMod.agda
Labels: performance, refactoring, status: ready

#1428 Fix proof name with | in Data.Nat.Properties
  CHANGELOG.md
  src/Data/Fin/Subset/Properties.agda
  src/Data/Nat/Properties.agda
Labels: bug, naming, status: ready

#1423 Add Data.Fin.combine as inverse of quotRem, and properties thereof
  CHANGELOG.md
  src/Data/Fin/Base.agda
  src/Data/Fin/Properties.agda
Labels: enhancement, status: ready

#1390 Add min, max and absolute value for unnormalised rationals
  CHANGELOG.md
  src/Algebra/Construct/NaturalChoice/Base.agda
  src/Algebra/Construct/NaturalChoice/Max.agda
  src/Algebra/Construct/NaturalChoice/MaxOp.agda
  src/Algebra/Construct/NaturalChoice/Min.agda
  src/Algebra/Construct/NaturalChoice/MinMaxOp.agda
  src/Algebra/Construct/NaturalChoice/MinOp.agda
  src/Data/Integer/Base.agda
  src/Data/Integer/Properties.agda
  src/Data/Nat/Properties.agda
  src/Data/Rational/Unnormalised/Base.agda
  src/Data/Rational/Unnormalised/Properties.agda
  src/Relation/Binary/Bundles.agda
  src/Relation/Binary/Consequences.agda
  src/Relation/Binary/Construct/Converse.agda
  src/Relation/Binary/Properties/Poset.agda
  src/Relation/Binary/Structures.agda
Labels: enhancement, status: ready

#1365 A verified mergesort implementation
  CHANGELOG.md
  src/Data/List/Base.agda
  src/Data/List/Properties.agda
  src/Data/List/Relation/Binary/Permutation/Propositional/Properties.agda
  src/Data/List/Relation/Binary/Permutation/Setoid/Properties.agda
  src/Data/List/Relation/Unary/All/Properties.agda
  src/Data/List/Relation/Unary/Linked.agda
  src/Data/List/Relation/Unary/Linked/Properties.agda
  src/Data/List/Relation/Unary/Sorted/TotalOrder/Properties.agda
  src/Data/List/Sort.agda
  src/Data/List/Sort/Base.agda
  src/Data/List/Sort/MergeSort.agda
  src/Data/Maybe/Relation/Binary/Connected.agda
  src/Data/Maybe/Relation/Unary/All/Properties.agda
  src/Data/Nat/Induction.agda
  src/Data/Nat/PseudoRandom/LCG.agda
  src/Relation/Binary/Properties/DecTotalOrder.agda
  src/Relation/Binary/Properties/Poset.agda
  src/Relation/Binary/Properties/TotalOrder.agda
Labels: enhancement, performance, status: being-worked-on

#1433 Replaced uses of ⟶ with ⇒ in names in `Relation.Binary.Consequences`
  CHANGELOG.md
  src/Algebra/Solver/Ring/NaturalCoefficients/Default.agda
  src/Algebra/Solver/Ring/Simple.agda
  src/Data/Bin.agda
  src/Data/Bin/Properties.agda
  src/Data/List/Relation/Binary/Lex/Strict.agda
  src/Data/Nat/Binary/Properties.agda
  src/Data/Product/Relation/Binary/Lex/NonStrict.agda
  src/Data/Product/Relation/Binary/Lex/Strict.agda
  src/Data/Star/Vec.agda
  src/Data/Vec/Relation/Binary/Lex/Strict.agda
  src/Relation/Binary/Consequences.agda
  src/Relation/Binary/Construct/StrictToNonStrict.agda
  src/Relation/Binary/HeterogeneousEquality.agda
  src/Relation/Binary/Properties/TotalOrder.agda
  src/Relation/Binary/Structures.agda
Labels: naming, refactoring, status: ready
