Repository agda/agda-stdlib, pull requests merged in 2022-02, with the labels that each got.

#1705 agda-stdlib-tools: relax outdated bounds, update CI to 9.0.2 and 9.2.1
  .github/haskell-ci.patch
  .github/workflows/haskell-ci.yml
  HACKING.md
  agda-stdlib-utils.cabal
  stack-8.10.7.yaml
  stack-8.8.4.yaml
  stack-9.0.2.yaml
Labels: continuous-integration

#1701 [ new ] NonZero is decidable
  CHANGELOG.md
  src/Data/Nat/Properties.agda
Labels: enhancement, status: ready

#1702 Add injectivity proof for Data.Fin.lower₁
  CHANGELOG.md
  src/Data/Fin/Properties.agda
Labels: enhancement, status: ready

#1697 Moved `_/_` and `_%_` to `Base` modules
  CHANGELOG.md
  src/Data/Fin/Substitution.agda
  src/Data/Fin/Substitution/Example.agda
  src/Data/Fin/Substitution/Lemmas.agda
  src/Data/Integer/Base.agda
  src/Data/Integer/DivMod.agda
  src/Data/Nat/Base.agda
  src/Data/Nat/DivMod.agda
  src/Data/Rational/Base.agda
  src/Data/Rational/Unnormalised/Base.agda
  src/Data/Rational/Unnormalised/Properties.agda
Labels: library-design, refactoring, discussion, dependencies

#1710 Properties of RingWithoutOne
  CHANGELOG.md
  src/Algebra/Properties/RingWithoutOne.agda
Labels: enhancement, status: ready

#1463 Add `Data.Nat.(Factorial/Combinatorics)`
  CHANGELOG.md
  README/Data/Default.agda
  src/Data/Nat/Base.agda
  src/Data/Nat/Combinatorics.agda
  src/Data/Nat/Combinatorics/Base.agda
  src/Data/Nat/Combinatorics/Specification.agda
  src/Data/Nat/DivMod.agda
  src/Data/Nat/Divisibility.agda
  src/Data/Nat/Properties.agda
Labels: enhancement, library-design, status: ready

#1693 Codata streams by coinductive records
  CHANGELOG.md
  src/Codata/Guarded/Stream.agda
  src/Codata/Guarded/Stream/Relation/Binary/Pointwise.agda
  src/Codata/Guarded/Stream/Relation/Unary/All.agda
  src/Codata/Guarded/Stream/Relation/Unary/Any.agda
Labels: enhancement, status: ready

#1640 Add `padRight` and `truncate` to `Data.Vec`, and prove some properties
  CHANGELOG.md
  src/Data/Vec/Base.agda
  src/Data/Vec/Properties.agda
Labels: enhancement, status: ready

#1713 Add small lemma relating ∷ʳ and ++
  CHANGELOG.md
  notes/style-guide.md
  src/Data/List/Properties.agda
Labels: enhancement, status: ready

#1717 [ new ] Codata.Guarded.Stream.Properties
  CHANGELOG.md
  src/Codata/Guarded/Stream.agda
  src/Codata/Guarded/Stream/Properties.agda
  src/Codata/Guarded/Stream/Relation/Binary/Pointwise.agda
  src/Codata/Sized/Stream/Properties.agda
  src/Data/Nat/GeneralisedArithmetic.agda
  src/Data/Vec/Base.agda
Labels: enhancement, status: ready

#1714 Added boolean versions of List/Vec functions that use predicates
  CHANGELOG.md
  src/Data/List/Base.agda
  src/Data/List/Relation/Unary/Unique/DecSetoid/Properties.agda
  src/Data/Product.agda
  src/Data/String.agda
  src/Data/String/Base.agda
  src/Data/Vec/Base.agda
Labels: enhancement, status: ready

#1709 An alternative to #1698
  CHANGELOG.md
  src/Data/Fin/Base.agda
  src/Data/Fin/Induction.agda
  src/Data/Fin/Properties.agda
  src/Data/Nat/Base.agda
  src/Data/Nat/Induction.agda
  src/Data/Nat/Properties.agda
  src/Data/Nat/Properties/Core.agda
  src/Data/Vec/Properties.agda
Labels: addition, refactoring, status: ready, dependencies

#1720 Add an Inverse for `swap` in module `Data.Sum.Properties`
  CHANGELOG.md
  src/Data/Sum/Properties.agda
Labels: addition, status: ready

#1698 Lighten dependencies of `Data.Nat.Induction`
  src/Data/Nat/Induction.agda
Labels: refactoring, status: ready, discussion, dependencies
