Repository agda/agda-stdlib, pull requests merged in 2022-11, with the labels that each got.

#1873 Add missing direct products and proof 0⋆≈1 in Kleene Algebra
  CHANGELOG.md
  src/Algebra/Construct/DirectProduct.agda
  src/Algebra/Properties/KleeneAlgebra.agda
Labels: addition, status: ready

#1876 [fix] issue #1864
  src/Reflection/AST/Abstraction.agda
  src/Reflection/AST/AlphaEquality.agda
  src/Reflection/AST/Argument.agda
  src/Reflection/AST/Argument/Information.agda
  src/Reflection/AST/Argument/Modality.agda
  src/Reflection/AST/Argument/Quantity.agda
  src/Reflection/AST/Argument/Relevance.agda
  src/Reflection/AST/Argument/Visibility.agda
  src/Reflection/AST/DeBruijn.agda
  src/Reflection/AST/Definition.agda
  src/Reflection/AST/Literal.agda
  src/Reflection/AST/Meta.agda
  src/Reflection/AST/Name.agda
  src/Reflection/AST/Show.agda
  src/Reflection/AST/Term.agda
Labels: status: ready, reflection, dependencies

#1870 rationalise use of `suc (suc n)` and `suc n@(suc _)` patterns throughout; remove `2+ _` pattern
  src/Algebra/Properties/Monoid/Mult.agda
  src/Algebra/Properties/Monoid/Mult/TCOptimised.agda
  src/Data/Digit.agda
  src/Data/Integer/Properties.agda
  src/Data/List/Relation/Unary/Linked/Properties.agda
  src/Data/Nat/DivMod.agda
  src/Data/Nat/Logarithm.agda
  src/Data/Nat/Logarithm/Core.agda
  src/Data/Nat/Primality.agda
  src/Data/Nat/Properties.agda
  src/Data/Product/Nary/NonDependent.agda
  src/Data/Vec/Recursive.agda
  src/Data/Vec/Recursive/Effectful.agda
  src/Reflection/AST/Term.agda
Labels: refactoring, status: being-worked-on

#1872 Standard algebraic properties of gcd
  CHANGELOG.md
  src/Data/Integer/GCD.agda
  src/Data/Nat/GCD.agda
Labels: addition, status: ready

#1867 [fix] issue 1865 for all the raw bundles added in #1755 [coda to Issue1858/ PR 1861]
  CHANGELOG.md
  src/Data/Integer/Base.agda
  src/Data/Nat/Binary/Properties.agda
  src/Data/Nat/Properties.agda
  src/Data/Rational/Base.agda
  src/Data/Rational/Properties.agda
  src/Data/Rational/Unnormalised/Base.agda
  src/Data/Rational/Unnormalised/Properties.agda
Labels: deprecation, status: ready
