Repository agda/agda-stdlib, pull requests merged in 2022-03, with the labels that each got.

#1721 Use variables in remaining `Relation.Binary.Construct` modules
  src/Relation/Binary/Construct/Converse.agda
  src/Relation/Binary/Construct/Flip.agda
  src/Relation/Binary/Construct/Intersection.agda
  src/Relation/Binary/Construct/Union.agda
Labels: refactoring, status: ready

#1725 Use variables in `Data.Fin` and `Data.Fin.Properties`
  CHANGELOG.md
  src/Data/Fin/Base.agda
  src/Data/Fin/Permutation/Components.agda
  src/Data/Fin/Properties.agda
Labels: refactoring, breaking, status: ready

#1718 Adding apartness relations and the beginnings of local rings and fields (II)
  CHANGELOG.md
  src/Algebra/Apartness.agda
  src/Algebra/Apartness/Bundles.agda
  src/Algebra/Apartness/Properties/HeytingCommutativeRing.agda
  src/Algebra/Apartness/Structures.agda
  src/Algebra/Definitions.agda
  src/Relation/Binary/Bundles.agda
  src/Relation/Binary/Consequences.agda
  src/Relation/Binary/Definitions.agda
  src/Relation/Binary/Properties/ApartnessRelation.agda
  src/Relation/Binary/Structures.agda
Labels: addition, library-design, status: ready

#1729 Add congruence property to IsInvertibleMagma
  src/Algebra/Construct/DirectProduct.agda
  src/Algebra/Structures.agda
Labels: bug, status: ready

#1723 Reimplement `split` and `flatten` in `Data.List.NonEmpty`
  CHANGELOG.md
  src/Data/List/NonEmpty.agda
  src/Data/List/NonEmpty/Base.agda
  src/Data/List/NonEmpty/Properties.agda
  src/Data/List/NonEmpty/Relation/Unary/All.agda
Labels: library-design, refactoring, breaking, status: ready, naming

#1734 Pr#1709 bis
  src/Data/Digit.agda
  src/Data/Integer/DivMod.agda
  src/Data/Integer/Properties.agda
  src/Data/List/Properties.agda
  src/Data/List/Relation/Binary/Infix/Heterogeneous/Properties.agda
  src/Data/List/Relation/Binary/Permutation/Setoid/Properties.agda
  src/Data/List/Relation/Binary/Sublist/Setoid/Properties.agda
  src/Data/List/Relation/Binary/Subset/Propositional/Properties.agda
  src/Data/List/Relation/Unary/All/Properties.agda
  src/Data/List/Relation/Unary/Any/Properties.agda
  src/Data/List/Relation/Unary/Linked/Properties.agda
  src/Data/List/Relation/Unary/Sorted/TotalOrder/Properties.agda
  src/Data/List/Sort/MergeSort.agda
  src/Data/Rational/Properties.agda
  src/Data/Rational/Unnormalised/Properties.agda
Labels: refactoring, status: ready

#1730 Kleene algebra
  CHANGELOG.md
  src/Algebra/Bundles.agda
  src/Algebra/Construct/DirectProduct.agda
  src/Algebra/Structures.agda
Labels: addition, status: ready

#1732 [ fix #645 ] Irrelevant Data.Empty
  CHANGELOG.md
  src/Data/Empty.agda
  src/Data/Erased.agda
  src/Data/Fin/Permutation.agda
  src/Data/Irrelevant.agda
  src/Data/Refinement.agda
  src/Relation/Binary/PropositionalEquality.agda
  src/Relation/Nullary/Decidable/Core.agda
  src/Relation/Unary/Properties.agda
  src/Text/Pretty/Core.agda
Labels: refactoring, status: ready

#1727 Change field names in new function hierarchy
  CHANGELOG.md
  src/Data/List/Countdown.agda
  src/Data/List/Relation/Unary/Enumerates/Setoid/Properties.agda
  src/Data/List/Relation/Unary/Grouped/Properties.agda
  src/Data/Product/Algebra.agda
  src/Data/Sum/Algebra.agda
  src/Data/Vec/Relation/Binary/Pointwise/Extensional.agda
  src/Function/Bundles.agda
  src/Function/Construct/Composition.agda
  src/Function/Construct/Identity.agda
  src/Function/Construct/Symmetry.agda
  src/Function/Properties.agda
  src/Function/Properties/Bijection.agda
  src/Function/Properties/Inverse.agda
  src/Function/Properties/RightInverse.agda
  src/Function/Properties/Surjection.agda
  src/Function/Related.agda
  src/Function/Related/Propositional.agda
  src/Function/Structures.agda
  src/Relation/Nullary/Decidable.agda
Labels: breaking, status: ready, naming

#1739 Define Quasiring and Nearring
  CHANGELOG.md
  src/Algebra/Bundles.agda
  src/Algebra/Structures.agda
Labels: addition, status: ready

#1689 Injective functions on fin
  CHANGELOG.md
  src/Data/Fin/Properties.agda
  src/Function/Consequences.agda
Labels: addition, status: ready

#1724 Propositional equality is a partial order with respect to itself
  CHANGELOG.md
  src/Relation/Binary/Properties/Setoid.agda
  src/Relation/Binary/PropositionalEquality/Properties.agda
Labels: addition, status: ready

#1740 Morphism for RingWithoutOne like structures
  CHANGELOG.md
  src/Algebra/Bundles.agda
  src/Algebra/Morphism/Structures.agda
Labels: addition, status: ready

#1708 Update `Data.Fin.Permutation` to use new function hierarchy
  CHANGELOG.md
  src/Data/Fin/Permutation.agda
  src/Function/Properties/Inverse.agda
Labels: refactoring, breaking, status: ready

#1742 Morphism identity and composition construction for quasigroup and loop
  src/Algebra/Morphism/Construct/Composition.agda
  src/Algebra/Morphism/Construct/Identity.agda
Labels: addition, status: ready
