Repository agda/agda-stdlib, pull requests merged in 2022-09, with the labels that each got.

#1813 Fix doc typo in README.Data.List.Membership
  README/Data/List/Membership.agda
Labels: bug, documentation, status: ready

#1812 Add `flip′` to `Function.Base`
  CHANGELOG.md
  src/Function/Base.agda
Labels: addition, status: ready

#1821 [ fix #588 ] More uniform naming conventions
  CHANGELOG.md
  src/Data/Vec/Relation/Unary/All.agda
  src/Data/Vec/Relation/Unary/All/Properties.agda
  src/Data/Vec/Relation/Unary/Any.agda
  src/Data/Vec/Relation/Unary/Linked/Properties.agda
  src/Data/Vec/Relation/Unary/Unique/Setoid/Properties.agda
Labels: refactoring, breaking, status: ready

#1824 Update CHANGELOG.md to finally complete PR#1735
  CHANGELOG.md
Labels: bug, documentation

#1820 [ fix #1289 ] re-export decision procedures in Data.Nat
  CHANGELOG.md
  src/Data/Nat.agda
  src/Data/Nat/Properties.agda
Labels: addition, status: ready

#1817 Fix missing fixities in some files (#207)
  CHANGELOG.md
  src/Data/Maybe/Base.agda
  src/Function/Strict.agda
Labels: bug, status: ready

#1832 [ re #588 ] More lookup cleanup
  CHANGELOG.md
  README/Data/Tree/AVL.agda
  README/Data/Trie/NonDependent.agda
  src/Codata/Guarded/Stream.agda
  src/Codata/Guarded/Stream/Properties.agda
  src/Codata/Guarded/Stream/Relation/Binary/Pointwise.agda
  src/Codata/Guarded/Stream/Relation/Unary/Any.agda
  src/Codata/Musical/Colist/Base.agda
  src/Codata/Musical/Colist/Relation/Unary/Any/Properties.agda
  src/Codata/Musical/Covec.agda
  src/Codata/Musical/Stream.agda
  src/Codata/Sized/Colist.agda
  src/Codata/Sized/Colist/Properties.agda
  src/Codata/Sized/Covec.agda
  src/Codata/Sized/Stream.agda
  src/Codata/Sized/Stream/Properties.agda
  src/Data/Fin/Induction.agda
  src/Data/Star/Environment.agda
  src/Data/Star/Pointer.agda
  src/Data/Star/Vec.agda
  src/Data/Tree/AVL.agda
  src/Data/Tree/AVL/Indexed.agda
  src/Data/Tree/AVL/IndexedMap.agda
  src/Data/Tree/AVL/Map.agda
  src/Data/Tree/AVL/NonEmpty.agda
  src/Data/Trie.agda
  src/Data/Trie/NonEmpty.agda
  src/Data/Vec/Recursive.agda
  src/Data/Vec/Relation/Unary/All/Properties.agda
  src/Data/Vec/Relation/Unary/Linked/Properties.agda
  src/Data/Vec/Relation/Unary/Unique/Setoid/Properties.agda
  src/Tactic/RingSolver.agda
  src/Tactic/RingSolver/Core/NatSet.agda
  tests/data/trie/Main.agda
Labels: refactoring, breaking, status: ready

#1811 Remove remaining map-with-∈ names
  CHANGELOG.md
  src/Data/List/Relation/Binary/Subset/Propositional/Properties.agda
  src/Data/List/Relation/Unary/Any/Properties.agda
Labels: deprecation, status: ready

#1834 Support for GHC 9.4
  agda-stdlib-utils.cabal
Labels: status: ready, admin

#1822 Resolves issue #509 and resolves issue #626
  CHANGELOG.md
  src/Codata/Guarded/Stream/Properties.agda
  src/Codata/Sized/Colist/Properties.agda
  src/Codata/Sized/Covec/Properties.agda
  src/Codata/Sized/Delay/Properties.agda
  src/Codata/Sized/M/Properties.agda
  src/Codata/Sized/Stream/Properties.agda
  src/Data/Fin/Properties.agda
  src/Data/Fin/Substitution/List.agda
  src/Data/List/NonEmpty/Properties.agda
  src/Data/List/Properties.agda
  src/Data/List/Relation/Binary/Suffix/Heterogeneous/Properties.agda
  src/Data/List/Relation/Unary/All/Properties.agda
  src/Data/List/Zipper/Properties.agda
  src/Data/Maybe/Properties.agda
  src/Data/Sum/Properties.agda
  src/Data/Tree/Binary/Zipper/Properties.agda
  src/Data/Tree/Rose/Properties.agda
  src/Data/Vec/Functional/Properties.agda
  src/Data/Vec/Properties.agda
  src/Data/Vec/Recursive/Properties.agda
  src/Data/Vec/Relation/Binary/Equality/Setoid.agda
Labels: status: ready

#1819 [ fix #693 ] Change the definition of FreeMonad
  CHANGELOG.md
  README/Data/Container/FreeMonad.agda
  src/Data/Container/FreeMonad.agda
Labels: status: ready

#1823 Make Cancellative be more consistent in whole library
  CHANGELOG.md
  src/Algebra/Consequences/Setoid.agda
  src/Algebra/Definitions.agda
  src/Algebra/Morphism/MagmaMonomorphism.agda
  src/Algebra/Properties/CancellativeCommutativeSemiring.agda
  src/Algebra/Properties/Group.agda
  src/Algebra/Properties/Quasigroup.agda
  src/Data/Fin/Properties.agda
  src/Data/Integer/Properties.agda
  src/Data/List/Properties.agda
  src/Data/Nat/Binary/Properties.agda
  src/Data/Nat/Binary/Subtraction.agda
  src/Data/Nat/DivMod.agda
  src/Data/Nat/DivMod/Core.agda
  src/Data/Nat/Divisibility.agda
  src/Data/Nat/GCD/Lemmas.agda
  src/Data/Nat/Properties.agda
  src/Data/Sign/Properties.agda
  src/Relation/Binary/HeterogeneousEquality/Quotients/Examples.agda
Labels: refactoring, breaking, status: ready
