Repository agda/agda-stdlib, pull requests merged in 2022-05, with the labels that each got.

#1758 [ doc ] update installation instructions to 1.7.1
  notes/installation-guide.md
Labels: documentation

#1762 List.Permutation: simplify ++-comm proofs
  src/Data/List/Relation/Binary/Permutation/Propositional/Properties.agda
  src/Data/List/Relation/Binary/Permutation/Setoid/Properties.agda
Labels: refactoring, status: ready

#1764 Try to improve reduction behaviour of rationals using Andreas's suggestion
  CHANGELOG.md
  src/Data/Rational/Base.agda
  src/Data/Rational/Properties.agda
  src/Data/Rational/Unnormalised/Base.agda
  src/Data/Rational/Unnormalised/Properties.agda
Labels: breaking, status: ready, performance

#1768 [ fix #1765 ] Specialise re-exported constructors
  CHANGELOG.md
  src/Data/List/Relation/Ternary/Appending.agda
  src/Data/List/Relation/Ternary/Appending/Properties.agda
  src/Data/List/Relation/Ternary/Appending/Propositional.agda
  src/Data/List/Relation/Ternary/Appending/Setoid.agda
  tests/data/appending/Main.agda
  tests/data/appending/TakeWhile.agda
  tests/data/appending/appending.agda-lib
  tests/data/appending/expected
  tests/data/appending/input
  tests/data/appending/run
  tests/runtests.agda
Labels: bug, status: ready

#1775 [ ci ] bump version numbers
  .github/workflows/ci-ubuntu.yml
Labels: continuous-integration

#1776 [ ci ] add ~/.cabal/share to cache
  .github/workflows/ci-ubuntu.yml
Labels: continuous-integration
