Repository agda/agda-stdlib, pull requests merged in 2022-01, with the labels that each got.

#1660 Add new exponentiation operator to `Data.Integer` (fixes #490)
  CHANGELOG.md
  README/Tactic/RingSolver.agda
  src/Algebra/Definitions/RawSemiring.agda
  src/Algebra/Properties/Semiring/Exp/TCOptimised.agda
  src/Algebra/Properties/Semiring/Exp/TailRecursiveOptimised.agda
  src/Data/Integer/Base.agda
  src/Data/Integer/Properties.agda
Labels: enhancement, status: ready

#1672 [fixes issue #602 for vectors] add lemma `xs≮[] : ∀ {n} (xs : Vec A n) → ¬ xs < []`
  CHANGELOG.md
  src/Data/Vec/Relation/Binary/Lex/Strict.agda
Labels: enhancement, status: ready

#1677 Add a difference operator for predicates
  CHANGELOG.md
  src/Relation/Unary.agda
Labels: enhancement, status: ready

#1674 Improve definition of `Prime` and add Euclid's lemma
  CHANGELOG.md
  src/Data/Nat/Coprimality.agda
  src/Data/Nat/Divisibility.agda
  src/Data/Nat/GCD.agda
  src/Data/Nat/Primality.agda
  src/Data/Nat/Properties.agda
Labels: enhancement, refactoring, breaking, status: ready

#1675 Add properties about unary predicates
  CHANGELOG.md
  src/Relation/Unary/Algebra.agda
  src/Relation/Unary/Polymorphic/Properties.agda
  src/Relation/Unary/Properties.agda
  src/Relation/Unary/Relation/Binary/Equality.agda
  src/Relation/Unary/Relation/Binary/Subset.agda
Labels: enhancement, status: ready

#1673 Modernise `Data.Vec(.Properties)`
  CHANGELOG.md
  src/Data/Vec/Base.agda
  src/Data/Vec/Properties.agda
Labels: enhancement, refactoring, status: ready

#1680 Move definitions from Algebra.Core to Algebra.Module.Core
  CHANGELOG.md
  src/Algebra/Core.agda
  src/Algebra/Module.agda
  src/Algebra/Module/Bundles.agda
  src/Algebra/Module/Consequences.agda
  src/Algebra/Module/Core.agda
  src/Algebra/Module/Definitions.agda
  src/Algebra/Module/Definitions/Bi.agda
  src/Algebra/Module/Definitions/Left.agda
  src/Algebra/Module/Definitions/Right.agda
  src/Algebra/Module/Morphism/Definitions.agda
  src/Algebra/Module/Structures.agda
  src/Algebra/Module/Structures/Biased.agda
Labels: refactoring, breaking, status: ready

#1681 Renamed Tactic.Rewrite to Tactic.Cong
  CHANGELOG.md
  README/Tactic/Cong.agda
  src/Tactic/Cong.agda
Labels: refactoring, status: ready

#1682 Switch nonZero Nat destructors to instance arguments
  CHANGELOG.md
  src/Data/Nat/Base.agda
  src/Data/Nat/DivMod.agda
  src/Data/Nat/GCD.agda
  src/Data/Nat/Properties.agda
  src/Data/Rational/Base.agda
  src/Data/Rational/Properties.agda
  src/System/Clock.agda
Labels: refactoring, breaking, status: ready

#1684 Remove duplication in Ring-like structures
  CHANGELOG.md
  src/Algebra/Construct/DirectProduct.agda
  src/Algebra/Construct/Subst/Equality.agda
  src/Algebra/Lattice/Properties/BooleanAlgebra.agda
  src/Algebra/Morphism/RingMonomorphism.agda
  src/Algebra/Structures.agda
  src/Algebra/Structures/Biased.agda
  src/Data/Bool/Properties.agda
  src/Data/Integer/Properties.agda
  src/Data/Nat/Binary/Properties.agda
  src/Data/Nat/Properties.agda
  src/Data/Product/Algebra.agda
  src/Data/Rational/Unnormalised/Properties.agda
  src/Relation/Unary/Algebra.agda
Labels: library-design, refactoring, breaking, discussion

#1685 Minor fixes `#1649` ,` #1523` , and `#1651`
  .gitignore
  src/Data/Nat/Tactic/RingSolver.agda
  src/Reflection/Term.agda
Labels: status: ready, admin

#1690 Define Rng
  CHANGELOG.md
  src/Algebra/Bundles.agda
  src/Algebra/Structures.agda
Labels: enhancement, status: ready

#1691 Add ∈⇒∣product
  CHANGELOG.md
  src/Data/List/Properties.agda
Labels: enhancement, status: ready

#1683 Organise `Reflection` subfolder
  CHANGELOG.md
  GenerateEverything.hs
  src/Data/Fin/Reflection.agda
  src/Data/List/Reflection.agda
  src/Data/Nat/Reflection.agda
  src/Data/Vec/Reflection.agda
  src/Reflection.agda
  src/Reflection/AST.agda
  src/Reflection/AST/Abstraction.agda
  src/Reflection/AST/AlphaEquality.agda
  src/Reflection/AST/Argument.agda
  src/Reflection/AST/Argument/Information.agda
  src/Reflection/AST/Argument/Modality.agda
  src/Reflection/AST/Argument/Quantity.agda
  src/Reflection/AST/Argument/Relevance.agda
  src/Reflection/AST/Argument/Visibility.agda
  src/Reflection/AST/DeBruijn.agda
  src/Reflection/AST/Definition.agda
  src/Reflection/AST/Instances.agda
  src/Reflection/AST/Literal.agda
  src/Reflection/AST/Meta.agda
  src/Reflection/AST/Name.agda
  src/Reflection/AST/Pattern.agda
  src/Reflection/AST/Show.agda
  src/Reflection/AST/Term.agda
  src/Reflection/AST/Traversal.agda
  src/Reflection/AST/Universe.agda
  src/Reflection/AnnotatedAST.agda
  src/Reflection/AnnotatedAST/Free.agda
  src/Reflection/TCM.agda
  src/Reflection/TCM/Categorical.agda
  src/Reflection/TCM/Format.agda
  src/Reflection/TCM/Instances.agda
  src/Reflection/TCM/Syntax.agda
  src/Reflection/TypeChecking/MonadSyntax.agda
  src/Tactic/Cong.agda
  src/Tactic/MonoidSolver.agda
  src/Tactic/RingSolver.agda
  tests/show/reflection/Main.agda
Labels: refactoring, breaking, status: ready

#1679 Add prove of injectivity to Data.Fin.combine
  CHANGELOG.md
  src/Data/Fin/Properties.agda
Labels: enhancement, status: ready

#1692 Add missing instance to quasigroup and loop.
  src/Algebra/Bundles.agda
  src/Algebra/Structures.agda
Labels: enhancement, status: ready

#1696 add properties of nonempty list
  CHANGELOG.md
  src/Data/List/NonEmpty/Base.agda
  src/Data/List/NonEmpty/Properties.agda
Labels: enhancement, status: ready

#1700 Minor fixes to quasigroup
  src/Algebra/Bundles.agda
  src/Algebra/Structures.agda
Labels: refactoring, status: ready

#1704 [ re #1380 ] small doc correction in Induction.agda
  src/Induction.agda
Labels: bug, documentation
