Repository agda/agda-stdlib, pull requests merged in 2023-02, with the labels that each got.

#1916 fixes #1437, supersedes #1836
  CHANGELOG.md
  src/Data/Rational/Properties.agda
  src/Data/Rational/Unnormalised/Properties.agda
Labels: bug, breaking, status: ready, naming

#1922 two whitespace violations
  CHANGELOG/v1.7.2.md
  src/Data/List/Membership/Setoid/Properties.agda
Labels: status: ready, cosmetic

#1913 punchOut preserves ordering
  CHANGELOG.md
  src/Data/Fin/Properties.agda
Labels: addition, status: ready

#1910 opposite of a `Ring` [clean version of pr #1900]
  CHANGELOG.md
  src/Algebra/Construct/Flip/Op.agda
Labels: addition, low-hanging-fruit, status: ready

#1920 Wellfounded proof for sum relations
  CHANGELOG.md
  src/Data/Sum/Relation/Binary/LeftOrder.agda
  src/Data/Sum/Relation/Binary/Pointwise.agda
Labels: addition, status: ready

#1932 agda-stdlib-utils: drop GHC < 8.6, modernise .cabal file, update CI
  .github/haskell-ci.patch
  .github/workflows/haskell-ci.yml
  HACKING.md
  agda-stdlib-utils.cabal
  cabal.haskell-ci
Labels: continuous-integration

#1902 initial+terminal algebras
  CHANGELOG.md
  src/Algebra/Construct/Initial.agda
  src/Algebra/Construct/Terminal.agda
  src/Algebra/Construct/Zero.agda
  src/Algebra/Module/Construct/Zero.agda
  src/Data/Unit.agda
  src/Data/Unit/Base.agda
Labels: deprecation, refactoring, status: being-worked-on, dependencies

#1914 `SelfInverse` operations on `Algebra`s and their properties
  CHANGELOG.md
  src/Algebra/Consequences/Base.agda
  src/Algebra/Consequences/Setoid.agda
  src/Algebra/Definitions.agda
  src/Data/Parity/Properties.agda
  src/Data/Sign/Properties.agda
Labels: addition, low-hanging-fruit, library-design, refactoring, status: being-worked-on, discussion

#1924 Wellfounded proof for vec lexicographic order
  CHANGELOG.md
  src/Data/Vec/Relation/Binary/Lex/Strict.agda
Labels: addition, status: ready

#1927 binomial lemmas for *-commuting elements in a `Semiring`
  CHANGELOG.md
  src/Algebra/Properties/Monoid/Mult.agda
  src/Algebra/Properties/Monoid/Sum.agda
  src/Algebra/Properties/Semiring/Exp.agda
  src/Algebra/Properties/Semiring/Mult.agda
Labels: addition, refactoring, status: ready
