Repository agda/agda-stdlib, pull requests merged in 2023-12, with the labels that each got.

#2224 Fix deprecated modules
  .github/workflows/ci-ubuntu.yml
  GenerateEverything.hs
  src/Algebra/Operations/Semiring.agda
  src/Algebra/Properties/BooleanAlgebra.agda
  src/Algebra/Properties/DistributiveLattice.agda
  src/Data/Fin/Substitution/Example.agda
Labels: bug, continuous-integration, deprecation

#2225 Final admin changes for v2.0 release
  .github/workflows/ci-ubuntu.yml
  CHANGELOG.md
  CITATION.cff
  LICENCE
  doc/installation-guide.md
Labels: upstream, admin

#2227 Setup for v2.1
  CHANGELOG.md
  CHANGELOG/v2.0.md
  doc/release-guide.txt
Labels: admin

#2190 Added tabulate+<
  CHANGELOG.md
  src/Data/List/Relation/Unary/AllPairs/Properties.agda
Labels: addition

#2222 Added pointwise and catmaybe in Lists
  CHANGELOG.md
  src/Data/List/Relation/Unary/All/Properties.agda
  src/Data/List/Relation/Unary/AllPairs/Properties.agda
  src/Data/Maybe/Relation/Binary/Pointwise.agda
Labels: addition

#2182 [fixes #1711] Refactoring `Data.Nat.Divisibility` and `Data.Nat.DivMod`
  CHANGELOG.md
  src/Data/Digit.agda
  src/Data/Fin/Properties.agda
  src/Data/Nat/Coprimality.agda
  src/Data/Nat/DivMod.agda
  src/Data/Nat/Divisibility.agda
  src/Data/Nat/Divisibility/Core.agda
  src/Data/Nat/Properties.agda
  src/Data/Rational/Properties.agda
Labels: addition, library-design, deprecation, refactoring

#2233 [fixes #2232]
  doc/release-guide.txt
  standard-library.agda-lib
Labels: bug, admin

#2208 Add `map` to `Data.String.Base`
  CHANGELOG.md
  src/Data/String/Base.agda
  src/Data/Tree/Rose/Show.agda
  src/IO.agda
  src/Text/Printf/Generic.agda
Labels: addition

#2238 fixes issue #2237
  CHANGELOG.md
  src/Data/Nat/Divisibility.agda
  src/Data/Nat/Primality.agda
Labels: bug, naming
