Repository agda/agda-stdlib, pull requests merged in 2023-07, with the labels that each got.

#2011 Simplify `Data.Sum` and leftover `Data.List` imports
  README/Case.agda
  README/Data/Container/FreeMonad.agda
  README/Design/Decidability.agda
  README/Design/Hierarchies.agda
  README/Nary.agda
  src/Algebra/Construct/Flip/Op.agda
  src/Algebra/Construct/NaturalChoice/Min.agda
  src/Algebra/Construct/Subst/Equality.agda
  src/Algebra/Lattice/Construct/Subst/Equality.agda
  src/Algebra/Module/Definitions/Left.agda
  src/Algebra/Module/Definitions/Right.agda
  src/Data/Container/Indexed/Combinator.agda
  src/Data/List/Relation/Unary/Enumerates/Setoid.agda
  src/Data/List/Relation/Unary/Enumerates/Setoid/Properties.agda
  src/Data/List/Relation/Unary/First.agda
  src/Data/List/Relation/Unary/Grouped.agda
  src/Data/List/Relation/Unary/Grouped/Properties.agda
  src/Data/List/Relation/Unary/Unique/DecSetoid/Properties.agda
  src/Data/Nat/Binary/Subtraction.agda
  src/Data/Nat/Combinatorics/Specification.agda
  src/Data/Nat/InfinitelyOften.agda
  src/Data/Tree/AVL/Indexed/Relation/Unary/Any/Properties.agda
  src/Data/Tree/AVL/Map/Membership/Propositional.agda
  src/Data/Tree/AVL/Map/Membership/Propositional/Properties.agda
  src/Data/Vec/Relation/Binary/Lex/Core.agda
  src/Effect/Monad/Error/Transformer.agda
  src/Reflection/External.agda
  src/Relation/Nullary/Universe.agda
  src/Relation/Unary/Algebra.agda
Labels: refactoring, status: ready

#2025 refine import of Data.Nat.Show
  src/Data/Fin/Show.agda
  src/Data/Integer.agda
  src/System/Clock.agda
  src/System/Console/ANSI.agda
  src/Test/Golden.agda
  src/Text/Printf.agda
Labels: refactoring, status: ready

#2014 Simplify more `Data.product` imports
  src/Codata/Guarded/Stream/Properties.agda
  src/Codata/Guarded/Stream/Relation/Unary/All.agda
  src/Codata/Musical/Covec.agda
  src/Codata/Sized/Colist.agda
  src/Codata/Sized/Colist/Properties.agda
  src/Codata/Sized/M/Bisimilarity.agda
  src/Codata/Sized/M/Properties.agda
  src/Codata/Sized/Stream/Effectful.agda
  src/Codata/Sized/Stream/Properties.agda
  src/Data/AVL/IndexedMap.agda
  src/Data/Char/Properties.agda
  src/Data/Digit/Properties.agda
  src/Data/Fin/Induction.agda
  src/Data/Fin/Permutation.agda
  src/Data/Fin/Permutation/Components.agda
  src/Data/Fin/Permutation/Transposition/List.agda
  src/Data/Integer/Properties.agda
  src/Data/List/Extrema/Core.agda
  src/Data/List/Extrema/Nat.agda
  src/Data/List/Fresh/Properties.agda
  src/Data/List/Fresh/Relation/Unary/All.agda
  src/Data/List/Fresh/Relation/Unary/All/Properties.agda
  src/Data/List/Fresh/Relation/Unary/Any/Properties.agda
  src/Data/List/Nary/NonDependent.agda
  src/Data/List/NonEmpty/Effectful.agda
  src/Data/List/Relation/Binary/Disjoint/Setoid.agda
  src/Data/List/Relation/Binary/Disjoint/Setoid/Properties.agda
  src/Data/List/Relation/Binary/Lex/Strict.agda
  src/Data/List/Relation/Binary/Permutation/Propositional/Properties.agda
  src/Data/List/Relation/Binary/Prefix/Heterogeneous/Properties.agda
Labels: refactoring, status: ready

#2027 Bump stdlib and agda version in installation guide
  notes/installation-guide.md
Labels: status: ready, admin

#2013 Reconciling `Data.Nat.Divisibility.Core._∣_` and `Algebra.Definitions.RawMagma._∣_`
  CHANGELOG.md
  src/Data/Nat/Coprimality.agda
  src/Data/Nat/DivMod.agda
  src/Data/Nat/Divisibility.agda
  src/Data/Nat/Divisibility/Core.agda
  src/Data/Nat/GCD.agda
  src/Data/Nat/Primality.agda
Labels: low-hanging-fruit, library-design, refactoring, status: ready, discussion, cosmetic

#2034 Simplify more `Relation.Binary` imports
  src/Algebra/Properties/Monoid/Sum.agda
  src/Data/AVL/Map.agda
  src/Data/AVL/NonEmpty.agda
  src/Data/AVL/Sets.agda
  src/Data/AVL/Value.agda
  src/Data/Container/Morphism/Properties.agda
  src/Data/Container/Relation/Binary/Equality/Setoid.agda
  src/Data/Container/Relation/Binary/Pointwise.agda
  src/Data/Container/Relation/Unary/Any/Properties.agda
  src/Data/Fin/Permutation.agda
  src/Data/Integer/Coprimality.agda
  src/Data/List/Extrema/Core.agda
  src/Data/List/Fresh/Membership/Setoid/Properties.agda
  src/Data/List/Fresh/Relation/Unary/All.agda
  src/Data/List/Fresh/Relation/Unary/All/Properties.agda
  src/Data/List/Fresh/Relation/Unary/Any.agda
  src/Data/List/Fresh/Relation/Unary/Any/Properties.agda
  src/Data/List/Membership/Propositional/Properties.agda
  src/Data/List/Relation/Binary/Permutation/Setoid/Properties.agda
  src/Data/List/Relation/Binary/Prefix/Heterogeneous.agda
  src/Data/List/Relation/Binary/Sublist/DecPropositional/Solver.agda
  src/Data/List/Relation/Binary/Sublist/DecSetoid/Solver.agda
  src/Data/List/Relation/Binary/Sublist/Heterogeneous/Core.agda
  src/Data/List/Relation/Binary/Sublist/Heterogeneous/Solver.agda
  src/Data/List/Relation/Binary/Sublist/Setoid.agda
  src/Data/List/Relation/Binary/Subset/Propositional/Properties.agda
  src/Data/List/Relation/Ternary/Appending.agda
  src/Data/List/Relation/Ternary/Appending/Properties.agda
  src/Data/List/Relation/Ternary/Appending/Setoid.agda
  src/Data/List/Relation/Ternary/Appending/Setoid/Properties.agda
  src/Data/List/Relation/Ternary/Interleaving/Setoid.agda
  src/Data/List/Relation/Ternary/Interleaving/Setoid/Properties.agda
  src/Data/Tree/AVL.agda
  src/Data/Trie/NonEmpty.agda
  src/Data/Vec/Membership/DecPropositional.agda
  src/Data/Vec/Relation/Binary/Equality/DecSetoid.agda
  src/Data/Vec/Relation/Unary/All/Properties.agda
  src/Relation/Binary/Indexed/Homogeneous/Definitions.agda
  src/Relation/Nullary/Decidable.agda
Labels: refactoring, status: ready, dependencies

#2026 Rename and deprecate `excluded-middle`
  CHANGELOG.md
  src/Axiom/DoubleNegationElimination.agda
  src/Codata/Musical/Colist.agda
  src/Data/List/Membership/Propositional/Properties.agda
  src/Effect/Monad/Partiality.agda
  src/Relation/Nullary/Decidable/Core.agda
  src/Relation/Nullary/Negation.agda
Labels: refactoring, status: ready

#2016 simplified `String` import in stdl
  README/Data/List/Relation/Binary/Subset.agda
  README/Data/Tree/AVL.agda
  README/Data/Trie/NonDependent.agda
  README/Function/Reasoning.agda
  README/IO.agda
  src/Data/Rational.agda
  src/Reflection/AST/Abstraction.agda
  src/Reflection/AST/Literal.agda
  src/Reflection/AST/Show.agda
  src/Reflection/AST/Term.agda
  src/Reflection/AST/Traversal.agda
  src/Test/Golden.agda
  src/Text/Tabular/List.agda
Labels: refactoring, status: ready, dependencies

#1156 Strict inverses
  CHANGELOG.md
  src/Algebra/Consequences/Setoid.agda
  src/Algebra/Lattice/Morphism/Construct/Composition.agda
  src/Algebra/Lattice/Morphism/Construct/Identity.agda
  src/Algebra/Lattice/Morphism/Structures.agda
  src/Algebra/Module/Morphism/Construct/Composition.agda
  src/Algebra/Module/Morphism/Construct/Identity.agda
  src/Algebra/Module/Morphism/Structures.agda
  src/Algebra/Morphism/Consequences.agda
  src/Algebra/Morphism/Construct/Composition.agda
  src/Algebra/Morphism/Construct/Identity.agda
  src/Algebra/Morphism/Structures.agda
  src/Data/Fin/Permutation.agda
  src/Data/Fin/Properties.agda
  src/Data/List/Relation/Binary/Sublist/Heterogeneous/Properties.agda
  src/Data/List/Relation/Unary/Enumerates/Setoid/Properties.agda
  src/Data/Nat/Binary/Properties.agda
  src/Data/Nat/Binary/Subtraction.agda
  src/Data/Parity/Properties.agda
  src/Data/Product/Algebra.agda
  src/Data/Sum/Algebra.agda
  src/Data/Vec/N-ary.agda
  src/Data/Vec/Recursive.agda
  src/Function/Bundles.agda
  src/Function/Consequences.agda
  src/Function/Consequences/Propositional.agda
  src/Function/Construct/Composition.agda
  src/Function/Construct/Identity.agda
  src/Function/Construct/Symmetry.agda
  src/Function/Definitions.agda
  src/Function/Definitions/Core1.agda
  src/Function/Definitions/Core2.agda
  src/Function/Properties.agda
  src/Function/Properties/Bijection.agda
  src/Function/Properties/Inverse.agda
  src/Function/Properties/RightInverse.agda
  src/Function/Properties/Surjection.agda
  src/Function/Related.agda
  src/Function/Structures.agda
  src/Relation/Binary/Morphism/Construct/Composition.agda
  src/Relation/Binary/Morphism/Construct/Identity.agda
Labels: addition, status: ready, discussion

#1986 functions `take/drop/head -map-commute` added to stdl Data.List.Properties
  CHANGELOG.md
  src/Data/List/Properties.agda
Labels: addition, status: ready

#2018 Simplified `Vec` import in stdl
  README/Data/Tree/AVL.agda
  src/Data/Nat/Binary/Subtraction.agda
  src/Data/Vec/Bounded.agda
  src/Data/Vec/Functional/Properties.agda
  src/Data/Vec/Membership/Propositional/Properties.agda
  src/Data/Vec/Relation/Binary/Lex/Core.agda
  src/Data/Vec/Relation/Binary/Lex/NonStrict.agda
  src/Data/Vec/Relation/Unary/Any/Properties.agda
  src/Tactic/RingSolver/Core/Polynomial/Homomorphism/Addition.agda
  src/Tactic/RingSolver/Core/Polynomial/Homomorphism/Exponentiation.agda
  src/Tactic/RingSolver/Core/Polynomial/Homomorphism/Multiplication.agda
  src/Tactic/RingSolver/Core/Polynomial/Homomorphism/Negation.agda
  src/Tactic/RingSolver/Core/Polynomial/Semantics.agda
  src/Tactic/RingSolver/NonReflective.agda
Labels: refactoring, status: ready, dependencies
