Repository agda/agda-stdlib, pull requests merged in 2023-08, with the labels that each got.

#1959 Added Unnormalised Rational Field Structure
  CHANGELOG.md
  src/Data/Rational/Unnormalised/Properties.agda
Labels: addition, status: ready

#2044 move just a few more things over to new Function hierarchy.
  src/Data/List/Relation/Binary/Pointwise.agda
  src/Data/List/Relation/Unary/All/Properties.agda
  src/Data/Vec/Properties.agda
  src/Data/Vec/Recursive/Properties.agda
Labels: refactoring, breaking, status: ready

#1968 Added properties of Heyting Commutative Ring
  CHANGELOG.md
  src/Algebra/Apartness/Properties/HeytingCommutativeRing.agda
  src/Algebra/Properties/CommutativeMonoid.agda
Labels: addition, status: ready

#2035 Add more properties for `xor`
  CHANGELOG.md
  src/Data/Bool/Properties.agda
Labels: addition, status: ready

#2020 Additional lemmas about lists and vectors
  CHANGELOG.md
  src/Data/List/Membership/Setoid/Properties.agda
  src/Data/List/Properties.agda
  src/Data/Vec/Membership/Propositional/Properties.agda
  src/Data/Vec/Properties.agda
Labels: addition, status: ready

#2062 removed redundant `import`s from `Data.Bool.Base` in `Data.List.NonEmpty.Base`
  src/Data/List/NonEmpty/Base.agda
Labels: status: ready, dependencies

#2061 tidying up `Data.String`
  src/Data/String.agda
Labels: refactoring, status: ready

#2043 Add `drop-drop` in `Data.List.Properties`
  CHANGELOG.md
  src/Codata/Guarded/Stream/Properties.agda
  src/Codata/Sized/Colist/Properties.agda
  src/Data/List/Properties.agda
Labels: addition, status: ready

#2060 fixes #2046
  CHANGELOG.md
  src/Data/Bool/Properties.agda
Labels: low-hanging-fruit, deprecation, status: ready, naming, cosmetic

#2042 Add `find`, `findIndex`, and `findIndices` for `Data.List`
  CHANGELOG.md
  src/Data/List/Base.agda
  src/Data/List/Membership/Setoid/Properties.agda
  src/Data/List/Relation/Binary/Subset/Setoid/Properties.agda
  src/Data/List/Relation/Unary/Any/Properties.agda
  src/Function/Base.agda
Labels: addition, status: being-worked-on
