Repository agda/agda-stdlib, pull requests merged in 2023-10, with the labels that each got.

#2116 Add new fixities
  CHANGELOG.md
  README/Design/Fixity.agda
  src/Data/Container/Relation/Binary/Pointwise.agda
  src/Data/Nat/Combinatorics.agda
  src/Data/Nat/Combinatorics/Base.agda
  src/Data/Nat/Combinatorics/Specification.agda
  src/Data/Refinement.agda
  src/Data/Tree/AVL/Value.agda
  src/Effect/Monad/Partiality.agda
  src/Effect/Monad/Partiality/All.agda
  src/Effect/Monad/Predicate.agda
  src/Foreign/Haskell/Pair.agda
  src/Function/Construct/Composition.agda
  src/Reflection/AST/DeBruijn.agda
  src/Reflection/AST/Traversal.agda
  src/Reflection/AnnotatedAST.agda
  src/Relation/Binary/Construct/Composition.agda
  src/Relation/Binary/HeterogeneousEquality/Quotients/Examples.agda
  src/Relation/Binary/Indexed/Heterogeneous/Construct/At.agda
  src/Relation/Binary/Indexed/Homogeneous/Construct/At.agda
  src/Relation/Unary/Indexed.agda
  src/Relation/Unary/PredicateTransformer.agda
  src/Relation/Unary/Properties.agda
  src/Tactic/RingSolver.agda
  src/Tactic/RingSolver/Core/Expression.agda
  src/Text/Regex/Derivative/Brzozowski.agda
  src/Text/Regex/Properties.agda
  src/Text/Regex/String/Unsafe.agda
Labels: addition, status: ready

#2093 Adds `setoid` export to `Algebra.Bundles.SemiringWithoutOne` (possible solution to #1917)
  src/Algebra/Bundles.agda
  src/Algebra/Structures.agda
Labels: status: ready, dependencies

#2111 Ob #453: added `Dense` relations and `DenseLinearOrder`
  CHANGELOG.md
  src/Data/Rational/Properties.agda
  src/Data/Rational/Unnormalised/Properties.agda
  src/Data/Tree/AVL/Indexed/WithK.agda
  src/Data/Tree/AVL/NonEmpty/Propositional.agda
  src/Relation/Binary/Bundles.agda
  src/Relation/Binary/Definitions.agda
  src/Relation/Binary/Structures.agda
Labels: addition, low-hanging-fruit, status: ready

#2118 Rectifies the negated equality symbol in `Data.Rational.Unnormalised.*`
  CHANGELOG.md
  src/Data/Rational/Base.agda
  src/Data/Rational/Properties.agda
  src/Data/Rational/Unnormalised/Base.agda
  src/Data/Rational/Unnormalised/Properties.agda
Labels: low-hanging-fruit, deprecation, status: ready, naming

#2049 Sync insert, remove, and update functionalities for `List` and `Vec`
  CHANGELOG.md
  src/Algebra/Properties/CommutativeMonoid/Sum.agda
  src/Algebra/Properties/Semiring/Binomial.agda
  src/Data/List/Base.agda
  src/Data/List/Properties.agda
  src/Data/List/Relation/Unary/All/Properties.agda
  src/Data/List/Relation/Unary/Any.agda
  src/Data/Vec/Base.agda
  src/Data/Vec/Functional.agda
  src/Data/Vec/Functional/Properties.agda
  src/Data/Vec/Properties.agda
Labels: refactoring, breaking, status: ready, naming

#1948 Redefines `Data.Nat.Base._≤″_`
  CHANGELOG.md
  src/Data/Nat/Base.agda
  src/Data/Nat/Properties.agda
Labels: low-hanging-fruit, library-design, deprecation, refactoring, breaking, status: ready, discussion

#2051 Sync `iterate` and `replicate` for `List` and `Vec`
  CHANGELOG.md
  src/Codata/Guarded/Stream/Properties.agda
  src/Data/List/Base.agda
  src/Data/List/Properties.agda
  src/Data/Vec/Base.agda
  src/Data/Vec/Properties.agda
Labels: addition, status: ready

#2084 Changes explicit argument `y` to implicit in `Induction.WellFounded.WfRec`
  CHANGELOG.md
  README/Data/Nat/Induction.agda
  src/Codata/Musical/Colist/Infinite-merge.agda
  src/Data/Bool/Properties.agda
  src/Data/Digit.agda
  src/Data/Fin/Induction.agda
  src/Data/Graph/Acyclic.agda
  src/Data/List/Relation/Binary/Permutation/Setoid/Properties.agda
  src/Data/List/Sort/MergeSort.agda
  src/Data/Nat/DivMod.agda
  src/Data/Nat/GCD.agda
  src/Data/Nat/Induction.agda
  src/Data/Nat/Logarithm/Core.agda
  src/Data/Nat/Properties.agda
  src/Data/Product/Relation/Binary/Lex/Strict.agda
  src/Data/Vec/Relation/Binary/Lex/Strict.agda
  src/Induction/WellFounded.agda
  src/Relation/Binary/Construct/Closure/Transitive.agda
  src/Relation/Binary/Construct/On.agda
  src/Relation/Binary/Rewriting.agda
  src/Tactic/RingSolver/Core/Polynomial/Base.agda
  src/Tactic/RingSolver/Core/Polynomial/Homomorphism/Multiplication.agda
  src/Tactic/RingSolver/Core/Polynomial/Homomorphism/Negation.agda
Labels: library-design, refactoring, breaking, status: being-worked-on

#2067 Add (propositional) equational reasoning combinators for vectors
  CHANGELOG.md
  README.agda
  README/Data.agda
  README/Data/Vec/Relation/Binary/Equality/Cast.agda
  src/Data/Vec/Base.agda
  src/Data/Vec/Properties.agda
  src/Data/Vec/Relation/Binary/Equality/Cast.agda
Labels: addition, status: ready

#2089 Strict and non-strict transitive property names
  CHANGELOG.md
  src/Data/Integer/Properties.agda
  src/Data/List/Relation/Binary/Permutation/Setoid/Properties.agda
  src/Data/Nat/Coprimality.agda
  src/Data/Nat/DivMod.agda
  src/Data/Nat/DivMod/Core.agda
  src/Data/Nat/Properties.agda
  src/Relation/Binary/Definitions.agda
Labels: low-hanging-fruit, deprecation, refactoring, status: ready, naming, cosmetic

#2122 Re-export numeric subclass instances
  src/Data/Integer/Base.agda
  src/Data/Rational/Base.agda
  src/Data/Rational/Unnormalised/Base.agda
Labels: bug, status: ready, instances

#2119 Added Irreflexivity and Asymmetry of WellFounded Relations
  CHANGELOG.md
  src/Induction/WellFounded.agda
Labels: addition, status: ready

#2121 Fix argument order of composition operators
  CHANGELOG.md
  src/Data/Fin/Permutation.agda
  src/Function/Construct/Composition.agda
  src/Function/Properties/Inverse.agda
  src/Function/Related/Propositional.agda
Labels: bug, status: ready

#2120 Make size parameter on 'replicate' explicit
  CHANGELOG.md
  src/Algebra/Properties/Monoid/Sum.agda
  src/Algebra/Solver/CommutativeMonoid.agda
  src/Algebra/Solver/IdempotentCommutativeMonoid.agda
  src/Codata/Guarded/Stream/Properties.agda
  src/Codata/Sized/Stream/Properties.agda
  src/Data/Fin/Subset.agda
  src/Data/String.agda
  src/Data/Vec/Base.agda
  src/Data/Vec/Bounded/Base.agda
  src/Data/Vec/Effectful.agda
  src/Data/Vec/Effectful/Transformer.agda
  src/Data/Vec/Functional.agda
  src/Data/Vec/Functional/Relation/Binary/Pointwise/Properties.agda
  src/Data/Vec/Functional/Relation/Unary/All/Properties.agda
  src/Data/Vec/Properties.agda
  src/Data/Vec/Recursive.agda
  src/Data/Vec/Relation/Binary/Equality/Setoid.agda
Labels: refactoring, breaking, status: ready

#2131 [fixes #2130] Moving `Properties.HeytingAlgebra` from `Relation.Binary` to `Relation.Binary.Lattice`
  CHANGELOG.md
  src/Relation/Binary/Lattice/Properties/HeytingAlgebra.agda
  src/Relation/Binary/Properties/HeytingAlgebra.agda
Labels: bug, low-hanging-fruit, deprecation, status: ready

#2128 [fixes #2127] Fixes #1930 `import` bug
  README.agda
  README/Inspect.agda
Labels: bug, low-hanging-fruit, deprecation, status: ready

#2095 [fixes #1214] Add negated ordering relation symbols systematically to `Relation.Binary.*`
  CHANGELOG.md
  src/Data/List/Sort/MergeSort.agda
  src/Relation/Binary/Bundles.agda
  src/Relation/Binary/Properties/DecTotalOrder.agda
  src/Relation/Binary/Properties/Poset.agda
  src/Relation/Binary/Properties/StrictPartialOrder.agda
  src/Relation/Binary/Properties/StrictTotalOrder.agda
  src/Relation/Binary/Properties/TotalOrder.agda
Labels: addition, library-design, deprecation, refactoring, breaking, status: ready, discussion, dependencies

#2000 Refactoring (inversion) properties of `_<_` on `Nat`, plus consequences
  CHANGELOG.md
  src/Data/Digit/Properties.agda
  src/Data/Fin/Base.agda
  src/Data/Fin/Properties.agda
  src/Data/Integer/Properties.agda
  src/Data/List/Properties.agda
  src/Data/List/Relation/Unary/Linked/Properties.agda
  src/Data/Nat.agda
  src/Data/Nat/Base.agda
  src/Data/Nat/Binary/Properties.agda
  src/Data/Nat/DivMod.agda
  src/Data/Nat/DivMod/WithK.agda
  src/Data/Nat/Properties.agda
  src/Data/Nat/Properties/Core.agda
  src/Data/Nat/Show/Properties.agda
  src/Data/Vec/Base.agda
  src/Data/Vec/Bounded/Base.agda
  src/Data/Vec/Properties.agda
  src/Data/Vec/Relation/Unary/Linked/Properties.agda
Labels: addition, refactoring, status: ready, regression

#2134 Bump CI tests to Agda-2.6.4
  .github/workflows/ci-ubuntu.yml
Labels: upstream, status: ready

#2133 Remove `Algebra.Ordered`
  CHANGELOG.md
  src/Algebra/Ordered.agda
  src/Algebra/Ordered/Bundles.agda
  src/Algebra/Ordered/Structures.agda
  src/Relation/Binary/Lattice/Properties/BoundedJoinSemilattice.agda
  src/Relation/Binary/Lattice/Properties/JoinSemilattice.agda
  src/Relation/Binary/Lattice/Properties/MeetSemilattice.agda
Labels: library-design, status: ready

#2139 [ fix ] missing name in LICENCE file
  LICENCE
Labels: documentation, status: ready

#2141 release v1.7.3
  CHANGELOG.md
  CHANGELOG/v1.7.2.md
  CITATION.cff
  README.agda
  agda-stdlib-utils.cabal
  notes/installation-guide.md
  src/Data/Star/Decoration.agda
  src/Data/Star/Pointer.agda
  src/Effect/Applicative.agda
  src/Effect/Applicative/Indexed.agda
  src/Effect/Applicative/Predicate.agda
  src/Effect/Comonad.agda
  src/Effect/Functor.agda
  src/Effect/Functor/Indexed.agda
  src/Effect/Functor/Predicate.agda
  src/Effect/Monad.agda
  src/Effect/Monad/Continuation.agda
  src/Effect/Monad/Indexed.agda
  src/Effect/Monad/Partiality.agda
  src/Effect/Monad/Partiality/All.agda
  src/Effect/Monad/Partiality/Instances.agda
  src/Effect/Monad/Predicate.agda
  src/Effect/Monad/Reader.agda
  src/Effect/Monad/State.agda
  src/IO/Primitive.agda
  src/Reflection/Annotated.agda
  standard-library.agda-lib
Labels: release

#1972 Update blockOnMeta → blockTC
  CHANGELOG.md
  src/Reflection/TCM.agda
Labels: upstream, status: ready

#2137 Change definition of `IsStrictTotalOrder`
  CHANGELOG.md
  src/Data/Bool/Properties.agda
  src/Data/Char/Properties.agda
  src/Data/Fin/Properties.agda
  src/Data/Integer/Properties.agda
  src/Data/List/Relation/Binary/Lex/Strict.agda
  src/Data/Nat/Binary/Properties.agda
  src/Data/Nat/Properties.agda
  src/Data/Product/Relation/Binary/Lex/Strict.agda
  src/Data/Rational/Properties.agda
  src/Data/Rational/Unnormalised/Properties.agda
  src/Data/Sum/Relation/Binary/LeftOrder.agda
  src/Data/Vec/Relation/Binary/Lex/Strict.agda
  src/Induction/WellFounded.agda
  src/Relation/Binary.agda
  src/Relation/Binary/Bundles.agda
  src/Relation/Binary/Construct/Add/Infimum/Strict.agda
  src/Relation/Binary/Construct/Add/Supremum/Strict.agda
  src/Relation/Binary/Construct/Flip/EqAndOrd.agda
  src/Relation/Binary/Construct/Flip/Ord.agda
  src/Relation/Binary/Construct/NonStrictToStrict.agda
  src/Relation/Binary/Construct/On.agda
  src/Relation/Binary/Morphism/OrderMonomorphism.agda
  src/Relation/Binary/Structures.agda
  src/Relation/Binary/Structures/Biased.agda
Labels: library-design, refactoring, breaking, status: ready

#2144 Add `_⟨$⟩_` operator for Function bundle
  CHANGELOG.md
  src/Function/Bundles.agda
Labels: addition, status: ready

#2147 [ fix #2086 ] new www deploy strategy
  .github/workflows/ci-ubuntu.yml
  travis/agda-logo.svg
  travis/landing-bottom.html
  travis/landing-top.html
  travis/landing.sh
Labels: continuous-integration, documentation, status: ready

#2151 [ admin ] fix sorting logic
  travis/landing.sh
Labels: bug, continuous-integration, documentation, status: ready

#1898 Add commutative law to modules
  CHANGELOG.md
  src/Algebra/Module/Construct/DirectProduct.agda
  src/Algebra/Module/Construct/TensorUnit.agda
  src/Algebra/Module/Definitions.agda
  src/Algebra/Module/Definitions/Bi/Simultaneous.agda
  src/Algebra/Module/Structures.agda
  src/Algebra/Module/Structures/Biased.agda
Labels: refactoring, breaking, status: ready

#2158 Fixes typos identified in #2154
  CHANGELOG.md
  src/Function/Bundles.agda
Labels: bug, low-hanging-fruit, cosmetic

#2157 Tackles #2124 as regards renaming `case_return_of_`
  CHANGELOG.md
  README/Case.agda
  src/Function/Base.agda
Labels: low-hanging-fruit, deprecation, status: ready, naming, cosmetic

#2159 Move ≡-Reasoning from Core to Properties and implement using syntax
  CHANGELOG.md
  src/Codata/Guarded/Stream/Properties.agda
  src/Codata/Musical/Colist/Infinite-merge.agda
  src/Codata/Sized/Stream/Properties.agda
  src/Data/Fin/Relation/Unary/Top.agda
  src/Data/Fin/Substitution/Lemmas.agda
  src/Data/List/Countdown.agda
  src/Data/List/Relation/Binary/Sublist/Propositional/Example/UniqueBoundVariables.agda
  src/Data/List/Relation/Ternary/Interleaving/Properties.agda
  src/Data/List/Relation/Unary/Any/Properties.agda
  src/Data/Nat/Coprimality.agda
  src/Data/Nat/GCD.agda
  src/Data/Nat/LCM.agda
  src/Data/String/Unsafe.agda
  src/Data/Vec/Bounded/Base.agda
  src/Data/Vec/Recursive/Properties.agda
  src/Data/Vec/Relation/Binary/Equality/Cast.agda
  src/Effect/Applicative/Indexed.agda
  src/Function/Related/TypeIsomorphisms.agda
  src/Relation/Binary/PropositionalEquality/Core.agda
  src/Relation/Binary/PropositionalEquality/Properties.agda
  src/Relation/Binary/Reasoning/Syntax.agda
Labels: refactoring, breaking, status: ready

#2163 Add consistent deprecation warnings to old function hierarchy
  CHANGELOG.md
  src/Data/Product/Function/Dependent/Setoid.agda
  src/Function/Bijection.agda
  src/Function/Construct/Constant.agda
  src/Function/Equality.agda
  src/Function/Equivalence.agda
  src/Function/Injection.agda
  src/Function/Inverse.agda
  src/Function/LeftInverse.agda
  src/Function/Properties/Equivalence.agda
  src/Function/Properties/Injection.agda
  src/Function/Properties/Surjection.agda
  src/Function/Surjection.agda
Labels: deprecation, status: ready

#2164 Restore 'return' as an alias for 'pure'
  CHANGELOG.md
  src/Effect/Applicative.agda
  src/IO/Primitive.agda
Labels: refactoring, status: ready

#2161 [ fix #2153 ] Properly re-export specialised combinators
  CHANGELOG.md
  src/Data/List/Membership/Setoid.agda
Labels: bug, status: ready

#2054 Connect `LeftInverse` with (`Split`)`Surjection`
  CHANGELOG.md
  src/Function/Bundles.agda
  src/Function/Structures.agda
Labels: addition, status: ready

#2162 Added remaining flipped and negated relations to binary relation bundles
  CHANGELOG.md
  README/Design/Hierarchies.agda
  src/Algebra/Lattice/Properties/Semilattice.agda
  src/Data/Product/Relation/Binary/Lex/Strict.agda
  src/Relation/Binary/Bundles.agda
  src/Relation/Binary/Properties/DecTotalOrder.agda
  src/Relation/Binary/Properties/Poset.agda
  src/Relation/Binary/Properties/TotalOrder.agda
  src/Relation/Binary/Structures.agda
Labels: addition, refactoring, status: ready

#2165 Tidy up CHANGELOG in preparation for release candidate
  CHANGELOG.md
Labels: refactoring, status: ready, admin

#2167 v2.0-rc1 spellcheck
  CHANGELOG.md
Labels: refactoring, documentation, status: ready

#2176 [fixes #2175]
  README.agda
Labels: bug, documentation, status: ready

#2173 [fixes #2171]
  src/Data/Nat/Properties.agda
Labels: bug, deprecation, status: ready
