Repository agda/agda-stdlib, pull requests merged in 2023-05, with the labels that each got.

#1946 Restore deleted `*.Categorical.*` as deprecated modules
  CHANGELOG.md
  GenerateEverything.hs
  src/Codata/Sized/Colist/Categorical.agda
  src/Codata/Sized/Covec/Categorical.agda
  src/Codata/Sized/Delay/Categorical.agda
  src/Codata/Sized/Stream/Categorical.agda
  src/Data/List/Categorical.agda
  src/Data/List/Categorical/Transformer.agda
  src/Data/List/NonEmpty/Categorical.agda
  src/Data/List/NonEmpty/Categorical/Transformer.agda
  src/Data/Maybe/Categorical.agda
  src/Data/Maybe/Categorical/Transformer.agda
  src/Data/Product/Categorical/Examples.agda
  src/Data/Product/Categorical/Left.agda
  src/Data/Product/Categorical/Left/Base.agda
  src/Data/Product/Categorical/Right.agda
  src/Data/Product/Categorical/Right/Base.agda
  src/Data/Sum/Categorical/Examples.agda
  src/Data/Sum/Categorical/Left.agda
  src/Data/Sum/Categorical/Left/Transformer.agda
  src/Data/Sum/Categorical/Right.agda
  src/Data/Sum/Categorical/Right/Transformer.agda
  src/Data/These/Categorical/Left.agda
  src/Data/These/Categorical/Left/Base.agda
  src/Data/These/Categorical/Right.agda
  src/Data/These/Categorical/Right/Base.agda
  src/Data/Vec/Categorical.agda
  src/Data/Vec/Categorical/Transformer.agda
  src/Data/Vec/Recursive/Categorical.agda
  src/Function/Identity/Categorical.agda
  src/IO/Categorical.agda
  src/Reflection/TCM/Categorical.agda
Labels: addition, low-hanging-fruit, library-design, deprecation, status: ready

#1964 cosmetic: two whitespace violations
  src/Data/List/Properties.agda
  src/Data/Nat/Combinatorics.agda
Labels: low-hanging-fruit, cosmetic

#1955 Add citation file to repo
  CITATION.cff
  notes/release-guide.txt
Labels: addition, documentation, status: ready

#1949 Monus `_∸_` is right adjoint to addition `_+_` across usual `_≤_` preorder
  CHANGELOG.md
  src/Data/Nat/Properties.agda
Labels: addition, low-hanging-fruit, library-design, status: ready, discussion

#1965 Added reverse permutation
  CHANGELOG.md
  src/Data/List/Relation/Binary/Permutation/Propositional/Properties.agda
Labels: addition, status: ready

#1930 Another attempt at deprecation of `inspect`
  CHANGELOG.md
  README.agda
  README/Inspect.agda
  src/Codata/Sized/Colist/Properties.agda
  src/Data/Fin/Properties.agda
  src/Data/List/Properties.agda
  src/Data/List/Relation/Binary/Permutation/Propositional/Properties.agda
  src/Data/List/Relation/Binary/Permutation/Setoid/Properties.agda
  src/Data/List/Relation/Unary/Any/Properties.agda
  src/Data/Rational/Properties.agda
  src/Data/Vec/Relation/Unary/Any/Properties.agda
  src/Relation/Binary/PropositionalEquality.agda
Labels: low-hanging-fruit, deprecation, refactoring
