Repository agda/agda-stdlib, pull requests merged in 2023-09, with the labels that each got.

#2078 spellchecked `CHANGELOG`
  CHANGELOG.md
Labels: low-hanging-fruit, status: ready, admin

#2077 addresses #2075: removes symmetry assumption from lexicographic well-foundedness
  CHANGELOG.md
  src/Data/Product/Relation/Binary/Lex/Strict.agda
  src/Data/Vec/Relation/Binary/Lex/Strict.agda
  src/Induction/WellFounded.agda
Labels: addition, low-hanging-fruit, refactoring, breaking, status: ready, dependencies

#1967 Make sure RawRing defines rawRingWithoutOne
  src/Algebra/Bundles/Raw.agda
Labels: bug, status: ready

#1909 Direct products and minor fixes
  CHANGELOG.md
  src/Algebra/Bundles.agda
  src/Algebra/Construct/DirectProduct.agda
  src/Algebra/Structures.agda
Labels: addition, status: ready

#2072 Refine imports in `Reflection.AST`
  src/Reflection/AST/Abstraction.agda
  src/Reflection/AST/AlphaEquality.agda
  src/Reflection/AST/Argument.agda
  src/Reflection/AST/Argument/Information.agda
  src/Reflection/AST/Argument/Modality.agda
  src/Reflection/AST/Argument/Quantity.agda
  src/Reflection/AST/Argument/Relevance.agda
  src/Reflection/AST/Argument/Visibility.agda
  src/Reflection/AST/Definition.agda
  src/Reflection/AST/Literal.agda
  src/Reflection/AST/Meta.agda
  src/Reflection/AST/Name.agda
  src/Reflection/AST/Show.agda
  src/Reflection/AST/Term.agda
  src/Reflection/AST/Traversal.agda
Labels: refactoring, dependencies

#2041 Add some `_∷ʳ_` properties to `Data.Vec.Properties`
  CHANGELOG.md
  src/Data/List/Properties.agda
  src/Data/Vec/Base.agda
  src/Data/Vec/Properties.agda
Labels: addition, breaking, status: being-worked-on

#2079 Monadic join
  CHANGELOG.md
  src/Data/List/Effectful.agda
  src/Data/Maybe/Effectful.agda
  src/Data/Sum/Effectful/Left.agda
  src/Data/Sum/Effectful/Right.agda
  src/Data/Vec.agda
  src/Data/Vec/Base.agda
  src/Data/Vec/Effectful.agda
  src/Data/Vec/Effectful/Transformer.agda
  src/Effect/Monad.agda
  src/Effect/Monad/Identity.agda
  src/Effect/Monad/Partiality.agda
  src/Effect/Monad/Reader.agda
  src/Effect/Monad/State.agda
  src/Effect/Monad/Writer.agda
Labels: addition, low-hanging-fruit, status: ready, naming

#2047 Move `≡-setoid` to `Function.Indexed.Relation.Binary.Equality`
  src/Data/List/Relation/Binary/Permutation/Propositional/Properties.agda
  src/Data/List/Relation/Binary/Permutation/Setoid/Properties.agda
  src/Data/Product/Function/Dependent/Propositional.agda
  src/Data/Product/Function/Dependent/Setoid/WithK.agda
  src/Data/Product/Function/NonDependent/Propositional.agda
  src/Data/Product/Relation/Binary/Pointwise/NonDependent.agda
  src/Function/Endomorphism/Setoid.agda
  src/Function/Indexed/Relation/Binary/Equality.agda
  src/Relation/Binary/PropositionalEquality.agda
  src/Relation/Nullary/Universe.agda
Labels: addition, status: ready

#2085 making (more) arguments implicit: #602, #1648, #1672 revisited
  CHANGELOG.md
  src/Data/List/Relation/Binary/Lex/Strict.agda
  src/Data/Vec/Relation/Binary/Lex/Strict.agda
Labels: low-hanging-fruit, breaking, status: ready

#2082 `WellFounded` proofs for transitive closure
  CHANGELOG.md
  src/Relation/Binary/Construct/Closure/Transitive.agda
Labels: addition, low-hanging-fruit, refactoring, status: ready, naming

#2045 Add properties of vector selectors, `Vec.reverse`, `Vec._++_` and `Vec.fromList`
  CHANGELOG.md
  src/Data/Fin/Properties.agda
  src/Data/Vec/Properties.agda
Labels: addition, status: ready

#2094 fixes #1990
  CHANGELOG.md
Labels: low-hanging-fruit, documentation, admin, cosmetic

#2056 improve implementation of splitAt, take and drop.
  CHANGELOG.md
  src/Data/Vec/Base.agda
  src/Data/Vec/Properties.agda
  src/Data/Vec/Relation/Unary/All/Properties.agda
  src/Data/Vec/Relation/Unary/AllPairs/Properties.agda
Labels: refactoring, status: ready

#1923 a recursive view of `Fin n`
  CHANGELOG.md
  README/Data/Fin/Relation/Unary/Top.agda
  src/Data/Fin/Properties.agda
  src/Data/Fin/Relation/Unary/Top.agda
Labels: addition, refactoring, status: ready, discussion

#2104 Fix typo and whitespace violation
  src/Data/Container/FreeMonad.agda
  src/Data/Vec/Base.agda
Labels: status: ready, cosmetic

#1936 Kleene Algebra morphism with composition and identity construct
  CHANGELOG.md
  src/Algebra/Bundles.agda
  src/Algebra/Bundles/Raw.agda
  src/Algebra/Morphism/Construct/Composition.agda
  src/Algebra/Morphism/Construct/Identity.agda
  src/Algebra/Morphism/Structures.agda
Labels: addition, low-hanging-fruit, status: ready

#1944 Added foldr of permutation of Commutative Monoid
  CHANGELOG.md
  src/Data/List/Relation/Binary/Permutation/Setoid/Properties.agda
Labels: addition, status: ready

#1470 Add `begin-irrefl` reasoning combinator
  CHANGELOG.md
  src/Data/Integer/Properties.agda
  src/Data/List/Relation/Unary/Any/Properties.agda
  src/Data/Nat/Binary/Properties.agda
  src/Data/Nat/Properties.agda
  src/Data/Rational/Properties.agda
  src/Data/Rational/Unnormalised/Properties.agda
  src/Data/Tree/AVL/Indexed/Relation/Unary/Any/Properties.agda
  src/Data/Vec/Relation/Binary/Lex/NonStrict.agda
  src/Data/Vec/Relation/Binary/Lex/Strict.agda
  src/Relation/Binary/Reasoning/Base/Triple.agda
  src/Relation/Binary/Reasoning/PartialOrder.agda
  src/Relation/Binary/Reasoning/StrictPartialOrder.agda
Labels: addition, refactoring, breaking, status: ready, naming

#2101 Refactor some lookup and truncation lemmas
  CHANGELOG.md
  src/Data/Fin/Base.agda
  src/Data/Fin/Properties.agda
  src/Data/Vec/Base.agda
  src/Data/Vec/Properties.agda
Labels: addition, refactoring, status: ready

#2109 Add style-guide note about local suffix
  notes/style-guide.md
Labels: addition, documentation, status: ready

#2108 Weakened pre-conditions of grouped map lemmas
  CHANGELOG.md
  src/Data/List/Relation/Unary/All/Properties.agda
  src/Data/List/Relation/Unary/Grouped/Properties.agda
Labels: refactoring, breaking, status: ready

#2107 Un-deprecate inspect idiom
  CHANGELOG.md
  src/Relation/Binary/PropositionalEquality.agda
Labels: deprecation, status: ready

#1928 Proofs of the Binomial Theorem for `(Commutative)Semiring` [supersedes #1287]
  CHANGELOG.md
  src/Algebra/Properties/CommutativeSemiring/Binomial.agda
  src/Algebra/Properties/Monoid/Sum.agda
  src/Algebra/Properties/Semiring/Binomial.agda
Labels: addition, refactoring, status: ready

#2110 Modernise `Relation.Nullary` code
  CHANGELOG.md
  src/Codata/Musical/Colist.agda
  src/Data/Nat/InfinitelyOften.agda
  src/Relation/Nullary/Decidable.agda
  src/Relation/Nullary/Decidable/Core.agda
  src/Relation/Nullary/Negation.agda
  src/Relation/Nullary/Negation/Core.agda
  src/Relation/Nullary/Reflects.agda
  src/Relation/Nullary/Universe.agda
Labels: refactoring, status: ready
