Repository agda/agda-stdlib, pull requests merged in 2023-06, with the labels that each got.

#1973 Apartness reasoning
  CHANGELOG.md
  src/Relation/Binary/Reasoning/Base/Apartness.agda
Labels: addition, status: ready

#1953 middle four exchange law in a `Setoid`: definition and consequences
  CHANGELOG.md
  src/Algebra/Consequences/Propositional.agda
  src/Algebra/Consequences/Setoid.agda
  src/Algebra/Definitions.agda
Labels: addition, low-hanging-fruit, status: ready

#1976 add take-[] and drop-[] to stdl Data/List/Properties.agda
  CHANGELOG.md
  src/Data/List/Properties.agda
Labels: addition, status: ready

#1956 Added cong and map to vec ≋ equality
  CHANGELOG.md
  src/Data/Vec/Relation/Binary/Equality/Setoid.agda
  src/Data/Vec/Relation/Binary/Pointwise/Inductive.agda
Labels: addition, status: ready

#1991 Update CHANGELOG.md move 2 functions to section Data.List.Properties
  CHANGELOG.md
Labels: refactoring, documentation, status: ready

#1989 Fixities for `Data` and `Codata`
  CHANGELOG.md
  src/Codata/Guarded/Stream.agda
  src/Codata/Guarded/Stream/Relation/Binary/Pointwise.agda
  src/Codata/Musical/Colist.agda
  src/Codata/Musical/Colist/Bisimilarity.agda
  src/Codata/Musical/Colist/Relation/Unary/All.agda
  src/Codata/Musical/Conat.agda
  src/Codata/Sized/Colist.agda
  src/Codata/Sized/Colist/Bisimilarity.agda
  src/Codata/Sized/Conat/Properties.agda
  src/Codata/Sized/Covec.agda
  src/Codata/Sized/Covec/Bisimilarity.agda
  src/Codata/Sized/Cowriter.agda
  src/Codata/Sized/Cowriter/Bisimilarity.agda
  src/Codata/Sized/Stream.agda
  src/Codata/Sized/Stream/Bisimilarity.agda
  src/Data/Container/Core.agda
  src/Data/Container/FreeMonad.agda
  src/Data/Container/Indexed.agda
  src/Data/Float/Base.agda
  src/Data/Nat/Base.agda
  src/Data/Nat/Properties.agda
  src/Data/Rational/Unnormalised/Properties.agda
  src/Data/Tree/AVL/Map/Membership/Propositional.agda
  src/Induction/WellFounded.agda
Labels: bug, status: ready

#1950 New property merge-is-superlist
  CHANGELOG.md
  src/Data/List/Relation/Binary/Sublist/Setoid/Properties.agda
  src/Data/List/Relation/Unary/Sorted/TotalOrder/Properties.agda
Labels: addition, status: ready

#1992 Fixities for `Relation` and `Algebra`
  CHANGELOG.md
  src/Algebra/Solver/Ring.agda
  src/Relation/Binary/Bundles.agda
  src/Relation/Binary/Construct/Add/Infimum/Strict.agda
  src/Relation/Binary/Construct/Add/Point/Equality.agda
  src/Relation/Binary/Construct/Add/Supremum/NonStrict.agda
  src/Relation/Binary/Construct/Closure/Transitive.agda
  src/Relation/Binary/Construct/Intersection.agda
Labels: bug, status: ready

#1983 added new function `take-all` to stdl
  CHANGELOG.md
  src/Data/List/Properties.agda
Labels: addition, status: ready

#1984 New functions `take-drop-1` and `take-one-more` added to Data.List.Properties
  CHANGELOG.md
  src/Data/List/Properties.agda
Labels: addition, status: ready

#2006 Cut down `Function` imports
  src/Algebra/Construct/NaturalChoice/Min.agda
  src/Algebra/Morphism.agda
  src/Algebra/Ordered/Structures.agda
  src/Algebra/Solver/Ring/AlmostCommutativeRing.agda
  src/Data/Container/Combinator.agda
  src/Data/Container/Combinator/Properties.agda
  src/Data/Container/Indexed/Combinator.agda
  src/Data/Container/Indexed/FreeMonad.agda
  src/Data/Container/Indexed/WithK.agda
  src/Data/Container/Morphism.agda
  src/Data/Container/Morphism/Properties.agda
  src/Data/Container/Properties.agda
  src/Data/Container/Relation/Unary/All.agda
  src/Data/Digit/Properties.agda
  src/Data/Fin/Permutation/Transposition/List.agda
  src/Data/Fin/Substitution/Lemmas.agda
  src/Data/Fin/Substitution/List.agda
  src/Data/Float/Properties.agda
  src/Data/List/Relation/Unary/Grouped/Properties.agda
  src/Data/Nat/Binary/Subtraction.agda
  src/Data/Nat/DivMod.agda
  src/Data/Nat/Show/Properties.agda
  src/Data/Parity/Properties.agda
  src/Data/Sign/Properties.agda
  src/Data/Star/Environment.agda
  src/Data/Tree/AVL/Value.agda
  src/Data/Tree/Binary/Properties.agda
  src/Data/Trie/NonEmpty.agda
  src/Data/Vec/Effectful.agda
  src/Data/Vec/Relation/Binary/Lex/NonStrict.agda
  src/Data/Vec/Relation/Unary/AllPairs.agda
  src/Data/Vec/Relation/Unary/AllPairs/Properties.agda
  src/Function/Injection.agda
  src/Function/Metric/Nat/Bundles.agda
  src/Function/Metric/Nat/Structures.agda
  src/Function/Metric/Rational/Bundles.agda
  src/Function/Metric/Rational/Structures.agda
  src/Function/Reasoning.agda
  src/Reflection/AST/Meta.agda
  src/Reflection/AST/Name.agda
  src/Reflection/AST/Traversal.agda
  src/Reflection/External.agda
  src/Relation/Binary/OrderMorphism.agda
  src/Relation/Unary/Algebra.agda
  src/Tactic/Cong.agda
  src/Tactic/RingSolver/Core/AlmostCommutativeRing.agda
  tests/data/appending/Main.agda
  tests/data/colist/Main.agda
Labels: status: ready, dependencies

#2010 gitignore `_build` correctly
  .gitignore
Labels: status: ready, admin

#2003 Simplify `Data.Product` imports
  README/Data/Container/FreeMonad.agda
  src/Algebra/Apartness/Properties/HeytingCommutativeRing.agda
  src/Algebra/Construct/Add/Identity.agda
  src/Algebra/Construct/Flip/Op.agda
  src/Algebra/Construct/LexProduct/Inner.agda
  src/Algebra/Construct/LiftedChoice.agda
  src/Algebra/Construct/NaturalChoice/Min.agda
  src/Algebra/Construct/Subst/Equality.agda
  src/Algebra/Lattice/Morphism/Construct/Identity.agda
  src/Algebra/Lattice/Morphism/LatticeMonomorphism.agda
  src/Algebra/Lattice/Properties/BooleanAlgebra/Expression.agda
  src/Algebra/Lattice/Structures/Biased.agda
  src/Algebra/Module/Morphism/Construct/Identity.agda
  src/Algebra/Module/Structures.agda
  src/Algebra/Morphism/Consequences.agda
  src/Algebra/Morphism/Construct/Identity.agda
  src/Algebra/Morphism/MonoidMonomorphism.agda
  src/Algebra/Ordered/Structures.agda
  src/Algebra/Properties/BooleanAlgebra.agda
  src/Algebra/Properties/CommutativeMagma/Divisibility.agda
  src/Algebra/Properties/CommutativeSemigroup/Divisibility.agda
  src/Algebra/Properties/Lattice.agda
  src/Algebra/Properties/Monoid/Divisibility.agda
  src/Algebra/Properties/Semigroup/Divisibility.agda
  src/Algebra/Properties/Semiring/Divisibility.agda
  src/Algebra/Solver/CommutativeMonoid.agda
  src/Algebra/Solver/IdempotentCommutativeMonoid.agda
  src/Algebra/Solver/Ring/NaturalCoefficients.agda
Labels: refactoring, status: ready, dependencies

#2007 Simplify `Data.List` imports
  README/Data/List/Relation/Binary/Pointwise.agda
  README/Data/List/Relation/Binary/Subset.agda
  README/Data/Tree/AVL.agda
  README/Data/Trie/NonDependent.agda
  README/Tactic/RingSolver.agda
  README/Text/Regex.agda
  src/Data/Fin/Permutation/Transposition/List.agda
  src/Data/List/Countdown.agda
  src/Data/List/Relation/Binary/Sublist/Heterogeneous/Solver.agda
  src/Data/List/Relation/Unary/AllPairs/Properties.agda
  src/Data/List/Relation/Unary/Grouped.agda
  src/Data/Tree/Binary/Zipper.agda
  src/Data/Vec/Functional/Properties.agda
  src/Data/Vec/Reflection.agda
  src/Reflection/AST/Show.agda
  src/Reflection/AST/Traversal.agda
  src/Tactic/MonoidSolver.agda
  src/Tactic/RingSolver/Core/NatSet.agda
  src/Tactic/RingSolver/Core/Polynomial/Homomorphism/Addition.agda
  src/Tactic/RingSolver/Core/Polynomial/Homomorphism/Lemmas.agda
  src/Tactic/RingSolver/Core/Polynomial/Semantics.agda
  tests/data/appending/Main.agda
  tests/data/appending/TakeWhile.agda
  tests/data/list/Main.agda
  tests/data/trie/Main.agda
Labels: refactoring, status: ready, dependencies

#2008 More fixities
  CHANGELOG.md
  src/Codata/Guarded/Stream/Relation/Unary/All.agda
  src/Foreign/Haskell/List/NonEmpty.agda
  src/Function/Metric/Rational/Bundles.agda
  src/Level/Literals.agda
  src/Relation/Binary/Construct/Union.agda
  src/Relation/Binary/HeterogeneousEquality/Quotients/Examples.agda
  src/Relation/Binary/Indexed/Homogeneous/Bundles.agda
  src/Text/Regex/Search.agda
Labels: bug, status: ready
