Repository agda/agda-stdlib, pull requests merged in 2024-04, with the labels that each got.

#2335 Move pointwise equality to `.Core` module
  src/Algebra/Properties/Monoid/Sum.agda
  src/Data/List/Effectful.agda
  src/Data/List/Membership/Propositional/Properties.agda
  src/Data/List/Relation/Unary/All/Properties.agda
  src/Data/Product/Properties.agda
  src/Relation/Binary/PropositionalEquality.agda
  src/Relation/Binary/PropositionalEquality/Core.agda
Labels: refactoring, dependencies

#2344 fix warning: it was pointing to a record that did not exist.
  src/Algebra/Morphism.agda
Labels: bug, deprecation

#2334 Tighten imports
  src/Algebra/Definitions/RawMagma.agda
  src/Algebra/Structures.agda
  src/Data/List/Relation/Unary/AllPairs.agda
  src/Data/Maybe/Base.agda
  src/Data/Product/Properties.agda
  src/Function/Indexed/Relation/Binary/Equality.agda
  src/Relation/Binary/Bundles.agda
  src/Relation/Binary/PropositionalEquality/Algebra.agda
  src/Relation/Binary/Reasoning/Setoid.agda
  src/Relation/Binary/Reasoning/Syntax.agda
Labels: refactoring, dependencies

#2343 Tighten imports some more
  doc/README/Effect/Monad/Partiality.agda
  src/Algebra/Module/Construct/Idealization.agda
  src/Algebra/Properties/CommutativeMonoid.agda
  src/Data/Container/Core.agda
  src/Data/Container/Indexed.agda
  src/Data/Container/Indexed/Relation/Binary/Pointwise.agda
  src/Data/List/Properties.agda
  src/Data/List/Relation/Ternary/Appending/Setoid/Properties.agda
  src/Data/List/Relation/Unary/First/Properties.agda
  src/Data/Nat/Primality/Factorisation.agda
  src/Data/Product/Relation/Binary/Pointwise/NonDependent.agda
  src/Data/Rational/Unnormalised/Base.agda
  src/Data/Sum/Algebra.agda
  src/Data/Sum/Function/Propositional.agda
  src/Data/Unit/Polymorphic/Properties.agda
  src/Effect/Monad/Partiality.agda
  src/Function/Properties/Inverse/HalfAdjointEquivalence.agda
  src/Function/Related/TypeIsomorphisms.agda
  src/Relation/Binary/Reasoning/Base/Apartness.agda
  src/Relation/Binary/Reasoning/Base/Double.agda
  src/Relation/Binary/Reasoning/Base/Partial.agda
  src/Relation/Binary/Reasoning/Base/Triple.agda
Labels: refactoring, dependencies

#2277 [fixes #2273] Add `SuccessorSet` and associated boilerplate
  CHANGELOG.md
  src/Algebra/Bundles.agda
  src/Algebra/Bundles/Raw.agda
  src/Algebra/Morphism/Structures.agda
  src/Algebra/Structures.agda
Labels: addition

#2354 Systematise use of `Relation.Binary.Definitions.DecidableEquality`
  src/Algebra/Solver/Monoid.agda
  src/Axiom/UniquenessOfIdentityProofs.agda
  src/Data/Bool/Properties.agda
  src/Data/Char/Properties.agda
  src/Data/List/Membership/DecPropositional.agda
  src/Data/List/Membership/Propositional/Properties.agda
  src/Data/List/Relation/Binary/Equality/DecPropositional.agda
  src/Data/List/Relation/Binary/Sublist/DecPropositional.agda
  src/Data/List/Relation/Binary/Sublist/DecPropositional/Solver.agda
  src/Data/Maybe/Properties.agda
  src/Data/Nat/Binary/Properties.agda
  src/Data/Record.agda
  src/Data/String/Properties.agda
  src/Data/Sum/Properties.agda
  src/Data/These/Properties.agda
  src/Data/Unit/Polymorphic/Properties.agda
  src/Data/Unit/Properties.agda
  src/Data/Vec/Membership/DecPropositional.agda
  src/Data/Vec/Relation/Binary/Equality/DecPropositional.agda
  src/Effect/Monad/Partiality.agda
  src/Reflection/AST/Term.agda
  src/Relation/Binary/Construct/Closure/Reflexive/Properties.agda
  src/Relation/Binary/PropositionalEquality/Properties.agda
Labels: refactoring, cosmetic, dependencies

#2356 Added missing v1.7.3 CHANGELOG
  CHANGELOG/v1.7.3.md
Labels: bug, admin

#2370 Add a consequence of definition straight to IsCancellativeCommutativeSemiring
  CHANGELOG.md
  src/Algebra/Structures.agda
Labels: addition

#2368 [ new ] System.Random bindings
  CHANGELOG.md
  GenerateEverything.hs
  src/Data/Float/Base.agda
  src/Data/List/Show.agda
  src/Data/String/Base.agda
  src/Data/Vec/Bounded/Show.agda
  src/Data/Vec/Show.agda
  src/Data/Word/Base.agda
  src/System/Random.agda
  src/System/Random/Primitive.agda
  tests/runtests.agda
  tests/system/random/.gitignore
  tests/system/random/Main.agda
  tests/system/random/expected
  tests/system/random/random.agda-lib
  tests/system/random/run
Labels: addition

#2340 Another tweak to cong!
  CHANGELOG.md
  doc/README/Tactic/Cong.agda
  src/Reflection/TCM/Utilities.agda
  src/Tactic/Cong.agda
Labels: reflection, tactics, instances

#2364 Improve `Data.List.Base.unfold` (#2359; deprecate use of `with` #2123)
  src/Data/List/Base.agda
Labels: library-design, refactoring, cosmetic

#2357 [fix #2253] Deprecate `Algebra.Structures.Biased.IsRing*`
  CHANGELOG.md
  src/Algebra/Structures/Biased.agda
Labels: bug, low-hanging-fruit, deprecation

#2337 Remove uses of `Data.Nat.Solver` from a number of places
  src/Data/Digit.agda
  src/Data/Fin/Properties.agda
  src/Data/Integer/Properties.agda
  src/Data/Integer/Properties/NatLemmas.agda
  src/Data/Nat/GCD/Lemmas.agda
  src/Data/Rational/Unnormalised/Properties.agda
Labels: refactoring, dependencies

#2367 [ new ] IO buffering, and loops
  CHANGELOG.md
  GenerateEverything.hs
  doc/README/IO.agda
  src/Foreign/Haskell/Coerce.agda
  src/IO.agda
  src/IO/Base.agda
  src/IO/Finite.agda
  src/IO/Handle.agda
  src/IO/Infinite.agda
  src/IO/Primitive.agda
  src/IO/Primitive/Core.agda
  src/IO/Primitive/Handle.agda
  src/System/Clock/Primitive.agda
  src/System/Environment/Primitive.agda
  src/System/FilePath/Posix/Primitive.agda
  src/System/Process/Primitive.agda
  tests/runtests.agda
  tests/system/io/Main.agda
  tests/system/io/expected
  tests/system/io/input
  tests/system/io/io.agda-lib
  tests/system/io/run
Labels: addition

#2371 [ cleanup ] imports in the Effect.Monad modules
  src/Effect/Monad/Continuation.agda
  src/Effect/Monad/Error/Transformer.agda
  src/Effect/Monad/IO.agda
  src/Effect/Monad/Identity.agda
  src/Effect/Monad/Partiality.agda
  src/Effect/Monad/Predicate.agda
  src/Effect/Monad/Reader.agda
  src/Effect/Monad/Reader/Transformer.agda
  src/Effect/Monad/State.agda
  src/Effect/Monad/State/Transformer.agda
  src/Effect/Monad/Writer.agda
  src/Effect/Monad/Writer/Transformer.agda
Labels: dependencies

#2355 Add proofs to Data.List.Properties
  CHANGELOG.md
  src/Data/List/Properties.agda
Labels: bug, addition

#2363 A number of `with` are not really needed
  src/Algebra/Construct/LexProduct.agda
  src/Algebra/Construct/LiftedChoice.agda
  src/Algebra/Construct/NaturalChoice/MinOp.agda
  src/Codata/Sized/Cowriter.agda
  src/Data/Fin/Base.agda
  src/Data/List/Fresh.agda
  src/Data/List/Fresh/Relation/Unary/All.agda
  src/Data/List/Kleene/Base.agda
  src/Data/List/NonEmpty/Base.agda
  src/Data/List/Relation/Binary/Infix/Heterogeneous.agda
  src/Data/List/Relation/Binary/Prefix/Heterogeneous.agda
  src/Data/List/Relation/Binary/Suffix/Heterogeneous.agda
  src/Data/List/Relation/Binary/Suffix/Heterogeneous/Properties.agda
  src/Data/List/Relation/Unary/Enumerates/Setoid/Properties.agda
  src/Data/Nat/Binary/Subtraction.agda
  src/Data/Rational/Base.agda
  src/Data/Rational/Unnormalised/Base.agda
  src/Data/Star/Environment.agda
  src/Data/Star/Pointer.agda
  src/Data/Star/Vec.agda
  src/Data/String/Base.agda
  src/Data/Tree/AVL.agda
  src/Data/Vec.agda
  src/Data/Vec/Base.agda
  src/Data/Vec/Membership/Setoid.agda
  src/Relation/Binary/Construct/NaturalOrder/Left.agda
  src/Relation/Binary/Construct/NaturalOrder/Right.agda
  src/Text/Pretty/Core.agda
Labels: refactoring

#2349 [ new ] ⁻¹-anti-homo-(// | \\)
  CHANGELOG.md
  src/Algebra/Properties/AbelianGroup.agda
  src/Algebra/Properties/Group.agda
Labels: addition
