Repository agda/agda-stdlib, pull requests merged in 2024-10, with the labels that each got.

#2490 [DRY] Refactor `Data.List.Relation.Binary.Equality.Setoid` exports
  src/Data/List/Relation/Binary/Equality/DecSetoid.agda
  src/Data/List/Relation/Binary/Equality/Setoid.agda
  src/Data/List/Relation/Binary/Subset/DecSetoid.agda
Labels: library-design, refactoring

#2488 Add `(Is)DecPreorder` to `Relation.Binary.*`
  CHANGELOG.md
  src/Relation/Binary/Bundles.agda
  src/Relation/Binary/Construct/Interior/Symmetric.agda
  src/Relation/Binary/Structures.agda
Labels: addition, low-hanging-fruit

#2496 Lemmas for Positive, Negative, etc. and _+_ and _*_ for rationals
  CHANGELOG.md
  src/Data/Rational/Properties.agda
Labels: addition

#2497 Add `Relation.Nullary.Recomputable.irrelevant-recompute`
  CHANGELOG.md
  src/Relation/Nullary/Recomputable.agda
Labels: addition
