Repository agda/agda-stdlib, pull requests merged in 2024-02, with the labels that each got.

#2271 add lemma(s) about `Relation.Nullary.Decidable.Core.isYes`
  CHANGELOG.md
  src/Relation/Nullary/Decidable.agda
Labels: addition, low-hanging-fruit

#2270 additions to `style-guide`
  doc/style-guide.md
Labels: addition, style-guide

#2254 (Partial) fix for issue #1688
  CHANGELOG.md
  src/Algebra/Bundles.agda
Labels: bug, addition, library-design

#2259 Systematise relational definitions at all arities
  CHANGELOG.md
  src/Relation/Binary/Definitions.agda
  src/Relation/Nullary.agda
  src/Relation/Unary.agda
Labels: addition

#2272 lemmas about semiring structure induced by `_× x`
  CHANGELOG.md
  src/Algebra/Properties/Monoid/Mult.agda
  src/Algebra/Properties/Semiring/Binomial.agda
  src/Algebra/Properties/Semiring/Mult.agda
Labels: addition, deprecation, refactoring, cosmetic, dependencies

#2281 Qualified import of `Data.Nat` fixing #2280
  src/Algebra/Properties/Semiring/Binomial.agda
  src/Codata/Sized/Cowriter.agda
  src/Data/Char/Properties.agda
  src/Data/DifferenceNat.agda
  src/Data/DifferenceVec.agda
  src/Data/Fin.agda
  src/Data/Fin/Permutation/Components.agda
  src/Data/Fin/Properties.agda
  src/Data/Fin/Subset/Properties.agda
  src/Data/Float/Properties.agda
  src/Data/Graph/Acyclic.agda
  src/Data/Integer/Divisibility.agda
  src/Data/List/Extrema/Nat.agda
  src/Data/List/Relation/Binary/Infix/Heterogeneous/Properties.agda
  src/Data/List/Relation/Binary/Sublist/Heterogeneous/Properties.agda
  src/Data/List/Relation/Binary/Sublist/Heterogeneous/Solver.agda
  src/Data/List/Relation/Binary/Sublist/Setoid/Properties.agda
  src/Data/Nat/Binary/Properties.agda
  src/Data/Nat/Binary/Subtraction.agda
  src/Data/Rational/Base.agda
  src/Data/String.agda
  src/Data/Vec.agda
  src/Data/Vec/Functional/Properties.agda
  src/Data/Word/Properties.agda
  src/Induction/Lexicographic.agda
  src/Reflection/AST/Definition.agda
  src/Reflection/AST/Meta.agda
  src/Tactic/Cong.agda
  src/Tactic/RingSolver/Core/Polynomial/Homomorphism/Addition.agda
  src/Tactic/RingSolver/Core/Polynomial/Homomorphism/Exponentiation.agda
  src/Tactic/RingSolver/Core/Polynomial/Homomorphism/Lemmas.agda
  src/Text/Pretty.agda
  src/Text/Printf.agda
Labels: refactoring, admin, cosmetic

#2279 Fix import in `README.Data.Fin.Substitution.UntypedLambda`
  doc/README.agda
  doc/README/Data/Fin/Substitution/UntypedLambda.agda
Labels: bug, dependencies

#2282 Qualified import of reasoning modules fixing #2280
  src/Algebra/Apartness/Properties/HeytingCommutativeRing.agda
  src/Algebra/Construct/LexProduct.agda
  src/Algebra/Construct/LiftedChoice.agda
  src/Algebra/Lattice/Morphism/LatticeMonomorphism.agda
  src/Algebra/Module/Bundles.agda
  src/Algebra/Module/Consequences.agda
  src/Algebra/Morphism.agda
  src/Algebra/Morphism/Consequences.agda
  src/Algebra/Morphism/GroupMonomorphism.agda
  src/Algebra/Morphism/MagmaMonomorphism.agda
  src/Algebra/Morphism/MonoidMonomorphism.agda
  src/Algebra/Morphism/RingMonomorphism.agda
  src/Algebra/Properties/CommutativeSemigroup/Divisibility.agda
  src/Algebra/Solver/CommutativeMonoid.agda
  src/Algebra/Solver/IdempotentCommutativeMonoid.agda
  src/Codata/Musical/Colist.agda
  src/Data/Integer/Divisibility/Signed.agda
  src/Data/List/Properties.agda
  src/Data/List/Relation/Binary/BagAndSetEquality.agda
  src/Data/List/Relation/Binary/Permutation/Setoid.agda
  src/Data/List/Relation/Binary/Subset/Propositional/Properties.agda
  src/Data/List/Relation/Binary/Subset/Setoid/Properties.agda
  src/Data/Nat/Divisibility.agda
  src/Data/Rational/Unnormalised/Properties.agda
  src/Function/Properties/Bijection.agda
  src/Function/Properties/Equivalence.agda
  src/Function/Properties/Injection.agda
  src/Function/Properties/Inverse.agda
  src/Function/Properties/Surjection.agda
  src/Relation/Binary/Construct/Closure/ReflexiveTransitive/Properties.agda
  src/Relation/Binary/Construct/NaturalOrder/Left.agda
  src/Relation/Binary/Construct/NaturalOrder/Right.agda
  src/Relation/Binary/Lattice/Properties/HeytingAlgebra.agda
  src/Relation/Binary/Lattice/Properties/Lattice.agda
  src/Relation/Binary/Reasoning/Base/Apartness.agda
  src/Relation/Binary/Reasoning/Base/Double.agda
  src/Relation/Binary/Reasoning/Base/Partial.agda
  src/Relation/Binary/Reasoning/Base/Single.agda
  src/Relation/Binary/Reasoning/Base/Triple.agda
  src/Relation/Binary/Reasoning/MultiSetoid.agda
  src/Relation/Binary/Reasoning/PartialSetoid.agda
  src/Relation/Binary/Reasoning/Syntax.agda
  src/Relation/Binary/Reflection.agda
  src/Tactic/MonoidSolver.agda
Labels: refactoring

#2284 Qualified import of `Data.Product.Base` fixing #2280
  src/Algebra/Construct/Flip/Op.agda
  src/Algebra/Construct/Subst/Equality.agda
  src/Algebra/Lattice/Construct/Subst/Equality.agda
  src/Codata/Musical/Colist.agda
  src/Codata/Musical/Colist/Infinite-merge.agda
  src/Codata/Sized/Colist/Properties.agda
  src/Codata/Sized/Cowriter.agda
  src/Codata/Sized/M/Properties.agda
  src/Codata/Sized/Stream/Properties.agda
  src/Data/Container/Core.agda
  src/Data/Fin/Properties.agda
  src/Data/List/Base.agda
  src/Data/List/Membership/Propositional/Properties/Core.agda
  src/Data/List/Membership/Setoid.agda
  src/Data/List/Membership/Setoid/Properties.agda
  src/Data/List/Nary/NonDependent.agda
  src/Data/List/Properties.agda
  src/Data/List/Relation/Binary/Prefix/Heterogeneous/Properties.agda
  src/Data/List/Relation/Binary/Subset/Propositional/Properties.agda
  src/Data/List/Relation/Ternary/Interleaving.agda
  src/Data/List/Relation/Unary/All.agda
  src/Data/List/Relation/Unary/All/Properties.agda
  src/Data/List/Relation/Unary/Any.agda
  src/Data/List/Relation/Unary/Any/Properties.agda
  src/Data/List/Sort/MergeSort.agda
  src/Data/Maybe/Relation/Unary/All.agda
  src/Data/Maybe/Relation/Unary/Any.agda
  src/Data/Product/Function/Dependent/Propositional.agda
  src/Data/Product/Function/NonDependent/Setoid.agda
  src/Data/Product/Relation/Binary/Pointwise/Dependent.agda
  src/Data/Product/Relation/Binary/Pointwise/NonDependent.agda
  src/Data/Sum/Function/Setoid.agda
  src/Data/Tree/AVL/Map/Membership/Propositional/Properties.agda
  src/Data/Tree/AVL/Map/Relation/Unary/Any.agda
  src/Data/Tree/AVL/Relation/Unary/Any.agda
  src/Data/Tree/AVL/Sets.agda
  src/Data/Tree/AVL/Sets/Membership.agda
  src/Data/Tree/AVL/Sets/Membership/Properties.agda
  src/Data/Trie/NonEmpty.agda
  src/Data/Vec/Base.agda
  src/Data/Vec/N-ary.agda
  src/Data/Vec/Properties.agda
  src/Data/Vec/Recursive.agda
  src/Data/Vec/Relation/Unary/All.agda
  src/Data/Vec/Relation/Unary/All/Properties.agda
  src/Data/Vec/Relation/Unary/Any.agda
  src/Data/Vec/Relation/Unary/Any/Properties.agda
  src/Data/Vec/Relation/Unary/Linked.agda
  src/Function/Consequences.agda
  src/Function/Related/TypeIsomorphisms.agda
  src/Relation/Binary/Construct/Closure/Reflexive/Properties.agda
  src/Relation/Binary/Construct/Subst/Equality.agda
  src/Relation/Binary/Properties/Preorder.agda
  src/Relation/Nary.agda
  src/Relation/Nullary/Negation.agda
  src/Relation/Nullary/Universe.agda
Labels: refactoring

#2286 missing code endquote
  CHANGELOG.md
Labels: continuous-integration, documentation, cosmetic

#2285 `README.Data.*` manual fix for #1380
  src/Data/Bool/Solver.agda
  src/Data/Integer/Solver.agda
  src/Data/Integer/Tactic/RingSolver.agda
  src/Data/Nat/Solver.agda
Labels: documentation, admin, dependencies

#2295 Fix `sized-types` error in `README.Data.Tree.Binary`
  doc/README/Data/Tree/Binary.agda
Labels: bug, continuous-integration

#2066 Added functional vector permutation
  CHANGELOG.md
  src/Data/Vec/Functional/Relation/Binary/Permutation.agda
  src/Data/Vec/Functional/Relation/Binary/Permutation/Properties.agda
Labels: addition

#2244 Nagata's "idealization of a module" construction
  CHANGELOG.md
  src/Algebra/Module/Construct/Idealization.agda
Labels: addition, paper-based

#2290 Qualified import of `Data.Sum.Base` fixing #2280
  src/Codata/Sized/Delay.agda
  src/Data/Container/Combinator.agda
  src/Data/Container/Combinator/Properties.agda
Labels: refactoring

#2023 [ new ] associativity of Appending
  CHANGELOG.md
  src/Data/List/Relation/Binary/Pointwise/Base.agda
  src/Data/List/Relation/Ternary/Appending/Properties.agda
  src/Data/List/Relation/Ternary/Appending/Setoid/Properties.agda
  src/Relation/Binary/Properties/Setoid.agda
Labels: addition

#2071 [ new ] symmetric core of a binary relation
  CHANGELOG.md
  src/Data/Fin/Subset/Properties.agda
  src/Relation/Binary/Construct/Interior/Symmetric.agda
  src/Relation/Binary/Definitions.agda
  src/Relation/Unary/Polymorphic/Properties.agda
  src/Relation/Unary/Properties.agda
Labels: addition, naming

#2301 Refactor proofs from #2023
  CHANGELOG.md
  src/Relation/Binary/Construct/Composition.agda
  src/Relation/Binary/Properties/Setoid.agda
Labels: addition
