Repository agda/agda-stdlib, pull requests merged in 2024-09, with the labels that each got.

#2414 Add a property relating `maybe` to composition
  CHANGELOG.md
  src/Data/Maybe/Properties.agda
Labels: addition

#2470 Rename+deprecate in `Algebra.Properties.CommutativeMagma.Divisibility`
  CHANGELOG.md
  src/Algebra/Properties/CommutativeMagma/Divisibility.agda
Labels: deprecation, naming, cosmetic

#2407 Refactor `Algebra.Solver.*Monoid`
  CHANGELOG.md
  src/Algebra/Solver/CommutativeMonoid.agda
  src/Algebra/Solver/CommutativeMonoid/Normal.agda
  src/Algebra/Solver/IdempotentCommutativeMonoid.agda
  src/Algebra/Solver/IdempotentCommutativeMonoid/Normal.agda
  src/Algebra/Solver/Monoid.agda
  src/Algebra/Solver/Monoid/Expression.agda
  src/Algebra/Solver/Monoid/Normal.agda
  src/Algebra/Solver/Monoid/Solver.agda
  src/Algebra/Solver/Ring.agda
  src/Relation/Binary/Reflection.agda
  src/Tactic/RingSolver.agda
  src/Tactic/RingSolver/NonReflective.agda
Labels: refactoring, dependencies

#2473 Merge v2.1.1 into `master`
  .github/workflows/ci-ubuntu.yml
  CHANGELOG.md
  CHANGELOG/v2.1.1.md
  CITATION.cff
  doc/README.agda
  doc/installation-guide.md
  src/Reflection/AST/Definition.agda
  src/Reflection/AST/Instances.agda
  src/Reflection/AST/Show.agda
Labels: admin

#2477 fix typo in `release-guide`
  doc/release-guide.txt
Labels: cosmetic

#2474 fix `CHANGELOG` after #2418
  CHANGELOG.md
Labels: bug, documentation

#2465 Add two lemmas to `Data.List.Membership.Setoid.Properties`
  CHANGELOG.md
  src/Data/List/Membership/Setoid/Properties.agda
  src/Data/List/Relation/Unary/All/Properties.agda
  src/Data/List/Relation/Unary/All/Properties/Core.agda
Labels: addition, refactoring, dependencies

#2480 Simplify definitions/exports in `Data.List.Relation.Unary.Unique.*`
  src/Data/List/Relation/Unary/Unique/Propositional.agda
  src/Data/List/Relation/Unary/Unique/Setoid.agda
Labels: refactoring, cosmetic

#2481 Add properties/structures/bundles related to decidability for `Relation.Binary.Construct.Interior.Symmetric`
  CHANGELOG.md
  src/Relation/Binary/Construct/Interior/Symmetric.agda
Labels: addition, refactoring

#2478 fixes #2466: add equivalence proofs
  CHANGELOG.md
  src/Data/List/Membership/Setoid/Properties.agda
Labels: addition, refactoring, cosmetic

#2333 Refactor `Data.List.Relation.Binary.Permutation.*`, part I
  CHANGELOG.md
  src/Data/List/Relation/Binary/BagAndSetEquality.agda
  src/Data/List/Relation/Binary/Permutation/Homogeneous.agda
  src/Data/List/Relation/Binary/Permutation/Propositional.agda
  src/Data/List/Relation/Binary/Permutation/Propositional/Properties.agda
  src/Data/List/Relation/Binary/Permutation/Setoid.agda
  src/Data/List/Relation/Binary/Permutation/Setoid/Properties.agda
Labels: addition, refactoring

#2485 [DRY] refactor #2479
  CHANGELOG.md
  src/Data/List/Membership/Propositional/Properties.agda
Labels: addition, refactoring
