Repository agda/agda-stdlib, pull requests merged in 2024-06, with the labels that each got.

#2399 Lists: decidability of Subset+Disjoint relations
  CHANGELOG.md
  src/Data/List/Membership/DecSetoid.agda
  src/Data/List/Relation/Binary/Disjoint/DecPropositional.agda
  src/Data/List/Relation/Binary/Disjoint/DecSetoid.agda
  src/Data/List/Relation/Binary/Subset/DecPropositional.agda
  src/Data/List/Relation/Binary/Subset/DecSetoid.agda
Labels: addition

#2389 More list properties about `catMaybes/mapMaybe`
  CHANGELOG.md
  src/Data/List/Properties.agda
  src/Data/List/Relation/Binary/Permutation/Propositional/Properties.agda
  src/Data/List/Relation/Binary/Permutation/Setoid/Properties.agda
  src/Data/List/Relation/Binary/Permutation/Setoid/Properties/Maybe.agda
Labels: addition

#2373 Very dependent map
  CHANGELOG.md
  src/Data/Product.agda
  src/Data/Product/Properties/Dependent.agda
Labels: addition

#2366 Improve `Data.List.Base` (fix #2359; deprecate use of with #2123)
  src/Data/List/Base.agda
Labels: library-design, refactoring, cosmetic

#2243 Adds `Relation.Nullary.Recomputable` plus consequences
  CHANGELOG.md
  src/Axiom/UniquenessOfIdentityProofs.agda
  src/Data/Empty.agda
  src/Relation/Binary/Definitions.agda
  src/Relation/Nullary.agda
  src/Relation/Nullary/Decidable.agda
  src/Relation/Nullary/Decidable/Core.agda
  src/Relation/Nullary/Negation.agda
  src/Relation/Nullary/Negation/Core.agda
  src/Relation/Nullary/Recomputable.agda
  src/Relation/Nullary/Reflects.agda
  src/Relation/Unary.agda
Labels: addition, library-design

#2342 Port two Endomorphism submodules over to new Function hierarchy
  CHANGELOG.md
  src/Function/Endo/Propositional.agda
  src/Function/Endo/Setoid.agda
  src/Function/Endomorphism/Propositional.agda
  src/Function/Endomorphism/Setoid.agda
  src/Function/Equality.agda
Labels: addition, refactoring

#2402 Add `IsIdempotentMonoid` and `IsCommutativeBand` to `Algebra.Structures`
  CHANGELOG.md
  src/Algebra/Bundles.agda
  src/Algebra/Lattice/Bundles.agda
  src/Algebra/Lattice/Construct/Subst/Equality.agda
  src/Algebra/Lattice/Structures.agda
  src/Algebra/Structures.agda
Labels: addition, low-hanging-fruit, library-design, dependencies

#2409 Update LICENSE
  LICENCE
Labels: admin, license, cosmetic

#2405 Refactor `Data.Sum.{to|from}Dec` via move+deprecate in `Relation.Nullary.Decidable.Core`
  CHANGELOG.md
  src/Data/List/Fresh/Relation/Unary/Any.agda
  src/Data/List/Relation/Unary/Any.agda
  src/Data/List/Relation/Unary/First/Properties.agda
  src/Data/Sum.agda
  src/Data/Vec/Relation/Unary/Any.agda
  src/Relation/Binary/Construct/Closure/Reflexive/Properties.agda
  src/Relation/Nullary/Decidable/Core.agda
Labels: low-hanging-fruit, library-design, refactoring, dependencies

#2336 Implement move-via-deprecate of `decToMaybe` as per #2330
  CHANGELOG.md
  src/Algebra/Solver/CommutativeMonoid.agda
  src/Algebra/Solver/IdempotentCommutativeMonoid.agda
  src/Algebra/Solver/Monoid.agda
  src/Data/Graph/Acyclic.agda
  src/Data/List/Relation/Binary/Sublist/Heterogeneous/Solver.agda
  src/Data/Maybe/Base.agda
  src/Relation/Binary/Consequences.agda
  src/Relation/Nullary/Decidable/Core.agda
Labels: low-hanging-fruit, deprecation, refactoring, dependencies

#2413 fixes #2411
  CHANGELOG.md
  src/Data/List/Base.agda
  src/Data/List/NonEmpty/Base.agda
Labels: naming

#2412 Tidy up CHANGELOG in preparation for v2.1 release candidate
  CHANGELOG.md
  agda-stdlib-utils.cabal
Labels: refactoring, admin
