Repository agda/agda-stdlib, pull requests merged in 2024-05, with the labels that each got.

#2378 `Data.List.Base.reverse` is self adjoint wrt `Data.List.Relation.Binary.Subset.Setoid._⊆_`
  CHANGELOG.md
  src/Data/List/Membership/Setoid/Properties.agda
  src/Data/List/Properties.agda
  src/Data/List/Relation/Binary/Subset/Setoid/Properties.agda
Labels: addition, low-hanging-fruit, refactoring

#2377 fixes #2375
  CHANGELOG.md
  src/Data/List/Relation/Binary/Subset/Setoid/Properties.agda
Labels: addition, low-hanging-fruit

#2385 Add `Data.List.Relation.Binary.Sublist.Setoid` categorical properties
  CHANGELOG.md
  src/Data/List/Relation/Binary/Sublist/Heterogeneous/Properties.agda
  src/Data/List/Relation/Binary/Sublist/Propositional/Properties.agda
  src/Data/List/Relation/Binary/Sublist/Setoid/Properties.agda
Labels: addition, refactoring

#2381 Pointwise `Algebra`
  CHANGELOG.md
  src/Algebra/Construct/Pointwise.agda
Labels: addition, low-hanging-fruit

#2386 Algebra fixity
  doc/README/Design/Fixity.agda
  doc/style-guide.md
  src/Algebra/Bundles.agda
  src/Algebra/Definitions.agda
  src/Algebra/Definitions/RawMagma.agda
  src/Algebra/Module/Bundles.agda
  src/Algebra/Module/Definitions/Left.agda
  src/Algebra/Module/Definitions/Right.agda
  src/Algebra/Properties/Monoid/Divisibility.agda
  src/Algebra/Properties/Semiring/Divisibility.agda
  src/Algebra/Solver/Ring/AlmostCommutativeRing.agda
Labels: library-design, documentation

#2194 Decidable Setoid -> Apartness Relation and Rational Heyting Field
  CHANGELOG.md
  src/Algebra/Properties/Group.agda
  src/Data/Rational/Properties.agda
  src/Relation/Binary/Properties/DecSetoid.agda
  src/Relation/Binary/Properties/Setoid.agda
Labels: addition

#2398 CI bumps: ghc 9.10, action versions, Agda to 2.6.4.3
  .github/workflows/ci-ubuntu.yml
  .github/workflows/haskell-ci.yml
  agda-stdlib-utils.cabal
Labels: continuous-integration

#2395 Refactor `Data.List.Base.scan*` and their properties
  CHANGELOG.md
  src/Codata/Sized/Colist/Properties.agda
  src/Data/List.agda
  src/Data/List/Base.agda
  src/Data/List/Membership/Propositional/Properties.agda
  src/Data/List/NonEmpty/Base.agda
  src/Data/List/NonEmpty/Properties.agda
  src/Data/List/Properties.agda
  src/Data/List/Scans/Base.agda
  src/Data/List/Scans/Properties.agda
  src/Tactic/RingSolver/Core/NatSet.agda
Labels: addition, deprecation, refactoring, dependencies

#2392 `style-guide` rule for initial `private` block in modules
  doc/style-guide.md
Labels: documentation, style-guide

#2393 Add the `Setoid`-based `Monoid` on `(List, [], _++_)`
  CHANGELOG.md
  src/Data/List/Relation/Binary/Equality/Setoid/Properties.agda
Labels: addition, library-design, refactoring
