Repository agda/agda-stdlib, pull requests merged in 2024-01, with the labels that each got.

#2239 Bring back a convenient short-cut for infix Func
  CHANGELOG.md
  src/Function/Bundles.agda
Labels: addition, naming

#2241 Update `README`
  README.md
Labels: bug, documentation, admin, cubical-compatible

#2242 Update `HACKING`
  HACKING.md
Labels: library-design, documentation, dependencies

#2261 fix toList-replicate's statement about vectors
  CHANGELOG.md
  src/Data/Vec/Properties.agda
Labels: bug

#2256 Remove all external use of `less-than-or-equal` beyond `Data.Nat.*`
  src/Data/Vec/Bounded/Base.agda
Labels: low-hanging-fruit, refactoring, cosmetic

#2263 Raw modules bundles
  CHANGELOG.md
  src/Algebra/Module/Bundles.agda
  src/Algebra/Module/Bundles/Raw.agda
  src/Algebra/Module/Construct/DirectProduct.agda
  src/Algebra/Module/Construct/TensorUnit.agda
  src/Algebra/Module/Construct/Zero.agda
Labels: addition, library-design

#2265 Parametrize module morphisms by raw bundles
  CHANGELOG.md
  src/Algebra/Module/Morphism/Construct/Composition.agda
  src/Algebra/Module/Morphism/Construct/Identity.agda
  src/Algebra/Module/Morphism/ModuleHomomorphism.agda
  src/Algebra/Module/Morphism/Structures.agda
Labels: library-design, refactoring, breaking
