Repository agda/agda-stdlib, pull requests merged in 2024-03, with the labels that each got.

#2294 Qualified imports in `Data.Integer.Divisibility` fixing #2280
  CHANGELOG.md
  doc/README/Data/Integer.agda
  src/Data/Integer/Divisibility.agda
  src/Data/Integer/Divisibility/Signed.agda
  src/Data/Integer/GCD.agda
  src/Data/Integer/LCM.agda
Labels: refactoring, breaking

#2309 Style guide: guideline for `-Reasoning` module imports cf #2282
  doc/style-guide.md
Labels: documentation, style-guide

#2240 Function setoid is back.
  CHANGELOG.md
  src/Function/Relation/Binary/Setoid/Equality.agda
Labels: addition

#2308 Style guide: avoid `renaming` on qualified import cf. #2294
  doc/style-guide.md
Labels: documentation, style-guide

#2314 make `mkRawMonad` and `mkRawApplicative` universe-polymorphic
  src/Data/Product/Effectful/Left.agda
  src/Data/Product/Effectful/Right.agda
  src/Effect/Applicative.agda
  src/Effect/Monad.agda
  src/Reflection/AST/DeBruijn.agda
Labels: bug

#2316 Some properties of upTo and downFrom
  CHANGELOG.md
  src/Data/List/Properties.agda
Labels: addition

#2313 Tidy up `README` imports #2280
  doc/README/Data/Container/FreeMonad.agda
  doc/README/Data/List/Membership.agda
  doc/README/Data/List/Relation/Binary/Equality.agda
  doc/README/Data/Tree/AVL.agda
  doc/README/Data/Trie/NonDependent.agda
  doc/README/Data/Vec/Relation/Binary/Equality/Cast.agda
  doc/README/Function/Reasoning.agda
  doc/README/Tactic/Cong.agda
  doc/README/Tactic/MonoidSolver.agda
Labels: refactoring, documentation

#2296 Add unique morphisms from/to `Initial` and `Terminal` algebras
  CHANGELOG.md
  doc/style-guide.md
  src/Algebra/Construct/Initial.agda
  src/Algebra/Construct/Terminal.agda
  src/Algebra/Construct/Zero.agda
  src/Algebra/Morphism/Construct/Initial.agda
  src/Algebra/Morphism/Construct/Terminal.agda
Labels: addition

#1511 Setoid version of indexed containers.
  CHANGELOG.md
  doc/README/Data.agda
  doc/README/Data/Container/Indexed/MultiSortedAlgebraExample.agda
  doc/README/Data/Container/Indexed/VectorExample.agda
  src/Data/Container/Indexed/Core.agda
  src/Data/Container/Indexed/Relation/Binary/Equality/Setoid.agda
  src/Data/Container/Indexed/Relation/Binary/Pointwise.agda
  src/Data/Container/Indexed/Relation/Binary/Pointwise/Properties.agda
Labels: addition, documentation

#2126 'No infinite descent' for (`Acc`essible elements of) `WellFounded` relations
  CHANGELOG.md
  src/Induction/InfiniteDescent.agda
  src/Relation/Binary/Construct/Closure/Transitive.agda
  src/Relation/Unary.agda
Labels: addition, low-hanging-fruit

#2251 Add new operations (cf. `RawQuasigroup`) to `IsGroup`
  CHANGELOG.md
  src/Algebra/Properties/Group.agda
  src/Algebra/Properties/Loop.agda
  src/Algebra/Properties/Quasigroup.agda
  src/Algebra/Structures.agda
Labels: addition, refactoring

#1969 Add prime factorization and its properties
  CHANGELOG.md
  src/Data/List/Relation/Binary/Permutation/Propositional/Properties.agda
  src/Data/Nat/Primality.agda
  src/Data/Nat/Primality/Factorisation.agda
Labels: addition

#2321 Refactor `Data.List.Relation.Binary.BagAndSetEquality`
  src/Data/List/Relation/Binary/BagAndSetEquality.agda
Labels: low-hanging-fruit, refactoring, cosmetic

#2312 Tidy up functional vector permutation #2066
  CHANGELOG.md
  src/Data/Vec/Functional/Relation/Binary/Permutation.agda
  src/Data/Vec/Functional/Relation/Binary/Permutation/Properties.agda
Labels: addition, cosmetic

#2310 A tweak for the cong! tactic
  CHANGELOG.md
  doc/README/Tactic/Cong.agda
  src/Tactic/Cong.agda
Labels: addition, tactics

#2323 Simplify `Data.List.Relation.Unary.Any.Properties`: remove dependency on `List.Properties`
  src/Data/List/Membership/Propositional/Properties/Core.agda
  src/Data/List/Relation/Unary/Any/Properties.agda
Labels: refactoring, cosmetic, dependencies

#2307 Refactor `Data.Integer.Divisibility.Signed`
  CHANGELOG.md
  src/Data/Integer/Divisibility.agda
  src/Data/Integer/Divisibility/Signed.agda
  src/Data/Integer/Properties.agda
Labels: addition, refactoring

#2320 Sublists: generalize disjoint-union-is-cospan to upper-bound-is-cospan
  CHANGELOG.md
  src/Data/List/Relation/Binary/Sublist/Propositional/Disjoint.agda
  src/Data/List/Relation/Binary/Sublist/Propositional/Slice.agda
  src/Data/List/Relation/Binary/Sublist/Setoid.agda
  standard-library.agda-lib
Labels: addition, refactoring

#2140 Predicate transformers: Reconciling `Induction.RecStruct` with `Relation.Unary.PredicateTransformer.PT`
  src/Induction.agda
Labels: low-hanging-fruit, refactoring

#2328 Github action to check for whitespace violations
  .github/workflows/whitespace.yml
Labels: admin

#2329 [refactor] Relation.Nulllary.Decidable.Core
  src/Relation/Nullary/Decidable/Core.agda
Labels: refactoring

#2322 Some design documentation (here: level polymorphism)
  doc/README/Design/LevelPolymorphism.md
  src/Data/Empty.agda
  src/Data/Unit.agda
  src/Relation/Unary.agda
Labels: documentation
