Repository agda/agda-stdlib, pull requests merged in 2025-03, with the labels that each got.

#2610 [imports] `Algebra.Module.Bundles` .. `Algebra.Morphism.*`
  src/Algebra/Module/Bundles.agda
  src/Algebra/Module/Structures.agda
  src/Algebra/Morphism/Bundles.agda
  src/Algebra/Morphism/Consequences.agda
  src/Algebra/Morphism/Construct/Composition.agda
  src/Algebra/Morphism/Construct/Initial.agda
  src/Algebra/Morphism/Construct/Terminal.agda
  src/Algebra/Morphism/GroupMonomorphism.agda
  src/Algebra/Morphism/MagmaMonomorphism.agda
  src/Algebra/Morphism/MonoidMonomorphism.agda
  src/Algebra/Morphism/RingMonomorphism.agda
  src/Algebra/Morphism/Structures.agda
Labels: dependencies

#2631 [ refactor ] `Algebra.Properties.Magma.Divisibility`
  src/Algebra/Properties/CommutativeMagma/Divisibility.agda
  src/Algebra/Properties/Magma/Divisibility.agda
Labels: bug, refactoring, cosmetic

#2633 [Import] `Data.Nat.*`
  src/Data/Nat/Binary/Base.agda
  src/Data/Nat/Binary/Properties.agda
  src/Data/Nat/Combinatorics/Specification.agda
  src/Data/Nat/Coprimality.agda
  src/Data/Nat/Divisibility/Core.agda
  src/Data/Nat/GCD.agda
  src/Data/Nat/GCD/Lemmas.agda
  src/Data/Nat/GeneralisedArithmetic.agda
  src/Data/Nat/Induction.agda
  src/Data/Nat/InfinitelyOften.agda
  src/Data/Nat/Instances.agda
  src/Data/Nat/LCM.agda
  src/Data/Nat/ListAction/Properties.agda
  src/Data/Nat/Logarithm/Core.agda
  src/Data/Nat/Primality.agda
  src/Data/Nat/Primality/Factorisation.agda
  src/Data/Nat/Properties.agda
  src/Data/Nat/Reflection.agda
  src/Data/Nat/Show.agda
  src/Data/Nat/Show/Properties.agda
  src/Data/Nat/Tactic/RingSolver.agda
Labels: dependencies

#2604 [ fix ] in non-commutative settings distinguish _∣ˡ_ and _∣ʳ_
  CHANGELOG.md
  src/Algebra/Properties/CommutativeMagma/Divisibility.agda
  src/Algebra/Properties/CommutativeSemigroup/Divisibility.agda
  src/Algebra/Properties/Magma/Divisibility.agda
  src/Algebra/Properties/Monoid/Divisibility.agda
  src/Algebra/Properties/Semigroup/Divisibility.agda
  src/Data/List/Relation/Binary/Prefix/Homogeneous/Properties.agda
  src/Data/List/Relation/Binary/Prefix/Propositional/Properties.agda
  src/Data/List/Relation/Binary/Suffix/Propositional/Properties.agda
Labels: addition, deprecation, naming

#2681 [ fix ] remove redundant `import`
  src/Algebra/Bundles/Raw.agda
Labels: low-hanging-fruit, refactoring, cosmetic, dependencies

#2683 [ add ] wellfoundedness of `Relation.Binary.Construct.Add.Infimum.Strict`
  CHANGELOG.md
  src/Relation/Binary/Construct/Add/Infimum/Strict.agda
Labels: addition

#2686 [ refactor ] Rename `Algebra.Lattice.Properties.BooleanAlgebra.{⊥≉⊤,⊤≉⊥}`
  CHANGELOG.md
  src/Algebra/Lattice/Properties/BooleanAlgebra.agda
Labels: deprecation, refactoring, naming

#2571 [ refactor ] deprecate `Algebra.Structures.IsGroup.{uniqueˡ-⁻¹|uniqueʳ-⁻¹}` with knock-ons for `Algebra.Module.*`
  CHANGELOG.md
  src/Algebra/Module/Bundles.agda
  src/Algebra/Module/Properties.agda
  src/Algebra/Module/Properties/Bimodule.agda
  src/Algebra/Module/Properties/LeftModule.agda
  src/Algebra/Module/Properties/RightModule.agda
  src/Algebra/Module/Properties/Semimodule.agda
  src/Algebra/Module/Structures.agda
  src/Algebra/Morphism.agda
  src/Algebra/Structures.agda
Labels: deprecation, refactoring
