Repository agda/agda-stdlib, pull requests merged in 2025-02, with the labels that each got.

#2561 [ refactor ] Add `Data.Bool.ListAction`
  CHANGELOG.md
  src/Data/Bool/ListAction.agda
  src/Data/List/Base.agda
  src/Data/List/Relation/Binary/Subset/Propositional/Properties.agda
  src/Data/List/Relation/Unary/All/Properties.agda
  src/Data/List/Relation/Unary/Any/Properties.agda
Labels: addition, refactoring

#2575 [ refactor ] `Axiom.ExcludedMiddle` and `Axiom.DoubleNegationElimination`
  src/Axiom/DoubleNegationElimination.agda
  src/Axiom/ExcludedMiddle.agda
Labels: refactoring, cosmetic

#2440 Implement ≤-total in terms of _≤?_
  CHANGELOG.md
  src/Data/Nat/Properties.agda
Labels: refactoring, breaking, performance

#2578 [ bug ] Fix use of `+` in lemma preconditions in favour of `∧` (bis)
  CHANGELOG.md
  src/Algebra/Construct/NaturalChoice/MinMaxOp.agda
  src/Algebra/Module/Consequences.agda
  src/Algebra/Module/Structures/Biased.agda
  src/Algebra/Properties/CancellativeCommutativeSemiring.agda
  src/Data/Rational/Unnormalised/Properties.agda
Labels: deprecation, refactoring, cosmetic, style-guide

#2558 [ refactor ] Add `Data.Nat.ListAction`
  CHANGELOG.md
  doc/README/Data/List.agda
  src/Data/List/Base.agda
  src/Data/List/Properties.agda
  src/Data/List/Relation/Binary/Permutation/Propositional/Properties.agda
  src/Data/Nat/ListAction.agda
  src/Data/Nat/ListAction/Properties.agda
  src/Data/Nat/Primality.agda
  src/Data/Nat/Primality/Factorisation.agda
  src/Data/Tree/Binary/Zipper.agda
  src/Data/Tree/Binary/Zipper/Properties.agda
  src/Test/Golden.agda
  src/Text/Format/Generic.agda
Labels: addition, library-design, deprecation, refactoring, naming, dependencies

#2574 [ refactor ] `Data.List.Relation.Unary.Enumerates.Setoid.Properties` using tighter lemma from `Function.Consequences`
  src/Data/List/Relation/Unary/Enumerates/Setoid/Properties.agda
Labels: refactoring, cosmetic

#2590 Add properties relating upTo/downFrom and map
  CHANGELOG.md
  src/Data/List/Properties.agda
Labels: addition

#2576 Rename overloaded sym in apartness
  CHANGELOG.md
  src/Algebra/Apartness/Properties/HeytingCommutativeRing.agda
  src/Algebra/Apartness/Structures.agda
Labels: bug, refactoring

#2579 [ refactor ] `Algebra.Properties.Semiring.Divisibility` and friends
  src/Algebra/Properties/Magma/Divisibility.agda
  src/Algebra/Properties/Monoid/Divisibility.agda
  src/Algebra/Properties/Semigroup/Divisibility.agda
  src/Algebra/Properties/Semiring/Divisibility.agda
  src/Algebra/Properties/Semiring/Primality.agda
Labels: refactoring, cosmetic

#2605 Cleaning import Lattice 3
  src/Algebra/Lattice/Morphism/Construct/Composition.agda
  src/Algebra/Lattice/Morphism/Construct/Identity.agda
  src/Algebra/Lattice/Morphism/LatticeMonomorphism.agda
  src/Algebra/Lattice/Morphism/Structures.agda
  src/Algebra/Lattice/Properties/BooleanAlgebra.agda
  src/Algebra/Lattice/Properties/DistributiveLattice.agda
  src/Algebra/Lattice/Properties/Lattice.agda
  src/Algebra/Lattice/Properties/Semilattice.agda
  src/Algebra/Lattice/Structures/Biased.agda
Labels: refactoring

#2602 cleaning import Lattice 1
  src/Algebra/Lattice/Bundles/Raw.agda
  src/Algebra/Lattice/Construct/NaturalChoice/MaxOp.agda
  src/Algebra/Lattice/Construct/NaturalChoice/MinMaxOp.agda
  src/Algebra/Lattice/Construct/NaturalChoice/MinOp.agda
Labels: refactoring

#2609 Import cleaning Module 3
  src/Algebra/Module/Bundles.agda
  src/Algebra/Module/Structures.agda
  src/Algebra/Module/Structures/Biased.agda
Labels: refactoring

#2598 Natural Choice Import
  src/Algebra/Construct/Add/Identity.agda
  src/Algebra/Construct/NaturalChoice/Base.agda
  src/Algebra/Construct/NaturalChoice/Max.agda
  src/Algebra/Construct/NaturalChoice/MaxOp.agda
  src/Algebra/Construct/NaturalChoice/Min.agda
  src/Algebra/Construct/NaturalChoice/MinMaxOp.agda
  src/Algebra/Construct/NaturalChoice/MinOp.agda
Labels: refactoring

#2607 Import cleaning Module 1
  src/Algebra/Module/Definitions/Bi.agda
  src/Algebra/Module/Definitions/Bi/Simultaneous.agda
  src/Algebra/Module/Definitions/Left.agda
  src/Algebra/Module/Definitions/Right.agda
  src/Algebra/Module/Morphism/Construct/Composition.agda
  src/Algebra/Module/Morphism/Construct/Identity.agda
Labels: refactoring

#2601 alegbra.definitions cleaning import
  src/Algebra/Definitions/RawMonoid.agda
  src/Algebra/Definitions/RawSemiring.agda
Labels: refactoring

#2584 [ fix ] Add correct fixities for `constructor` uses of `_,_`
  CHANGELOG.md
  src/Algebra/Definitions/RawMagma.agda
  src/Relation/Binary/Construct/Interior/Symmetric.agda
Labels: bug

#2596 [imports] `Algebra.Bundles` .. `Algebra.Consequences.*`
  src/Algebra/Bundles/Raw.agda
  src/Algebra/Consequences/Base.agda
  src/Algebra/Consequences/Propositional.agda
  src/Algebra/Consequences/Setoid.agda
Labels: dependencies

#2603 [imports] `Algebra.Lattice.Construct.*`
  src/Algebra/Lattice/Construct/DirectProduct.agda
  src/Algebra/Lattice/Construct/LiftedChoice.agda
  src/Algebra/Lattice/Construct/Subst/Equality.agda
  src/Algebra/Lattice/Construct/Zero.agda
Labels: dependencies

#2620 [imports] `Algebra.Module.Definitions.Bi.Simultaneous` .. `Data.Bool.Properties`
  src/Algebra/Module/Definitions/Bi/Simultaneous.agda
  src/Codata/Sized/Colist.agda
  src/Codata/Sized/Conat.agda
  src/Codata/Sized/Covec.agda
  src/Codata/Sized/Cowriter.agda
  src/Codata/Sized/Delay.agda
  src/Codata/Sized/M.agda
  src/Codata/Sized/Stream.agda
  src/Codata/Sized/Stream/Bisimilarity.agda
  src/Codata/Sized/Stream/Effectful.agda
  src/Codata/Sized/Stream/Instances.agda
  src/Codata/Sized/Stream/Properties.agda
  src/Codata/Sized/Thunk.agda
  src/Data/AVL/IndexedMap.agda
  src/Data/Bool/Base.agda
  src/Data/Bool/Instances.agda
  src/Data/Bool/ListAction.agda
  src/Data/Bool/Properties.agda
Labels: dependencies

#2608 [imports] `Algebra.Module.Morphism.*`
  src/Algebra/Module/Morphism/BimoduleMonomorphism.agda
  src/Algebra/Module/Morphism/BisemimoduleMonomorphism.agda
  src/Algebra/Module/Morphism/Definitions.agda
  src/Algebra/Module/Morphism/LeftModuleMonomorphism.agda
  src/Algebra/Module/Morphism/LeftSemimoduleMonomorphism.agda
  src/Algebra/Module/Morphism/ModuleHomomorphism.agda
  src/Algebra/Module/Morphism/ModuleMonomorphism.agda
  src/Algebra/Module/Morphism/RightModuleMonomorphism.agda
  src/Algebra/Module/Morphism/RightSemimoduleMonomorphism.agda
  src/Algebra/Module/Morphism/SemimoduleMonomorphism.agda
  src/Algebra/Module/Morphism/Structures.agda
Labels: refactoring

#2618 [imports] `Codata.Sized.CoFin.*` .. `Codata.Sized.CoNat.*`
  src/Codata/Sized/Cofin/Literals.agda
  src/Codata/Sized/Colist/Bisimilarity.agda
  src/Codata/Sized/Colist/Effectful.agda
  src/Codata/Sized/Colist/Properties.agda
  src/Codata/Sized/Conat/Bisimilarity.agda
  src/Codata/Sized/Conat/Properties.agda
Labels: dependencies

#2624 [imports] `Data.List.Effectful.*` .. `Relation.Nullary`
  src/Data/List/Effectful/Foldable.agda
  src/Data/List/Effectful/Transformer.agda
  src/Data/List/Extrema/Core.agda
  src/Data/List/Fresh.agda
  src/Data/List/Fresh/Membership/Setoid.agda
  src/Data/List/Fresh/Membership/Setoid/Properties.agda
  src/Data/List/Fresh/NonEmpty.agda
  src/Data/List/Fresh/Properties.agda
  src/Data/List/Fresh/Relation/Unary/All.agda
  src/Data/List/Fresh/Relation/Unary/All/Properties.agda
  src/Data/List/Fresh/Relation/Unary/Any.agda
  src/Data/List/Fresh/Relation/Unary/Any/Properties.agda
  src/Data/List/Kleene/AsList.agda
  src/Data/List/Kleene/Base.agda
  src/Relation/Nary.agda
Labels: dependencies

#2597 [imports] `Algebra.Apartness.Bundles` .. `Algebra.Construct.NaturalChoice.Base`
  src/Algebra/Apartness/Bundles.agda
  src/Algebra/Construct/Add/Identity.agda
Labels: dependencies

#2611 [imports] `Algebra.Operations.*` .. `Algebra.Properties.CommutativeSemiring.*`
  src/Algebra/Properties/BooleanAlgebra/Expression.agda
  src/Algebra/Properties/CommutativeMonoid/Sum.agda
  src/Algebra/Properties/CommutativeSemiring/Binomial.agda
  src/Algebra/Properties/CommutativeSemiring/Exp.agda
  src/Algebra/Properties/CommutativeSemiring/Exp/TCOptimised.agda
Labels: dependencies

#2623 [imports] `Data.Fin.Base` .. `Data.Integer.Tactic.RingSolver`
  src/Data/Fin/Base.agda
  src/Data/Fin/Induction.agda
  src/Data/Fin/Instances.agda
  src/Data/Fin/Literals.agda
  src/Data/Fin/Patterns.agda
  src/Data/Fin/Reflection.agda
  src/Data/Fin/Substitution.agda
  src/Data/Fin/Substitution/Example.agda
  src/Data/Float/Base.agda
  src/Data/Float/Instances.agda
  src/Data/Float/Properties.agda
  src/Data/Graph/Acyclic.agda
  src/Data/Integer/Coprimality.agda
  src/Data/Integer/DivMod.agda
  src/Data/Integer/Divisibility.agda
  src/Data/Integer/Divisibility/Signed.agda
  src/Data/Integer/GCD.agda
  src/Data/Integer/Instances.agda
  src/Data/Integer/LCM.agda
  src/Data/Integer/Properties.agda
  src/Data/Integer/Tactic/RingSolver.agda
Labels: dependencies
