Repository agda/agda-stdlib, pull requests merged in 2025-10, with the labels that each got.

#2797 [ add ] flipped version of `Relation.Nullary.Negation.Core.contradiction`
  CHANGELOG.md
  src/Relation/Nullary/Negation.agda
  src/Relation/Nullary/Negation/Core.agda
Labels: addition, refactoring

#2782 [ refactor ] `Data.Fin.Properties` following #2746
  src/Data/Fin/Properties.agda
Labels: refactoring

#2763 [ add ] `BooleanRing` plus `Properties`
  CHANGELOG.md
  src/Algebra/Bundles.agda
  src/Algebra/Consequences/Propositional.agda
  src/Algebra/Consequences/Setoid.agda
  src/Algebra/Lattice/Properties/BooleanAlgebra.agda
  src/Algebra/Properties/BooleanRing.agda
  src/Algebra/Properties/BooleanSemiring.agda
  src/Algebra/Properties/CommutativeMonoid.agda
  src/Algebra/Properties/CommutativeRing.agda
  src/Algebra/Properties/Ring.agda
  src/Algebra/Properties/Semiring.agda
  src/Algebra/Structures.agda
Labels: addition

#2822 [bug] replace wrong argument to projection in `Algebra.Morphism.Construct.DirectProduct`
  CHANGELOG.md
  src/Algebra/Morphism/Construct/DirectProduct.agda
Labels: bug
