Repository agda/agda-stdlib, pull requests merged in 2025-06, with the labels that each got.

#2732 Update imports in Cong and Utilities modules
  src/Reflection/TCM/Utilities.agda
  src/Tactic/Cong.agda
Labels: cosmetic

#2678 [ add ] `Relation.Binary.Properties.PartialSetoid`
  CHANGELOG.md
  src/Relation/Binary/Properties/PartialSetoid.agda
Labels: addition, naming

#2720 [ add ] product structure on `RawSetoid`
  CHANGELOG.md
  src/Relation/Binary/Morphism/Construct/Product.agda
Labels: addition

#2595 Adds unary disjoint relation
  CHANGELOG.md
  src/Relation/Unary.agda
  src/Relation/Unary/Properties.agda
Labels: addition, naming

#2753 [ fix] issue #2743
  src/Data/Fin/Permutation.agda
  src/Data/Fin/Permutation/Components.agda
Labels: bug

#2738 [ add ] `Relation.Nullary.Decidable.dec-yes-recompute`
  CHANGELOG.md
  src/Relation/Nullary/Decidable.agda
  src/Relation/Nullary/Decidable/Core.agda
  src/Relation/Nullary/Recomputable.agda
  src/Relation/Nullary/Recomputable/Core.agda
Labels: addition, deprecation, refactoring

#2755 Switch to Agda 2.8.0-rc3 by merging `experimental` into `master`
  .github/workflows/ci-ubuntu.yml
  CHANGELOG/v1.3.md
  README.md
  src/Algebra/Construct/Initial.agda
  src/Algebra/Operations/Semiring.agda
  src/Algebra/Properties/BooleanAlgebra.agda
  src/Algebra/Properties/DistributiveLattice.agda
  src/Data/Fin/Induction.agda
  src/Data/Fin/Properties.agda
  src/Data/List.agda
  src/Data/List/Properties.agda
  src/Data/List/Solver.agda
  src/Data/Rational/Properties.agda
  src/Data/Rational/Unnormalised/Properties.agda
  src/Function/Bijection.agda
  src/Function/Equivalence.agda
  src/Function/HalfAdjointEquivalence.agda
  src/Function/Injection.agda
  src/Function/Inverse.agda
  src/Function/LeftInverse.agda
  src/Function/Related.agda
  src/Function/Surjection.agda
Labels: admin

#2733 Refactor `Data.Vec.Properties` : Add toList-injective and new lemmas
  CHANGELOG.md
  src/Data/Vec/Properties.agda
Labels: addition
