Repository agda/agda-stdlib, pull requests merged in 2025-07, with the labels that each got.

#2748 Proved sorted permutations are equal
  CHANGELOG.md
  src/Data/Fin/Base.agda
  src/Data/Fin/Permutation.agda
  src/Data/Fin/Properties.agda
  src/Data/List/Relation/Unary/Linked.agda
  src/Data/List/Relation/Unary/Sorted/TotalOrder/Properties.agda
  src/Data/List/Sort/Base.agda
Labels: addition, documentation

#2688 [Add] Consequences of associativity for `Semigroup`s
  CHANGELOG.md
  src/Algebra/Properties/Semigroup.agda
Labels: addition, library-design, discussion, naming

#2580 [ refactor ] Restate, and use, the definitions of `Monotonic` etc. operations
  CHANGELOG.md
  src/Algebra/Consequences/Base.agda
  src/Algebra/Consequences/Propositional.agda
  src/Algebra/Consequences/Setoid.agda
  src/Algebra/Definitions.agda
  src/Algebra/Structures.agda
  src/Data/Fin/Properties.agda
  src/Data/Integer/Properties.agda
  src/Data/Nat/Properties.agda
  src/Data/Rational/Properties.agda
  src/Data/Rational/Unnormalised/Properties.agda
  src/Relation/Binary/Consequences.agda
  src/Relation/Binary/Definitions.agda
Labels: refactoring

#2692 [Add] Consequences of identity for `monoids`
  CHANGELOG.md
  src/Algebra/Properties/Monoid.agda
Labels: addition

#2756 Add instances of `IsString (List Char)`
  CHANGELOG.md
  src/Data/List/Instances.agda
Labels: addition

#2774 Fix breaking introduction of variable in `Semiring.Primality`
  src/Algebra/Properties/Semiring/Primality.agda
Labels: bug

#2773 Refactor CHANGELOG in preparation for v2.3-rc1
  CHANGELOG.md
Labels: release

#2775 reset `stdlib` for v2.4
  CHANGELOG.md
  agda-stdlib-utils.cabal
  doc/README.agda
  standard-library.agda-lib
Labels: release, admin

#2757 [ add ] `∸-suc` lemma for natural numbers
  CHANGELOG.md
  doc/README/Data/Fin/Relation/Unary/Top.agda
  src/Algebra/Properties/Semiring/Binomial.agda
  src/Data/Fin/Subset/Properties.agda
  src/Data/Nat/Binary/Subtraction.agda
  src/Data/Nat/Combinatorics.agda
  src/Data/Nat/Properties.agda
Labels: addition

#2776 [ refactor ] `CHANGELOG` for v2.3-rc2
  CHANGELOG.md
Labels: bug

#2726 [ add ] Choudhury and Fiore's alternative definition of `Permutation` for `Setoid`s
  CHANGELOG.md
  src/Data/List/Relation/Binary/Permutation/Algorithmic.agda
  src/Data/List/Relation/Binary/Permutation/Algorithmic/Properties.agda
  src/Data/List/Relation/Binary/Permutation/Declarative.agda
  src/Data/List/Relation/Binary/Permutation/Declarative/Properties.agda
Labels: addition, refactoring

#2764 [ DRY ] redefine `Algebra.Definitions.Medial` in terms of `Interchangable`
  CHANGELOG.md
  src/Algebra/Definitions.agda
  src/Algebra/Properties/CommutativeSemigroup.agda
  src/Algebra/Properties/CommutativeSemigroup/Divisibility.agda
  src/Algebra/Properties/IdempotentCommutativeMonoid.agda
  src/Algebra/Solver/CommutativeMonoid/Normal.agda
Labels: low-hanging-fruit, deprecation, refactoring, cosmetic

#2761 [ add ] rule of signs for `RingWithoutOne`
  CHANGELOG.md
  src/Algebra/Properties/RingWithoutOne.agda
Labels: addition
