Repository agda/agda-stdlib, pull requests merged in 2025-04, with the labels that each got.

#2699 [ fix ] documentation of `Algebra.Bundles.Raw` in `README.Design.Hierarchies`
  doc/README/Design/Hierarchies.agda
Labels: bug

#2694 [ fix ] attach fixity to the new declaration of `Function.Base.case_returning_of_`
  src/Function/Base.agda
Labels: bug

#2703 [add] properties of zipWith to Pointwise (Data.Vec)
  CHANGELOG.md
  src/Data/Vec/Relation/Binary/Pointwise/Inductive.agda
Labels: addition

#2707 [ fix ] redundant import in `Data.Fin.Base`
  src/Data/Fin/Base.agda
Labels: cosmetic, dependencies

#2706 Add/fix RightInverse for dependent products
  CHANGELOG.md
  src/Data/Product/Function/Dependent/Propositional.agda
  src/Data/Product/Function/Dependent/Setoid.agda
Labels: bug, addition

#2689 [add] Update PartialSetoid reasoning
  CHANGELOG.md
  src/Relation/Binary/Reasoning/Base/Partial.agda
Labels: bug

#2693 [ add ] obvious lemma about self-contradiction to `Relation.Nullary.Negation.Core`
  CHANGELOG.md
  src/Relation/Nullary/Negation/Core.agda
Labels: addition, low-hanging-fruit
