Repository agda/agda-stdlib, pull requests merged in 2025-01, with the labels that each got.

#2536 [ refactor ] add `rawSetoid` manifest fields to `Algebra.Bundles.Raw`
  CHANGELOG.md
  src/Algebra/Bundles/Raw.agda
Labels: addition, refactoring

#2535 [ refactor ] exchange left and right in `Data.List.Relation.Binary.Pointwise` etc. congruence rules for `_++_`
  CHANGELOG.md
  src/Data/List/Relation/Binary/Equality/Setoid.agda
  src/Data/List/Relation/Binary/Pointwise.agda
Labels: bug, refactoring

#2538 [ fix ] tidy up alphabetical ordering in `CHANGELOG`
  CHANGELOG.md
Labels: documentation, admin

#2527 [ add ] Module `⊆-Reasoning` for `Data.List.Relation.Binary.Sublist.*`
  CHANGELOG.md
  src/Data/List/Relation/Binary/Sublist/Heterogeneous/Properties.agda
  src/Data/List/Relation/Binary/Sublist/Setoid/Properties.agda
Labels: addition

#2424 Vec.Properties: introduce `≈-cong′`
  CHANGELOG.md
  doc/README/Data/Vec/Relation/Binary/Equality/Cast.agda
  src/Data/Vec/Properties.agda
  src/Data/Vec/Relation/Binary/Equality/Cast.agda
Labels: addition

#2541 Cleanup README comments to catch up with #2424
  doc/README/Data/Vec/Relation/Binary/Equality/Cast.agda
  src/Data/Vec/Properties.agda
Labels: refactoring, documentation

#2548 [ refactor ] Remove use of `rewrite` from `Data.List.Membership.Propositional.Properties.Core`
  src/Data/List/Membership/Propositional.agda
  src/Data/List/Membership/Propositional/Properties/Core.agda
Labels: refactoring, cosmetic

#2557 Update documentation from v2.2 release version to v2.3-dev
  CHANGELOG.md
  CHANGELOG/v2.2.md
  doc/README.agda
Labels: documentation, admin

#2544 Update CI
  .github/workflows/ci-ubuntu.yml
  .github/workflows/haskell-ci.yml
  agda-stdlib-utils.cabal
Labels: continuous-integration

#2546 agda/agda#7674 eta-expand fields in record expression
  src/Algebra/Construct/Initial.agda
Labels: upstream

#2555 Add a few algebraic structures missing from the Algebra.Construct.Pointwise
  CHANGELOG.md
  src/Algebra/Construct/Pointwise.agda
Labels: addition

#2562 [ refactor ] rename `∣∣` to `∥`, `∤∤` to `∦` throughout `Algebra.Definitions.RawMagma` and `Algebra.Properties.*.Divisibility`
  CHANGELOG.md
  doc/style-guide.md
  src/Algebra/Definitions/RawMagma.agda
  src/Algebra/Properties/Magma/Divisibility.agda
  src/Algebra/Properties/Monoid/Divisibility.agda
  src/Algebra/Properties/Semigroup/Divisibility.agda
Labels: deprecation, refactoring

#2564 [ bug ] Fix use of `+` in lemma preconditions in favour of `∧`
  src/Data/Nat/Properties.agda
Labels: bug, deprecation, cosmetic
