Repository agda/agda-stdlib, pull requests merged in 2025-08, with the labels that each got.

#2785 [ refactor ] weaken type of `Relation.Nullary.Negation.Core.contradiction-irr`
  CHANGELOG.md
  src/Relation/Nullary/Negation/Core.agda
Labels: refactoring

#2740 [ refactor ] `Data.Fin.Properties` of decidable equality, plus knock-ons
  CHANGELOG.md
  src/Data/Fin/Permutation.agda
  src/Data/Fin/Permutation/Components.agda
  src/Data/Fin/Properties.agda
  src/Data/Nat/Properties.agda
Labels: addition, refactoring, dependencies

#2799 Backport changes from 2.3 release to 2.4
  CHANGELOG/v2.3.md
  CITATION.cff
  README.md
  doc/installation-guide.md
  src/Algebra/Construct/Flip/Op.agda
  src/Data/Fin/Properties.agda
  src/Data/Sum/Relation/Binary/LeftOrder.agda
  src/Data/Sum/Relation/Binary/Pointwise.agda
Labels: admin
